[package]
name = "bray-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-ir = { path = "../bray-ir" }

[dev-dependencies]
bray-testing = { path = "../bray-testing", features = ["bound-unit"] }

[lints]
workspace = true
