[package]
name = "bray-symbols"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
test-support = []

[dependencies]
bray-base = { path = "../bray-base" }
bray-compiler-known = { path = "../bray-compiler-known" }
bray-declarations = { path = "../bray-declarations" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-source = { path = "../bray-source" }
bray-syntax = { path = "../bray-syntax" }

[dev-dependencies]
bray-parser = { path = "../bray-parser" }
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
