[package]
name = "bray-symbols"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-declarations = { path = "../bray-declarations" }

[dev-dependencies]
bray-parser = { path = "../bray-parser" }
bray-source = { path = "../bray-source" }
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
