[package]
name = "bray-project"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-standard-library = { path = "../bray-standard-library" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
