[package]
name = "bray-platform-abi"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bray-platform = { path = "../bray-platform" }
bray-runtime-interface = { path = "../bray-runtime-interface" }

[dev-dependencies]
bray-testing = { path = "../bray-testing" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Globalization"] }

[lints]
workspace = true
