[package]
name = "bray-platform-abi"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bray-platform = { path = "../bray-platform" }
bray-platform-abi-support = { path = "../bray-platform-abi-support" }
bray-platform-abi-temporal = { path = "../bray-platform-abi-temporal" }
bray-runtime-interface = { path = "../bray-runtime-interface" }

[dev-dependencies]
bray-testing = { path = "../bray-testing" }

[build-dependencies]
cc = "1.2.48"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Globalization"] }

[lints]
workspace = true
