use std::fmt::Write;

use super::super::model::{
    AggregateDescription, BitfieldDescription, CallbackDescription, DynamicSymbolDescription,
    FlexibleDescription, FunctionDescription, LinkDescription, OpaqueDescription,
    OverrideAuthority, ParameterDescription, StaticDescription, SymbolDescription,
    TargetDescription, TypeDescription,
};

// Formatting through String's fmt::Write implementation has no failure path.
use super::bits::bit_mask;

pub(super) fn bray(target: &TargetDescription, digest: &str) -> Result<String, String> {
    let mut source = String::new();

    writeln!(
        source,
        "// Generated by `cargo xtask standard-library os-bindings generate`."
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "// SDK authority: {} {}",
        target.sdk.authority,
        target.sdk.revision.label()
    )
    .expect("writing to a string must succeed");

    if let Some(runtime) = &target.sdk.compiler_runtime {
        writeln!(
            source,
            "// Compiler runtime authority: {} {}",
            runtime.authority, runtime.revision
        )
        .expect("writing to a string must succeed");
    }

    writeln!(source, "// Complete input SHA-256: {digest}")
        .expect("writing to a string must succeed");

    source.push('\n');

    writeln!(
        source,
        "@target(target.identity.NAME == \"{}\")",
        target.target
    )
    .expect("writing to a string must succeed");

    writeln!(source, "trusted module std.os.{};", target.system)
        .expect("writing to a string must succeed");

    render_scalars(&mut source, target);

    for constant in &target.constants {
        source.push('\n');

        writeln!(
            source,
            "const {}: {} = {};",
            constant.name, constant.ty, constant.value
        )
        .expect("writing to a string must succeed");
    }

    for ty in &target.types {
        render_type(&mut source, ty);
    }

    for callback in &target.callbacks {
        render_callback(&mut source, callback);
    }

    for function in &target.functions {
        render_function(&mut source, target, function);
    }

    for static_ in &target.statics {
        render_static(&mut source, target, static_);
    }

    for symbol in &target.dynamic_symbols {
        render_dynamic_symbol(&mut source, symbol);
    }

    bray_formatter::format_text(&source, &bray_formatter::FormatterConfiguration::default())
        .map(|outcome| outcome.into_text())
        .map_err(|error| {
            format!(
                "could not format generated {} OS bindings: {error:?}",
                target.target
            )
        })
}

fn render_scalars(source: &mut String, target: &TargetDescription) {
    for scalar in &target.scalars {
        source.push('\n');

        writeln!(
            source,
            "// Native scalar `{}` maps to `{}` with size {} and alignment {}.",
            scalar.native, scalar.bray, scalar.size, scalar.align
        )
        .expect("writing to a string must succeed");
    }
}

fn render_type(source: &mut String, ty: &TypeDescription) {
    match ty {
        TypeDescription::Structure(aggregate) => render_structure(source, aggregate),
        TypeDescription::Union(aggregate) => render_union(source, aggregate),
        TypeDescription::Incomplete(incomplete) => {
            source.push('\n');

            writeln!(source, "struct {};", incomplete.name)
                .expect("writing to a string must succeed");
        }
        TypeDescription::Opaque(opaque) => render_opaque(source, opaque),
        TypeDescription::Flexible(flexible) => render_flexible(source, flexible),
        TypeDescription::Bitfields(bitfields) => render_bitfields(source, bitfields),
    }
}

fn render_structure(source: &mut String, aggregate: &AggregateDescription) {
    render_aggregate_metadata(source, aggregate);

    writeln!(source, "@copy").expect("writing to a string must succeed");
    writeln!(source, "@layout(c)").expect("writing to a string must succeed");
    writeln!(source, "struct {}", aggregate.name).expect("writing to a string must succeed");
    writeln!(source, "{{").expect("writing to a string must succeed");

    for field in &aggregate.fields {
        writeln!(source, "    {}: {};", field.name, field.ty)
            .expect("writing to a string must succeed");
    }

    writeln!(source, "}}").expect("writing to a string must succeed");
}

fn render_union(source: &mut String, aggregate: &AggregateDescription) {
    render_aggregate_metadata(source, aggregate);

    writeln!(source, "@copy").expect("writing to a string must succeed");
    writeln!(source, "@layout(c, tag = none)").expect("writing to a string must succeed");
    writeln!(source, "union {}", aggregate.name).expect("writing to a string must succeed");
    writeln!(source, "{{").expect("writing to a string must succeed");

    for field in &aggregate.fields {
        writeln!(
            source,
            "    {}({}: {});",
            pascal_case(&field.name),
            field.name,
            field.ty
        )
        .expect("writing to a string must succeed");
    }

    writeln!(source, "}}").expect("writing to a string must succeed");
}

fn render_aggregate_metadata(source: &mut String, aggregate: &AggregateDescription) {
    source.push('\n');

    writeln!(
        source,
        "// Native `{}` has size {}, alignment {}, and {} ABI classification.",
        aggregate.native,
        aggregate.size,
        aggregate.align,
        aggregate.classification.as_str()
    )
    .expect("writing to a string must succeed");

    if let Some(contract) = &aggregate.active_variant_contract {
        writeln!(source, "// Active variant contract: {contract}.")
            .expect("writing to a string must succeed");
    }

    render_override_authority(source, &aggregate.override_);
}

fn render_opaque(source: &mut String, opaque: &OpaqueDescription) {
    source.push('\n');

    writeln!(
        source,
        "// Native `{}` uses {} ABI classification.",
        opaque.native,
        opaque.classification.as_str()
    )
    .expect("writing to a string must succeed");

    render_override_authority(source, &opaque.override_);

    writeln!(
        source,
        "@layout(c, size = {}, align = {})",
        opaque.size, opaque.align
    )
    .expect("writing to a string must succeed");

    writeln!(source, "struct {};", opaque.name).expect("writing to a string must succeed");
}

fn render_flexible(source: &mut String, flexible: &FlexibleDescription) {
    source.push('\n');

    writeln!(
        source,
        "// Native `{}` has alignment {}, {} ABI classification, and trailing storage at offset {}.",
        flexible.native,
        flexible.align,
        flexible.classification.as_str(),
        flexible.tail.offset
    )
    .expect("writing to a string must succeed");

    writeln!(source, "@layout(c)").expect("writing to a string must succeed");
    writeln!(source, "struct {}", flexible.name).expect("writing to a string must succeed");
    writeln!(source, "{{").expect("writing to a string must succeed");

    for field in &flexible.fields {
        writeln!(source, "    {}: {};", field.name, field.ty)
            .expect("writing to a string must succeed");
    }

    writeln!(
        source,
        "    {}: [{}; ..];",
        flexible.tail.name, flexible.tail.ty
    )
    .expect("writing to a string must succeed");

    writeln!(source, "}}").expect("writing to a string must succeed");
}

fn render_bitfields(source: &mut String, bitfields: &BitfieldDescription) {
    source.push('\n');

    writeln!(
        source,
        "// Native `{}` has size {}, alignment {}, and {} ABI classification.",
        bitfields.native,
        bitfields.size,
        bitfields.align,
        bitfields.classification.as_str()
    )
    .expect("writing to a string must succeed");

    render_override_authority(source, &bitfields.override_);

    writeln!(source, "@copy").expect("writing to a string must succeed");
    writeln!(source, "@layout(c)").expect("writing to a string must succeed");
    writeln!(source, "struct {}", bitfields.name).expect("writing to a string must succeed");
    writeln!(source, "{{").expect("writing to a string must succeed");

    writeln!(
        source,
        "    internal mut {}: {};",
        bitfields.backing_name, bitfields.backing_type
    )
    .expect("writing to a string must succeed");

    for field in &bitfields.fields {
        writeln!(source, "    {}: {};", field.name, field.ty)
            .expect("writing to a string must succeed");
    }

    for field in &bitfields.bitfields {
        let mask = bit_mask(field.width);
        let maximum = mask;

        source.push('\n');

        writeln!(
            source,
            "    func {}() -> {}",
            field.name, bitfields.backing_type
        )
        .expect("writing to a string must succeed");

        writeln!(source, "    {{").expect("writing to a string must succeed");

        writeln!(
            source,
            "        return self.{} >> {} & {};",
            bitfields.backing_name, field.shift, mask
        )
        .expect("writing to a string must succeed");

        writeln!(source, "    }}").expect("writing to a string must succeed");

        source.push('\n');

        writeln!(
            source,
            "    mut func set_{}(pos value: {}) -> bool",
            field.name, bitfields.backing_type
        )
        .expect("writing to a string must succeed");

        writeln!(source, "    {{").expect("writing to a string must succeed");

        writeln!(source, "        if value > {maximum}").expect("writing to a string must succeed");

        writeln!(source, "        {{").expect("writing to a string must succeed");

        writeln!(source, "            return false;").expect("writing to a string must succeed");

        writeln!(source, "        }}").expect("writing to a string must succeed");

        source.push('\n');

        writeln!(
            source,
            "        self.{} = self.{} & ~({} << {}) | value << {};",
            bitfields.backing_name, bitfields.backing_name, mask, field.shift, field.shift
        )
        .expect("writing to a string must succeed");

        source.push('\n');

        writeln!(source, "        return true;").expect("writing to a string must succeed");
        writeln!(source, "    }}").expect("writing to a string must succeed");
    }

    writeln!(source, "}}").expect("writing to a string must succeed");
}

fn render_callback(source: &mut String, callback: &CallbackDescription) {
    source.push('\n');

    write!(
        source,
        "callable {} = @abi({}) func(",
        callback.name,
        callback.abi.as_str()
    )
    .expect("writing to a string must succeed");

    render_parameters(source, &callback.parameters);

    writeln!(source, ") -> {};", callback.result).expect("writing to a string must succeed");
}

fn render_function(
    source: &mut String,
    target: &TargetDescription,
    function: &FunctionDescription,
) {
    // Model validation guarantees that every function names a declared link.
    let link = target
        .links
        .iter()
        .find(|link| link.name == function.link)
        .expect("validated function links must exist");

    render_contract_metadata(
        source,
        function.error_state.as_deref(),
        function.ownership.as_deref(),
        function.initialization.as_deref(),
        &function.dependencies,
    );

    render_link(source, link);
    render_symbol(source, function.symbol.as_ref(), &function.native);

    writeln!(source, "@abi({})", function.abi.as_str()).expect("writing to a string must succeed");

    write!(source, "extern trusted func {}(", function.name)
        .expect("writing to a string must succeed");

    render_parameters(source, &function.parameters);

    if function.variadic {
        if !function.parameters.is_empty() {
            source.push_str(", ");
        }

        source.push_str("...");
    }

    writeln!(source, ") -> {}", function.result).expect("writing to a string must succeed");

    render_predicate_clause(source, "requires", &function.requires);
    render_predicate_clause(source, "ensures", &function.ensures);

    writeln!(source, "    uses(foreign_call);").expect("writing to a string must succeed");
}

fn render_predicate_clause(source: &mut String, clause: &str, conditions: &[String]) {
    if conditions.is_empty() {
        return;
    }

    writeln!(source, "    {clause}(").expect("writing to a string must succeed");

    for condition in conditions {
        writeln!(source, "        {condition},").expect("writing to a string must succeed");
    }

    writeln!(source, "    )").expect("writing to a string must succeed");
}

fn render_static(source: &mut String, target: &TargetDescription, static_: &StaticDescription) {
    // Model validation guarantees that every static names a declared link.
    let link = target
        .links
        .iter()
        .find(|link| link.name == static_.link)
        .expect("validated static links must exist");

    render_contract_metadata(
        source,
        None,
        static_.ownership.as_deref(),
        None,
        &static_.dependencies,
    );

    render_link(source, link);
    render_symbol(source, Some(&static_.symbol), &static_.native);

    if static_.thread_local {
        writeln!(source, "@thread_local").expect("writing to a string must succeed");
    }

    write!(source, "extern trusted static ").expect("writing to a string must succeed");

    if static_.mutable {
        source.push_str("mut ");
    }

    writeln!(source, "{}: {};", static_.name, static_.ty)
        .expect("writing to a string must succeed");
}

fn render_dynamic_symbol(source: &mut String, symbol: &DynamicSymbolDescription) {
    let name = symbol.symbol.as_bytes();

    source.push('\n');

    writeln!(
        source,
        "// Dynamic {} symbol `{}` comes from `{}`.",
        symbol.target.as_str(),
        symbol.symbol,
        symbol.library
    )
    .expect("writing to a string must succeed");

    if let Some(ownership) = &symbol.ownership {
        writeln!(source, "// Ownership contract: {ownership}.")
            .expect("writing to a string must succeed");
    }

    if !symbol.dependencies.is_empty() {
        writeln!(
            source,
            "// Dependencies: {}.",
            symbol.dependencies.join(", ")
        )
        .expect("writing to a string must succeed");
    }

    writeln!(
        source,
        "trusted func {}(pos library: &std.dynamic.DynamicLibrary) -> Result<std.dynamic.DynamicSymbol<{}>, std.ffi.ForeignError>",
        symbol.name, symbol.ty
    )
    .expect("writing to a string must succeed");

    writeln!(source, "    requires(blocking_execution())")
        .expect("writing to a string must succeed");

    writeln!(source, "    uses(foreign_call, layout_reinterpret)")
        .expect("writing to a string must succeed");

    writeln!(source, "{{").expect("writing to a string must succeed");

    writeln!(
        source,
        "    let name: [u8; {}] = [{}];",
        name.len(),
        name.iter()
            .map(u8::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
    .expect("writing to a string must succeed");

    source.push('\n');

    writeln!(
        source,
        "    return trusted std.dynamic.symbol<{}>(library, &name[..]);",
        symbol.ty
    )
    .expect("writing to a string must succeed");

    writeln!(source, "}}").expect("writing to a string must succeed");
}

fn render_contract_metadata(
    source: &mut String,
    error_state: Option<&str>,
    ownership: Option<&str>,
    initialization: Option<&str>,
    dependencies: &[String],
) {
    source.push('\n');

    for (label, value) in [
        ("Error state", error_state),
        ("Ownership", ownership),
        ("Initialization", initialization),
    ] {
        if let Some(value) = value {
            writeln!(source, "// {label}: {value}.").expect("writing to a string must succeed");
        }
    }

    if !dependencies.is_empty() {
        writeln!(source, "// Dependencies: {}.", dependencies.join(", "))
            .expect("writing to a string must succeed");
    }
}

fn render_link(source: &mut String, link: &LinkDescription) {
    writeln!(
        source,
        "@link(name = \"{}\", kind = {})",
        link.name,
        link.kind.as_str()
    )
    .expect("writing to a string must succeed");
}

fn render_symbol(source: &mut String, symbol: Option<&SymbolDescription>, fallback: &str) {
    let Some(symbol) = symbol else {
        writeln!(source, "@symbol(name = \"{fallback}\")")
            .expect("writing to a string must succeed");

        return;
    };

    let identity = match (&symbol.name, symbol.ordinal) {
        (Some(name), None) => format!("name = \"{name}\""),
        (None, Some(ordinal)) => format!("ordinal = {ordinal}"),
        _ => unreachable!("validated symbols select one identity"),
    };

    let mut options = vec![identity];

    if let Some(version) = &symbol.version {
        options.push(format!("version = \"{version}\""));
    }

    if symbol.binding.as_str() != "strong" {
        options.push(format!("binding = {}", symbol.binding.as_str()));
    }

    if symbol.presence.as_str() != "required" {
        options.push(format!("presence = {}", symbol.presence.as_str()));
    }

    writeln!(source, "@symbol({})", options.join(", ")).expect("writing to a string must succeed");
}

fn render_parameters(source: &mut String, parameters: &[ParameterDescription]) {
    for (index, parameter) in parameters.iter().enumerate() {
        if index != 0 {
            source.push_str(", ");
        }

        write!(source, "pos {}: {}", parameter.name, parameter.ty)
            .expect("writing to a string must succeed");
    }
}

fn render_override_authority(source: &mut String, override_: &Option<OverrideAuthority>) {
    let Some(override_) = override_ else {
        return;
    };

    writeln!(
        source,
        "// Native layout authority: {}.",
        override_.authority
    )
    .expect("writing to a string must succeed");

    writeln!(source, "// Native layout rationale: {}.", override_.reason)
        .expect("writing to a string must succeed");
}

fn pascal_case(name: &str) -> String {
    let mut result = String::new();

    for word in name.split('_') {
        let mut characters = word.chars();

        if let Some(first) = characters.next() {
            result.extend(first.to_uppercase());
            result.extend(characters);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::{pascal_case, render_symbol};
    use crate::standard_library::os_bindings::model::{
        SymbolBinding, SymbolDescription, SymbolPresence,
    };

    #[test]
    fn union_variants_use_pascal_case() {
        assert_eq!(pascal_case("signed_value"), "SignedValue");
    }

    #[test]
    fn symbol_directives_preserve_orthogonal_identity_options() {
        let mut source = String::new();

        render_symbol(
            &mut source,
            Some(&SymbolDescription {
                name: None,
                ordinal: Some(17),
                version: None,
                binding: SymbolBinding::Weak,
                presence: SymbolPresence::Optional,
            }),
            "unused",
        );

        assert_eq!(
            source,
            "@symbol(ordinal = 17, binding = weak, presence = optional)\n"
        );
    }
}
