use std::fmt::Write;

use super::super::model::{
    BitfieldDescription, CallbackDescription, DynamicSymbolDescription, FieldDescription,
    FunctionDescription, ParameterDescription, StaticDescription, TargetDescription,
    TypeDescription,
};

// Formatting through String's fmt::Write implementation has no failure path.
use super::bits::bit_mask;

pub(super) fn probe(target: &TargetDescription, digest: &str) -> String {
    let mut source = String::new();

    writeln!(
        source,
        "/* Generated by cargo xtask standard-library os-bindings generate. */"
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "/* SDK authority: {} {} */",
        target.sdk.authority, target.sdk.revision
    )
    .expect("writing to a string must succeed");

    writeln!(source, "/* Complete input SHA-256: {digest} */")
        .expect("writing to a string must succeed");

    source.push('\n');

    writeln!(source, "#include <stddef.h>").expect("writing to a string must succeed");
    writeln!(source, "#include <stdint.h>").expect("writing to a string must succeed");
    writeln!(source, "#include <string.h>").expect("writing to a string must succeed");

    for definition in &target.sdk.probe_definitions {
        writeln!(source, "#define {definition}").expect("writing to a string must succeed");
    }

    for header in &target.sdk.headers {
        writeln!(source, "#include <{header}>").expect("writing to a string must succeed");
    }

    source.push('\n');

    for scalar in &target.scalars {
        writeln!(
            source,
            "_Static_assert(sizeof({}) == {}, \"{} size\");",
            scalar.native, scalar.size, scalar.native
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "_Static_assert(_Alignof({}) == {}, \"{} alignment\");",
            scalar.native, scalar.align, scalar.native
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "_Static_assert((({})-1 < ({})0) == {}, \"{} signedness\");",
            scalar.native,
            scalar.native,
            u8::from(scalar.signed),
            scalar.native
        )
        .expect("writing to a string must succeed");
    }

    for constant in &target.constants {
        writeln!(
            source,
            "_Static_assert(({}) == {}, \"{} value\");",
            constant.native, constant.value, constant.native
        )
        .expect("writing to a string must succeed");
    }

    for ty in &target.types {
        render_probe_type(&mut source, ty);
    }

    for callback in &target.callbacks {
        render_probe_callback(&mut source, callback);
    }

    for function in &target.functions {
        render_probe_function(&mut source, function);
    }

    for static_ in &target.statics {
        render_probe_static(&mut source, target, static_);
    }

    source.push('\n');

    writeln!(source, "int main(void)").expect("writing to a string must succeed");
    writeln!(source, "{{").expect("writing to a string must succeed");

    let mut failure = 1;

    for ty in &target.types {
        if let TypeDescription::Bitfields(bitfields) = ty {
            render_bitfield_probe_body(&mut source, bitfields, &mut failure);
        }
    }

    for function in &target.functions {
        writeln!(source, "    (void)&{};", function.native)
            .expect("writing to a string must succeed");
    }

    for static_ in &target.statics {
        writeln!(source, "    (void)&{};", probe_static_name(static_))
            .expect("writing to a string must succeed");
    }

    for symbol in &target.dynamic_symbols {
        render_dynamic_probe_body(&mut source, target, symbol, &mut failure);
    }

    writeln!(source, "    return 0;").expect("writing to a string must succeed");
    writeln!(source, "}}").expect("writing to a string must succeed");

    source
}

fn render_probe_type(source: &mut String, ty: &TypeDescription) {
    match ty {
        TypeDescription::Structure(aggregate) | TypeDescription::Union(aggregate) => {
            render_probe_layout(source, &aggregate.native, aggregate.size, aggregate.align);

            for field in &aggregate.fields {
                render_probe_field(source, &aggregate.native, field);
            }
        }
        TypeDescription::Incomplete(incomplete) => {
            writeln!(
                source,
                "_Static_assert(sizeof({} *) == sizeof(void *), \"{} pointer representation\");",
                incomplete.native, incomplete.native
            )
            .expect("writing to a string must succeed");
        }
        TypeDescription::Opaque(opaque) => {
            render_probe_layout(source, &opaque.native, opaque.size, opaque.align);
        }
        TypeDescription::Flexible(flexible) => {
            writeln!(
                source,
                "_Static_assert(_Alignof({}) == {}, \"{} alignment\");",
                flexible.native, flexible.align, flexible.native
            )
            .expect("writing to a string must succeed");

            for field in &flexible.fields {
                render_probe_field(source, &flexible.native, field);
            }

            writeln!(
                source,
                "_Static_assert(offsetof({}, {}) == {}, \"{}.{} offset\");",
                flexible.native,
                flexible.tail.native,
                flexible.tail.offset,
                flexible.native,
                flexible.tail.native
            )
            .expect("writing to a string must succeed");

            writeln!(
                source,
                "_Static_assert(sizeof((({} *)0)->{}[0]) == sizeof({}), \"{}.{} element\");",
                flexible.native,
                flexible.tail.native,
                flexible.tail.native_type,
                flexible.native,
                flexible.tail.native
            )
            .expect("writing to a string must succeed");
        }
        TypeDescription::Bitfields(bitfields) => {
            render_probe_layout(source, &bitfields.native, bitfields.size, bitfields.align);

            for field in &bitfields.fields {
                render_probe_field(source, &bitfields.native, field);
            }
        }
    }
}

fn render_probe_layout(source: &mut String, native: &str, size: u64, align: u64) {
    writeln!(
        source,
        "_Static_assert(sizeof({native}) == {size}, \"{native} size\");"
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(_Alignof({native}) == {align}, \"{native} alignment\");"
    )
    .expect("writing to a string must succeed");
}

fn render_probe_field(source: &mut String, native: &str, field: &FieldDescription) {
    writeln!(
        source,
        "_Static_assert(offsetof({}, {}) == {}, \"{}.{} offset\");",
        native, field.native, field.offset, native, field.native
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(sizeof((({} *)0)->{}) == sizeof({}), \"{}.{} type\");",
        native, field.native, field.native_type, native, field.native
    )
    .expect("writing to a string must succeed");
}

fn render_probe_callback(source: &mut String, callback: &CallbackDescription) {
    let parameters = native_parameters(&callback.parameters);

    writeln!(
        source,
        "typedef {} (*bray_probe_{})({});",
        callback.native_result, callback.name, parameters
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(__builtin_types_compatible_p({}, bray_probe_{}), \"{} callback\");",
        callback.native, callback.name, callback.native
    )
    .expect("writing to a string must succeed");
}

fn render_probe_function(source: &mut String, function: &FunctionDescription) {
    if function.variadic {
        writeln!(
            source,
            "static __typeof__(&{}) bray_probe_{} = &{};",
            function.native, function.name, function.native
        )
        .expect("writing to a string must succeed");

        return;
    }

    let parameters = native_parameters(&function.parameters);

    writeln!(
        source,
        "typedef {} (*bray_probe_{}_type)({});",
        function.native_result, function.name, parameters
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(__builtin_types_compatible_p(__typeof__(&{}), bray_probe_{}_type), \"{} signature\");",
        function.native, function.name, function.native
    )
    .expect("writing to a string must succeed");
}

fn render_probe_static(
    source: &mut String,
    target: &TargetDescription,
    static_: &StaticDescription,
) {
    let probe_name = probe_static_name(static_);

    if static_.thread_local {
        writeln!(
            source,
            "extern _Thread_local {} {};",
            static_.native_type, probe_name
        )
        .expect("writing to a string must succeed");

        if target.system == "linux" {
            if let Some(version) = &static_.symbol.version {
                // Model validation guarantees that a versioned symbol has a name.
                let symbol = static_
                    .symbol
                    .name
                    .as_deref()
                    .expect("validated versioned symbols must have names");

                writeln!(
                    source,
                    "__asm__(\".symver {},{}@{}\");",
                    probe_name, symbol, version
                )
                .expect("writing to a string must succeed");
            }
        }
    }

    writeln!(
        source,
        "_Static_assert(__builtin_types_compatible_p(__typeof__({}), {}), \"{} storage type\");",
        probe_name, static_.native_type, static_.native
    )
    .expect("writing to a string must succeed");
}

fn probe_static_name(static_: &StaticDescription) -> String {
    if static_.thread_local {
        format!("bray_probe_{}", static_.name)
    } else {
        static_.native.clone()
    }
}

fn render_dynamic_probe_body(
    source: &mut String,
    target: &TargetDescription,
    symbol: &DynamicSymbolDescription,
    failure: &mut u32,
) {
    let library = c_string(&symbol.library);
    let native_symbol = c_string(&symbol.symbol);

    if target.system == "windows" {
        writeln!(
            source,
            "    HMODULE bray_probe_{}_library = LoadLibraryA(\"{}\");",
            symbol.name, library
        )
        .expect("writing to a string must succeed");

        render_failure_check(
            source,
            &format!("bray_probe_{}_library == NULL", symbol.name),
            failure,
        );

        render_failure_check(
            source,
            &format!(
                "GetProcAddress(bray_probe_{}_library, \"{}\") == NULL",
                symbol.name, native_symbol
            ),
            failure,
        );

        render_failure_check(
            source,
            &format!("!FreeLibrary(bray_probe_{}_library)", symbol.name),
            failure,
        );
    } else {
        writeln!(
            source,
            "    void *bray_probe_{}_library = dlopen(\"{}\", RTLD_NOW | RTLD_LOCAL);",
            symbol.name, library
        )
        .expect("writing to a string must succeed");

        render_failure_check(
            source,
            &format!("bray_probe_{}_library == NULL", symbol.name),
            failure,
        );

        render_failure_check(
            source,
            &format!(
                "dlsym(bray_probe_{}_library, \"{}\") == NULL",
                symbol.name, native_symbol
            ),
            failure,
        );

        render_failure_check(
            source,
            &format!("dlclose(bray_probe_{}_library) != 0", symbol.name),
            failure,
        );
    }
}

fn c_string(value: &str) -> String {
    let mut escaped = String::new();

    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            character => escaped.push(character),
        }
    }

    escaped
}

fn native_parameters(parameters: &[ParameterDescription]) -> String {
    if parameters.is_empty() {
        return "void".to_owned();
    }

    parameters
        .iter()
        .map(|parameter| parameter.native_type.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_failure_check(source: &mut String, condition: &str, failure: &mut u32) {
    writeln!(source, "    if ({condition})").expect("writing to a string must succeed");
    writeln!(source, "        return {failure};").expect("writing to a string must succeed");

    *failure += 1;
}

fn render_bitfield_probe_body(
    source: &mut String,
    bitfields: &BitfieldDescription,
    failure: &mut u32,
) {
    writeln!(
        source,
        "    {} bray_probe_{} = {{0}};",
        bitfields.native, bitfields.name
    )
    .expect("writing to a string must succeed");

    for field in &bitfields.bitfields {
        let maximum = bit_mask(field.width);
        let mask = maximum << field.shift;

        writeln!(
            source,
            "    bray_probe_{}.{} = {};",
            bitfields.name, field.native, maximum
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "    {} bray_probe_{}_backing = 0;",
            bitfields.native_backing_type, field.name
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "    memcpy(&bray_probe_{}_backing, (unsigned char *)&bray_probe_{} + {}, sizeof(bray_probe_{}_backing));",
            field.name, bitfields.name, bitfields.backing_offset, field.name
        )
        .expect("writing to a string must succeed");

        render_failure_check(
            source,
            &format!(
                "(bray_probe_{}_backing & {}) >> {} != {}",
                field.name, mask, field.shift, maximum
            ),
            failure,
        );
    }
}

#[cfg(test)]
mod tests {
    use super::{native_parameters, render_failure_check};

    #[test]
    fn empty_native_parameters_use_the_c_void_form() {
        assert_eq!(native_parameters(&[]), "void");
    }

    #[test]
    fn failure_checks_follow_the_native_fixture_style() {
        let mut source = String::new();
        let mut failure = 4;

        render_failure_check(&mut source, "value == NULL", &mut failure);

        assert_eq!(source, "    if (value == NULL)\n        return 4;\n");
        assert_eq!(failure, 5);
    }
}
