use std::fmt::Write;

use super::super::model::{
    BitfieldDescription, CallbackDescription, DynamicSymbolDescription, FieldDescription,
    FunctionDescription, ParameterDescription, SdkRevision, StaticDescription, SymbolBinding,
    SymbolDescription, SymbolPresence, TargetDescription, TypeDescription,
};

// Formatting through String's fmt::Write implementation has no failure path.
use super::bits::bit_mask;
use super::types::render_abi_type_contracts;

pub(super) fn probe(target: &TargetDescription, digest: &str) -> String {
    let mut source = String::new();

    writeln!(
        source,
        "/* Generated by cargo xtask standard-library os-bindings generate. */"
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "/* SDK authority: {} {} */",
        target.sdk.authority,
        target.sdk.revision.label()
    )
    .expect("writing to a string must succeed");

    if let Some(runtime) = &target.sdk.compiler_runtime {
        writeln!(
            source,
            "/* Compiler runtime authority: {} {} */",
            runtime.authority, runtime.revision
        )
        .expect("writing to a string must succeed");
    }

    writeln!(source, "/* Complete input SHA-256: {digest} */")
        .expect("writing to a string must succeed");

    source.push('\n');

    writeln!(source, "#include <stddef.h>").expect("writing to a string must succeed");
    writeln!(source, "#include <stdint.h>").expect("writing to a string must succeed");
    writeln!(source, "#include <string.h>").expect("writing to a string must succeed");

    for definition in &target.sdk.probe_definitions {
        writeln!(source, "#define {definition}").expect("writing to a string must succeed");
    }

    for header in &target.sdk.headers {
        writeln!(source, "#include <{header}>").expect("writing to a string must succeed");
    }

    source.push('\n');

    render_sdk_revision_contract(&mut source, &target.sdk.revision);

    for scalar in &target.scalars {
        writeln!(
            source,
            "_Static_assert(sizeof({}) == {}, \"{} size\");",
            scalar.native, scalar.size, scalar.native
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "_Static_assert(_Alignof({}) == {}, \"{} alignment\");",
            scalar.native, scalar.align, scalar.native
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "_Static_assert((({})-1 < ({})0) == {}, \"{} signedness\");",
            scalar.native,
            scalar.native,
            u8::from(scalar.signed),
            scalar.native
        )
        .expect("writing to a string must succeed");
    }

    for constant in &target.constants {
        writeln!(
            source,
            "_Static_assert(({}) == {}, \"{} value\");",
            constant.native, constant.value, constant.native
        )
        .expect("writing to a string must succeed");
    }

    for ty in &target.types {
        render_probe_type(&mut source, ty);
    }

    for callback in &target.callbacks {
        render_probe_callback(&mut source, callback);
    }

    render_abi_type_contracts(&mut source, target);

    for function in &target.functions {
        render_probe_function(&mut source, target, function);
    }

    for static_ in &target.statics {
        render_probe_static(&mut source, target, static_);
    }

    source.push('\n');

    writeln!(source, "int main(void)").expect("writing to a string must succeed");
    writeln!(source, "{{").expect("writing to a string must succeed");

    let mut failure = 1;

    for ty in &target.types {
        if let TypeDescription::Bitfields(bitfields) = ty {
            render_bitfield_probe_body(&mut source, bitfields, &mut failure);
        }
    }

    for function in &target.functions {
        writeln!(
            source,
            "    (void)&{};",
            probe_function_name(target, function)
        )
        .expect("writing to a string must succeed");

        render_symbol_lookup(
            &mut source,
            target,
            &function.link,
            function.symbol.as_ref(),
            &mut failure,
        );
    }

    for static_ in &target.statics {
        writeln!(source, "    (void)&{};", probe_static_name(target, static_))
            .expect("writing to a string must succeed");

        render_symbol_lookup(
            &mut source,
            target,
            &static_.link,
            Some(&static_.symbol),
            &mut failure,
        );
    }

    for symbol in &target.dynamic_symbols {
        render_dynamic_probe_body(&mut source, target, symbol, &mut failure);
    }

    writeln!(source, "    return 0;").expect("writing to a string must succeed");
    writeln!(source, "}}").expect("writing to a string must succeed");

    source
}

fn render_sdk_revision_contract(source: &mut String, revision: &SdkRevision) {
    match revision {
        SdkRevision::Linux { kernel, glibc, .. } => {
            let (kernel_major, kernel_minor) = revision_pair(kernel);

            let (glibc_major, glibc_minor) = revision_pair(glibc);

            writeln!(
                source,
                "_Static_assert(LINUX_VERSION_CODE >= KERNEL_VERSION({kernel_major}, {kernel_minor}, 0) && LINUX_VERSION_CODE < KERNEL_VERSION({kernel_major}, {}, 0), \"Linux SDK revision\");",
                kernel_minor + 1
            )
            .expect("writing to a string must succeed");

            writeln!(
                source,
                "_Static_assert(__GLIBC__ == {glibc_major} && __GLIBC_MINOR__ == {glibc_minor}, \"glibc SDK revision\");"
            )
            .expect("writing to a string must succeed");
        }
        SdkRevision::MacOs { version } => {
            let (major, minor) = revision_pair(version);

            let encoded = major * 10_000 + minor * 100;

            writeln!(
                source,
                "_Static_assert(__MAC_OS_X_VERSION_MAX_ALLOWED == {encoded}, \"macOS SDK revision\");"
            )
            .expect("writing to a string must succeed");
        }
        SdkRevision::Windows { .. } => {}
    }
}

fn revision_pair(revision: &str) -> (u32, u32) {
    // Model validation requires exactly two numeric revision components.
    let mut parts = revision.split('.');

    let major = parts
        .next()
        .and_then(|part| part.parse().ok())
        .expect("validated SDK revisions have a numeric major component");

    let minor = parts
        .next()
        .and_then(|part| part.parse().ok())
        .expect("validated SDK revisions have a numeric minor component");

    (major, minor)
}

fn render_probe_type(source: &mut String, ty: &TypeDescription) {
    match ty {
        TypeDescription::Structure(aggregate) | TypeDescription::Union(aggregate) => {
            render_probe_layout(source, &aggregate.native, aggregate.size, aggregate.align);

            for field in &aggregate.fields {
                render_probe_field(source, &aggregate.native, field);
            }
        }
        TypeDescription::Incomplete(incomplete) => {
            writeln!(
                source,
                "_Static_assert(sizeof({} *) == sizeof(void *), \"{} pointer representation\");",
                incomplete.native, incomplete.native
            )
            .expect("writing to a string must succeed");
        }
        TypeDescription::Opaque(opaque) => {
            render_probe_layout(source, &opaque.native, opaque.size, opaque.align);
        }
        TypeDescription::Flexible(flexible) => {
            writeln!(
                source,
                "_Static_assert(_Alignof({}) == {}, \"{} alignment\");",
                flexible.native, flexible.align, flexible.native
            )
            .expect("writing to a string must succeed");

            for field in &flexible.fields {
                render_probe_field(source, &flexible.native, field);
            }

            writeln!(
                source,
                "_Static_assert(offsetof({}, {}) == {}, \"{}.{} offset\");",
                flexible.native,
                flexible.tail.native,
                flexible.tail.offset,
                flexible.native,
                flexible.tail.native
            )
            .expect("writing to a string must succeed");

            writeln!(
                source,
                "_Static_assert(sizeof((({} *)0)->{}[0]) == sizeof({}), \"{}.{} element\");",
                flexible.native,
                flexible.tail.native,
                flexible.tail.native_type,
                flexible.native,
                flexible.tail.native
            )
            .expect("writing to a string must succeed");
        }
        TypeDescription::Bitfields(bitfields) => {
            render_probe_layout(source, &bitfields.native, bitfields.size, bitfields.align);

            for field in &bitfields.fields {
                render_probe_field(source, &bitfields.native, field);
            }
        }
    }
}

fn render_probe_layout(source: &mut String, native: &str, size: u64, align: u64) {
    writeln!(
        source,
        "_Static_assert(sizeof({native}) == {size}, \"{native} size\");"
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(_Alignof({native}) == {align}, \"{native} alignment\");"
    )
    .expect("writing to a string must succeed");
}

fn render_probe_field(source: &mut String, native: &str, field: &FieldDescription) {
    writeln!(
        source,
        "_Static_assert(offsetof({}, {}) == {}, \"{}.{} offset\");",
        native, field.native, field.offset, native, field.native
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(sizeof((({} *)0)->{}) == sizeof({}), \"{}.{} type\");",
        native, field.native, field.native_type, native, field.native
    )
    .expect("writing to a string must succeed");
}

fn render_probe_callback(source: &mut String, callback: &CallbackDescription) {
    let parameters = native_parameters(&callback.parameters);

    writeln!(
        source,
        "typedef {} (*bray_probe_{})({});",
        callback.native_result, callback.name, parameters
    )
    .expect("writing to a string must succeed");

    writeln!(
        source,
        "_Static_assert(__builtin_types_compatible_p({}, bray_probe_{}), \"{} callback\");",
        callback.native, callback.name, callback.native
    )
    .expect("writing to a string must succeed");
}

fn render_probe_function(
    source: &mut String,
    target: &TargetDescription,
    function: &FunctionDescription,
) {
    if function.variadic {
        writeln!(
            source,
            "static __typeof__(&{}) bray_probe_{} = &{};",
            function.native, function.name, function.native
        )
        .expect("writing to a string must succeed");
    } else {
        let parameters = native_parameters(&function.parameters);

        writeln!(
            source,
            "typedef {} (*bray_probe_{}_type)({});",
            function.native_result, function.name, parameters
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "_Static_assert(__builtin_types_compatible_p(__typeof__(&{}), bray_probe_{}_type), \"{} signature\");",
            function.native, function.name, function.native
        )
        .expect("writing to a string must succeed");
    }

    render_function_symbol(source, target, function);
}

fn render_probe_static(
    source: &mut String,
    target: &TargetDescription,
    static_: &StaticDescription,
) {
    let probe_name = probe_static_name(target, static_);

    render_static_symbol(source, target, static_, &probe_name);

    writeln!(
        source,
        "_Static_assert(__builtin_types_compatible_p(__typeof__({}), {}), \"{} storage type\");",
        probe_name, static_.native_type, static_.native
    )
    .expect("writing to a string must succeed");
}

fn probe_static_name(target: &TargetDescription, static_: &StaticDescription) -> String {
    if target.system != "windows" && !plain_native_symbol(&static_.native, &static_.symbol) {
        return format!("bray_probe_{}_symbol", static_.name);
    }

    static_.native.clone()
}

fn probe_function_name(target: &TargetDescription, function: &FunctionDescription) -> String {
    let Some(symbol) = &function.symbol else {
        return function.native.clone();
    };

    if target.system != "windows" && !plain_native_symbol(&function.native, symbol) {
        return format!("bray_probe_{}_symbol", function.name);
    }

    function.native.clone()
}

fn plain_native_symbol(native: &str, symbol: &SymbolDescription) -> bool {
    symbol.name.as_deref() == Some(native)
        && symbol.version.is_none()
        && matches!(symbol.binding, SymbolBinding::Strong)
        && matches!(symbol.presence, SymbolPresence::Required)
}

fn render_function_symbol(
    source: &mut String,
    target: &TargetDescription,
    function: &FunctionDescription,
) {
    let Some(symbol) = &function.symbol else {
        return;
    };

    if target.system == "windows" || plain_native_symbol(&function.native, symbol) {
        return;
    }

    render_symbol_alias(
        source,
        &format!("bray_probe_{}_symbol", function.name),
        &format!("__typeof__({})", function.native),
        false,
        symbol,
    );
}

fn render_static_symbol(
    source: &mut String,
    target: &TargetDescription,
    static_: &StaticDescription,
    probe_name: &str,
) {
    if target.system == "windows" || plain_native_symbol(&static_.native, &static_.symbol) {
        return;
    }

    render_symbol_alias(
        source,
        probe_name,
        &static_.native_type,
        static_.thread_local,
        &static_.symbol,
    );
}

fn render_symbol_alias(
    source: &mut String,
    alias: &str,
    native_type: &str,
    thread_local: bool,
    symbol: &SymbolDescription,
) {
    let storage = if thread_local { "_Thread_local " } else { "" };

    let weak = if matches!(symbol.binding, SymbolBinding::Weak)
        || matches!(symbol.presence, SymbolPresence::Optional)
    {
        " __attribute__((weak))"
    } else {
        ""
    };

    if let Some(version) = &symbol.version {
        // Model validation permits versions only for named symbols.
        let name = symbol
            .name
            .as_deref()
            .expect("validated versioned symbols have names");

        writeln!(source, "extern {storage}{native_type} {alias}{weak};")
            .expect("writing to a string must succeed");

        writeln!(source, "__asm__(\".symver {alias},{name}@{version}\");")
            .expect("writing to a string must succeed");

        return;
    }

    if let Some(name) = &symbol.name {
        writeln!(
            source,
            "extern {storage}{native_type} {alias} __asm__(\"{name}\"){weak};"
        )
        .expect("writing to a string must succeed");
    }
}

fn render_dynamic_probe_body(
    source: &mut String,
    target: &TargetDescription,
    symbol: &DynamicSymbolDescription,
    failure: &mut u32,
) {
    let library = c_string(&symbol.library);
    let native_symbol = c_string(&symbol.symbol);

    if target.system == "windows" {
        writeln!(
            source,
            "    HMODULE bray_probe_{}_library = LoadLibraryA(\"{}\");",
            symbol.name, library
        )
        .expect("writing to a string must succeed");

        render_failure_check(
            source,
            &format!("bray_probe_{}_library == NULL", symbol.name),
            failure,
        );

        render_failure_check(
            source,
            &format!(
                "GetProcAddress(bray_probe_{}_library, \"{}\") == NULL",
                symbol.name, native_symbol
            ),
            failure,
        );

        render_failure_check(
            source,
            &format!("!FreeLibrary(bray_probe_{}_library)", symbol.name),
            failure,
        );
    } else {
        writeln!(
            source,
            "    void *bray_probe_{}_library = dlopen(\"{}\", RTLD_NOW | RTLD_LOCAL);",
            symbol.name, library
        )
        .expect("writing to a string must succeed");

        render_failure_check(
            source,
            &format!("bray_probe_{}_library == NULL", symbol.name),
            failure,
        );

        render_failure_check(
            source,
            &format!(
                "dlsym(bray_probe_{}_library, \"{}\") == NULL",
                symbol.name, native_symbol
            ),
            failure,
        );

        render_failure_check(
            source,
            &format!("dlclose(bray_probe_{}_library) != 0", symbol.name),
            failure,
        );
    }
}

fn render_symbol_lookup(
    source: &mut String,
    target: &TargetDescription,
    link_name: &str,
    symbol: Option<&SymbolDescription>,
    failure: &mut u32,
) {
    let Some(symbol) = symbol else {
        return;
    };

    if target.system != "windows" {
        return;
    }

    let library = format!("{}.dll", c_string(link_name));
    let identifier = *failure;

    writeln!(
        source,
        "    HMODULE bray_probe_symbol_library_{identifier} = LoadLibraryA(\"{library}\");"
    )
    .expect("writing to a string must succeed");

    render_failure_check(
        source,
        &format!("bray_probe_symbol_library_{identifier} == NULL"),
        failure,
    );

    let identity = match (&symbol.name, symbol.ordinal) {
        (Some(name), None) => format!("\"{}\"", c_string(name)),
        (None, Some(ordinal)) => format!("(const char *)(uintptr_t){ordinal}"),
        _ => unreachable!("validated symbols select one identity"),
    };

    writeln!(
        source,
        "    FARPROC bray_probe_symbol_{identifier} = GetProcAddress(bray_probe_symbol_library_{identifier}, {identity});"
    )
    .expect("writing to a string must succeed");

    if matches!(symbol.presence, SymbolPresence::Required) {
        render_failure_check(
            source,
            &format!("bray_probe_symbol_{identifier} == NULL"),
            failure,
        );
    }

    render_failure_check(
        source,
        &format!("!FreeLibrary(bray_probe_symbol_library_{identifier})"),
        failure,
    );
}

fn c_string(value: &str) -> String {
    let mut escaped = String::new();

    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            character => escaped.push(character),
        }
    }

    escaped
}

fn native_parameters(parameters: &[ParameterDescription]) -> String {
    if parameters.is_empty() {
        return "void".to_owned();
    }

    parameters
        .iter()
        .map(|parameter| parameter.native_type.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_failure_check(source: &mut String, condition: &str, failure: &mut u32) {
    writeln!(source, "    if ({condition})").expect("writing to a string must succeed");
    writeln!(source, "        return {failure};").expect("writing to a string must succeed");

    *failure += 1;
}

fn render_bitfield_probe_body(
    source: &mut String,
    bitfields: &BitfieldDescription,
    failure: &mut u32,
) {
    writeln!(
        source,
        "    {} bray_probe_{} = {{0}};",
        bitfields.native, bitfields.name
    )
    .expect("writing to a string must succeed");

    for field in &bitfields.bitfields {
        let maximum = bit_mask(field.width);
        let mask = maximum << field.shift;

        writeln!(
            source,
            "    bray_probe_{}.{} = {};",
            bitfields.name, field.native, maximum
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "    {} bray_probe_{}_backing = 0;",
            bitfields.native_backing_type, field.name
        )
        .expect("writing to a string must succeed");

        writeln!(
            source,
            "    memcpy(&bray_probe_{}_backing, (unsigned char *)&bray_probe_{} + {}, sizeof(bray_probe_{}_backing));",
            field.name, bitfields.name, bitfields.backing_offset, field.name
        )
        .expect("writing to a string must succeed");

        render_failure_check(
            source,
            &format!(
                "(bray_probe_{}_backing & {}) >> {} != {}",
                field.name, mask, field.shift, maximum
            ),
            failure,
        );
    }
}

#[cfg(test)]
mod tests {
    use super::{native_parameters, render_failure_check};

    #[test]
    fn empty_native_parameters_use_the_c_void_form() {
        assert_eq!(native_parameters(&[]), "void");
    }

    #[test]
    fn failure_checks_follow_the_native_fixture_style() {
        let mut source = String::new();
        let mut failure = 4;

        render_failure_check(&mut source, "value == NULL", &mut failure);

        assert_eq!(source, "    if (value == NULL)\n        return 4;\n");
        assert_eq!(failure, 5);
    }
}
