//! Stable native ABI primitives shared by generated code and linked runtime components.

#![forbid(unsafe_code)]

#[cfg(test)]
#[macro_use]
mod layout;
mod platform;
mod process;
mod product;
mod runtime;
mod temporal;

pub use platform::{
    NativePlatformEnvironmentEntry, NativePlatformEnvironmentList, NativePlatformFileMetadata,
    NativePlatformFileOptions, NativePlatformPath, NativePlatformSpanList, NativePlatformStatus,
    NativePlatformText,
};
pub use process::{NativePlatformChildRequest, NativePlatformExitStatus};
pub use product::{
    NativeProductHostDescriptor, NativeProductHostObservation, NativeProductHostOperation,
    NativeProductHostState, NativeProductHostStatus, NativeProductIdentity,
    NativeStaticAccessCallback, NativeStaticCleanupCallback, NativeStaticDuration,
    NativeStaticHostEntry, NativeStaticIdentity, NativeThreadStaticCleanupRegistration,
    PRODUCT_HOST_ABI_VERSION, PRODUCT_HOST_CONTROL_RUNTIME_SYMBOL,
};
pub use runtime::{
    AWAITED_FRAME_COMPOSITION_SYMBOL, CHARACTER_FROM_SCALAR_VALUE_SYMBOL,
    CHARACTER_IS_ALPHABETIC_SYMBOL, CHARACTER_IS_NUMERIC_SYMBOL, CHARACTER_IS_WHITESPACE_SYMBOL,
    CHARACTER_SCALAR_VALUE_SYMBOL, CHARACTER_UNICODE_DATA_VERSION, CHARACTER_UTF8_BYTE_SYMBOL,
    CHARACTER_UTF8_LENGTH_SYMBOL, CLEANUP_INCIDENT_REPORTING_SYMBOL,
    COMPATIBLE_LANE_SELECTION_SYMBOL, CURRENT_RUN_CANCELLATION_OBSERVATION_SYMBOL,
    CURRENT_RUN_CANCELLATION_PROPAGATION_SYMBOL, ENTRY_FAILURE_REPORTING_SYMBOL,
    FOREIGN_CALLBACK_EXECUTION_SYMBOL, FRAME_COMPLETION_MOVE_SYMBOL, JOIN_REGISTRATION_SYMBOL,
    MAIN_THREAD_LANE_DRIVE_SYMBOL, MAIN_THREAD_LANE_STARTUP_SYMBOL,
    MAX_PERFORMANCE_OBSERVATION_RECORDS, MEMORY_ALLOCATION_OBSERVATION_SYMBOL,
    MEMORY_ALLOCATION_SYMBOL, MEMORY_COPY_OBSERVATION_SYMBOL, MEMORY_DEALLOCATION_SYMBOL,
    MEMORY_OBSERVATION_BEGIN_SYMBOL, NativeExecutionLane, NativeExecutionLaneResult,
    NativeFrameActionCallback, NativeFrameAffinity, NativeFrameCancellationCallback,
    NativeFrameCompletionMoveCallback, NativeFrameExit, NativeFrameMoveBeforeStartCallback,
    NativeFrameProgress, NativeFrameProgressKind, NativeFrameResolveCallback,
    NativeFrameResumeCallback, NativeFrameState, NativeFrameStateCallback, NativeInactiveFrame,
    NativeLaneRequirements, NativePanicCause, NativeProtectedFrame, NativeProtectedFrameTransfer,
    NativeRootHandle, NativeRootStart, NativeRunOutcome, NativeRunState,
    NativeRuntimeConfiguration, NativeRuntimeEventCallback, NativeRuntimeStatus,
    NativeSourceAnchor, NativeStringView, NativeSynchronousRootCallback, NativeTaskAllocation,
    NativeTaskHandle, NativeWakeCallback, PANIC_PROPAGATION_SYMBOL,
    PANIC_REPORT_CONSTRUCTION_SYMBOL, PANIC_REPORTING_SYMBOL, PERFORMANCE_INTERVAL_BEGIN_SYMBOL,
    PERFORMANCE_INTERVAL_END_SYMBOL, PERFORMANCE_OBSERVATION_HEADER,
    PERFORMANCE_OBSERVATION_PATH_ENVIRONMENT, PLATFORM_CHILD_DISPOSE_SYMBOL,
    PLATFORM_CHILD_REAP_SYMBOL, PLATFORM_CHILD_SPAWN_SYMBOL, PLATFORM_CHILD_TERMINATE_SYMBOL,
    PLATFORM_CHILD_WAIT_SYMBOL, PLATFORM_CLOCK_MONOTONIC_NOW_SYMBOL, PLATFORM_CLOCK_SLEEP_SYMBOL,
    PLATFORM_CLOCK_WALL_NOW_SYMBOL, PLATFORM_CONTEXT_ARGUMENT_COUNT_SYMBOL,
    PLATFORM_CONTEXT_ARGUMENT_SYMBOL, PLATFORM_CONTEXT_ENVIRONMENT_COUNT_SYMBOL,
    PLATFORM_CONTEXT_ENVIRONMENT_ENTRY_SYMBOL, PLATFORM_CONTEXT_ENVIRONMENT_KEY_EQUALS_SYMBOL,
    PLATFORM_CONTEXT_IDENTITY_SYMBOL, PLATFORM_CONTEXT_NATIVE_TEXT_WIDTH_SYMBOL,
    PLATFORM_CONTEXT_WORKING_DIRECTORY_SYMBOL, PLATFORM_DIRECTORY_CLOSE_SYMBOL,
    PLATFORM_DIRECTORY_NEXT_SYMBOL, PLATFORM_DIRECTORY_OPEN_SYMBOL,
    PLATFORM_DYNAMIC_LIBRARY_CLOSE_SYMBOL, PLATFORM_DYNAMIC_LIBRARY_OPEN_PATH_SYMBOL,
    PLATFORM_DYNAMIC_LIBRARY_OPEN_SYSTEM_SYMBOL, PLATFORM_DYNAMIC_LIBRARY_SYMBOL_SYMBOL,
    PLATFORM_ENTROPY_FILL_SYMBOL, PLATFORM_FILE_CLOSE_SYMBOL, PLATFORM_FILE_FLUSH_SYMBOL,
    PLATFORM_FILE_METADATA_SYMBOL, PLATFORM_FILE_OPEN_SYMBOL, PLATFORM_FILE_READ_SYMBOL,
    PLATFORM_FILE_SEEK_SYMBOL, PLATFORM_FILE_WRITE_SYMBOL, PLATFORM_PATH_CREATE_DIRECTORY_SYMBOL,
    PLATFORM_PATH_METADATA_SYMBOL, PLATFORM_PATH_REMOVE_DIRECTORY_SYMBOL,
    PLATFORM_PATH_REMOVE_FILE_SYMBOL, PLATFORM_PATH_RENAME_SYMBOL,
    PLATFORM_PROCESS_PIPE_CLOSE_SYMBOL, PLATFORM_PROCESS_PIPE_FLUSH_SYMBOL,
    PLATFORM_PROCESS_PIPE_READ_SYMBOL, PLATFORM_PROCESS_PIPE_WRITE_SYMBOL,
    PLATFORM_STANDARD_ERROR_FLUSH_SYMBOL, PLATFORM_STANDARD_ERROR_LOCK_SYMBOL,
    PLATFORM_STANDARD_ERROR_UNLOCK_SYMBOL, PLATFORM_STANDARD_ERROR_WRITE_SYMBOL,
    PLATFORM_STANDARD_INPUT_READ_SYMBOL, PLATFORM_STANDARD_OUTPUT_FLUSH_SYMBOL,
    PLATFORM_STANDARD_OUTPUT_LOCK_SYMBOL, PLATFORM_STANDARD_OUTPUT_UNLOCK_SYMBOL,
    PLATFORM_STANDARD_OUTPUT_WRITE_SYMBOL, PLATFORM_TIME_DATE_ADD_SYMBOL,
    PLATFORM_TIME_DATE_VALIDATE_SYMBOL, PLATFORM_TIME_FORMAT_SYMBOL, PLATFORM_TIME_OBSERVE_SYMBOL,
    PLATFORM_TIME_PARSE_SYMBOL, PLATFORM_TIME_RESOLVE_SYMBOL, PLATFORM_TIME_ZONE_CLOSE_SYMBOL,
    PLATFORM_TIME_ZONE_LOAD_SYMBOL, PLATFORM_TIME_ZONE_LOCAL_SYMBOL,
    PLATFORM_TIME_ZONE_NAME_SYMBOL, PLATFORM_TIME_ZONE_RETAIN_SYMBOL,
    ROOT_CANCELLATION_REQUEST_SYMBOL, ROOT_COMPLETION_RESOLUTION_SYMBOL, ROOT_EXECUTION_SYMBOL,
    ROOT_TERMINAL_OBSERVATION_SYMBOL, RUNTIME_EVENT_SYMBOL, STRING_EQUALS_SYMBOL,
    STRING_FROM_UTF8_SYMBOL, STRING_SCALAR_AT_SYMBOL, STRING_SCALAR_COUNT_SYMBOL,
    STRING_SCALAR_SLICE_SYMBOL, STRUCTURED_SHUTDOWN_SYMBOL, SUSPENSION_REGISTRATION_SYMBOL,
    SYNCHRONOUS_ROOT_EXECUTION_SYMBOL, TASK_ALLOCATION_SYMBOL, TASK_CANCELLATION_REQUEST_SYMBOL,
    TASK_START_SYMBOL, TERMINAL_PUBLICATION_SYMBOL, TEST_ENTRY_SELECTION_SYMBOL,
    THREAD_ATTACHMENT_IDENTITY_SYMBOL, THREAD_STATIC_CLEANUP_REGISTRATION_SYMBOL, WAKE_SYMBOL,
};
pub use temporal::{
    NativePlatformDateTime, NativePlatformTemporalObservation, NativePlatformTemporalResolution,
    NativePlatformTemporalValue,
};
