//! Syntax data structures produced by the Bray parser.

#![forbid(unsafe_code)]

mod builder;
mod green;
mod kind;
mod list;
mod node;
mod syntax;
#[cfg(test)]
mod test_support;
mod text;
mod token;
mod tree;
mod trivia;

pub use kind::SyntaxKind;
pub use node::{SourceSyntaxNode, SyntaxNode};
pub use syntax::{
    AbiDirectiveSyntax, AbiDirectiveSyntaxBuilder, AbsenceExpressionSyntax,
    AbsenceExpressionSyntaxBuilder, AccessExpressionSyntax, AccessExpressionSyntaxBuilder,
    ArgumentListSyntax, ArgumentListSyntaxBuilder, ArgumentSyntax, ArgumentSyntaxBuilder,
    ArrayExpressionSyntax, ArrayExpressionSyntaxBuilder, AssertionExpressionSyntax,
    AssertionExpressionSyntaxBuilder, AsyncBlockExpressionSyntax,
    AsyncBlockExpressionSyntaxBuilder, AsyncCapableLifecycleMemberModifiersSyntax,
    AsyncCapableLifecycleMemberModifiersSyntaxBuilder, AwaitExpressionSyntax,
    AwaitExpressionSyntaxBuilder, BlockExpressionSyntax, BlockExpressionSyntaxBuilder,
    BlockItemSyntax, BlockItemSyntaxBuilder, BlockModuleDeclarationSyntax,
    BlockModuleDeclarationSyntaxBuilder, BooleanFoldExpressionSyntax,
    BooleanFoldExpressionSyntaxBuilder, BorrowExpressionSyntax, BorrowExpressionSyntaxBuilder,
    BreakExpressionSyntax, BreakExpressionSyntaxBuilder, CallOperationSyntax,
    CallOperationSyntaxBuilder, CallableBodyBlockExpressionSyntax,
    CallableBodyBlockExpressionSyntaxBuilder, CallableContractDeclarationSyntax,
    CallableContractDeclarationSyntaxBuilder, CallableContractModifiersSyntax,
    CallableContractModifiersSyntaxBuilder, CallableDirectivesSyntax,
    CallableDirectivesSyntaxBuilder, CallableModifiersSyntax, CallableModifiersSyntaxBuilder,
    CallableOverloadDeclarationSyntax, CallableOverloadDeclarationSyntaxBuilder,
    CallableResultClauseSyntax, CallableResultClauseSyntaxBuilder, CasePatternEntrySyntax,
    CasePatternEntrySyntaxBuilder, CasePatternSyntax, CasePatternSyntaxBuilder,
    CatchExpressionSyntax, CatchExpressionSyntaxBuilder, CompilationUnitSyntax,
    CompilationUnitSyntaxBuilder, ConditionalElseSyntax, ConditionalElseSyntaxBuilder,
    ConditionalExpressionSyntax, ConditionalExpressionSyntaxBuilder, ConstantDeclarationSyntax,
    ConstantDeclarationSyntaxBuilder, ConstantModifiersSyntax, ConstantModifiersSyntaxBuilder,
    ConstructorMemberModifiersSyntax, ConstructorMemberModifiersSyntaxBuilder,
    ContinueExpressionSyntax, ContinueExpressionSyntaxBuilder, ConversionOperationSyntax,
    ConversionOperationSyntaxBuilder, CopyDirectiveSyntax, CopyDirectiveSyntaxBuilder,
    DestructorMemberDeclarationSyntax, DestructorMemberDeclarationSyntaxBuilder,
    DirectiveArgumentListSyntax, DirectiveArgumentListSyntaxBuilder, DirectiveArgumentSyntax,
    DirectiveArgumentSyntaxBuilder, ElementIndexOperationSyntax,
    ElementIndexOperationSyntaxBuilder, EnsuresClauseSyntax, EnsuresClauseSyntaxBuilder,
    EntrypointDirectiveSyntax, EntrypointDirectiveSyntaxBuilder, ExportDeclarationSyntax,
    ExportDeclarationSyntaxBuilder, ExpressionSyntax, ExpressionSyntaxBuilder,
    FieldModifiersSyntax, FieldModifiersSyntaxBuilder, FinalizerMemberDeclarationSyntax,
    FinalizerMemberDeclarationSyntaxBuilder, ForExpressionSyntax, ForExpressionSyntaxBuilder,
    FunctionDeclarationSyntax, FunctionDeclarationSyntaxBuilder, FunctionDirectivesSyntax,
    FunctionDirectivesSyntaxBuilder, FunctionModifiersSyntax, FunctionModifiersSyntaxBuilder,
    GeneralGeneratorExpressionSyntax, GeneralGeneratorExpressionSyntaxBuilder,
    GeneratorIterationExpressionSyntax, GeneratorIterationExpressionSyntaxBuilder,
    GenericArgumentListSyntax, GenericArgumentListSyntaxBuilder, GenericArgumentSyntax,
    GenericArgumentSyntaxBuilder, GenericConstParameterSyntax, GenericConstParameterSyntaxBuilder,
    GenericParameterListSyntax, GenericParameterListSyntaxBuilder, GenericTypeParameterSyntax,
    GenericTypeParameterSyntaxBuilder, GroupedExpressionSyntax, GroupedExpressionSyntaxBuilder,
    IdentifierListItemSyntax, IdentifierListItemSyntaxBuilder, IdentifierListSyntax,
    IdentifierListSyntaxBuilder, ImplementationBodySyntax, ImplementationBodySyntaxBuilder,
    ImplementationOverloadDeclarationSyntax, ImplementationOverloadDeclarationSyntaxBuilder,
    ImplementationOverloadSubjectSyntax, ImplementationOverloadSubjectSyntaxBuilder,
    ImplementationSubjectSyntax, ImplementationSubjectSyntaxBuilder,
    ImplementationTypeMemberBindingSyntax, ImplementationTypeMemberBindingSyntaxBuilder,
    InherentImplementationDeclarationSyntax, InherentImplementationDeclarationSyntaxBuilder,
    IrrefutablePatternEntrySyntax, IrrefutablePatternEntrySyntaxBuilder, IrrefutablePatternSyntax,
    IrrefutablePatternSyntaxBuilder, IterationSourceSyntax, IterationSourceSyntaxBuilder,
    LambdaExpressionSyntax, LambdaExpressionSyntaxBuilder, LayoutDirectiveSyntax,
    LayoutDirectiveSyntaxBuilder, LeadingDotVariantExpressionSyntax,
    LeadingDotVariantExpressionSyntaxBuilder, LinkDirectiveSyntax, LinkDirectiveSyntaxBuilder,
    LiteralExpressionSyntax, LiteralExpressionSyntaxBuilder, LocalBindingDeclarationSyntax,
    LocalBindingDeclarationSyntaxBuilder, LoopExpressionSyntax, LoopExpressionSyntaxBuilder,
    MatchArmSyntax, MatchArmSyntaxBuilder, MatchBodySyntax, MatchBodySyntaxBuilder,
    MatchExpressionSyntax, MatchExpressionSyntaxBuilder, MatchSubjectSyntax,
    MatchSubjectSyntaxBuilder, MemberAccessOperationSyntax, MemberAccessOperationSyntaxBuilder,
    ModuleBodySyntax, ModuleBodySyntaxBuilder, ModuleDirectivesSyntax,
    ModuleDirectivesSyntaxBuilder, ModuleModifiersSyntax, ModuleModifiersSyntaxBuilder,
    NamedTraitImplementationDeclarationSyntax, NamedTraitImplementationDeclarationSyntaxBuilder,
    NullablePropagationOperationSyntax, NullablePropagationOperationSyntaxBuilder,
    OverloadArmListSyntax, OverloadArmListSyntaxBuilder, OverloadArmSyntax,
    OverloadArmSyntaxBuilder, OverloadModifiersSyntax, OverloadModifiersSyntaxBuilder,
    PanicExpressionSyntax, PanicExpressionSyntaxBuilder, ParameterListSyntax,
    ParameterListSyntaxBuilder, ParameterModifiersSyntax, ParameterModifiersSyntaxBuilder,
    ParameterSyntax, ParameterSyntaxBuilder, PathSyntax, PathSyntaxBuilder,
    PayloadFieldModifiersSyntax, PayloadFieldModifiersSyntaxBuilder, PredicateDeclarationSyntax,
    PredicateDeclarationSyntaxBuilder, PredicateModifiersSyntax, PredicateModifiersSyntaxBuilder,
    PredicateParameterListSyntax, PredicateParameterListSyntaxBuilder, PredicateParameterSyntax,
    PredicateParameterSyntaxBuilder, PrimaryExpressionSyntax, PrimaryExpressionSyntaxBuilder,
    RequiresClauseSyntax, RequiresClauseSyntaxBuilder, ResultPropagationExpressionSyntax,
    ResultPropagationExpressionSyntaxBuilder, ReturnExpressionSyntax,
    ReturnExpressionSyntaxBuilder, ScopeEnterMemberDeclarationSyntax,
    ScopeEnterMemberDeclarationSyntaxBuilder, ScopeExitMemberDeclarationSyntax,
    ScopeExitMemberDeclarationSyntaxBuilder, SequencedExpressionSyntax,
    SequencedExpressionSyntaxBuilder, SkippedSyntax, SliceIndexOperationSyntax,
    SliceIndexOperationSyntaxBuilder, SourceUnitModuleDeclarationSyntax,
    SourceUnitModuleDeclarationSyntaxBuilder, SourceUnitSyntax, SourceUnitSyntaxBuilder,
    SpawnExpressionSyntax, SpawnExpressionSyntaxBuilder, StructBodySyntax, StructBodySyntaxBuilder,
    StructConstructionBodySyntax, StructConstructionBodySyntaxBuilder, StructDeclarationSyntax,
    StructDeclarationSyntaxBuilder, StructFieldDeclarationSyntax,
    StructFieldDeclarationSyntaxBuilder, StructFieldInitializerSyntax,
    StructFieldInitializerSyntaxBuilder, SymbolDirectiveSyntax, SymbolDirectiveSyntaxBuilder,
    SyncLifecycleMemberModifiersSyntax, SyncLifecycleMemberModifiersSyntaxBuilder,
    TagDirectiveSyntax, TagDirectiveSyntaxBuilder, TargetDirectiveSyntax,
    TargetDirectiveSyntaxBuilder, TestDirectiveSyntax, TestDirectiveSyntaxBuilder,
    TraitApplicationSyntax, TraitApplicationSyntaxBuilder, TraitBodySyntax, TraitBodySyntaxBuilder,
    TraitCallableMemberDeclarationSyntax, TraitCallableMemberDeclarationSyntaxBuilder,
    TraitCallableMemberModifiersSyntax, TraitCallableMemberModifiersSyntaxBuilder,
    TraitConstantMemberDeclarationSyntax, TraitConstantMemberDeclarationSyntaxBuilder,
    TraitDeclarationSyntax, TraitDeclarationSyntaxBuilder,
    TraitDestructorRequirementDeclarationSyntax,
    TraitDestructorRequirementDeclarationSyntaxBuilder, TraitFinalizerRequirementDeclarationSyntax,
    TraitFinalizerRequirementDeclarationSyntaxBuilder, TraitModifiersSyntax,
    TraitModifiersSyntaxBuilder, TraitPredicateMemberDeclarationSyntax,
    TraitPredicateMemberDeclarationSyntaxBuilder, TraitPredicateMemberModifiersSyntax,
    TraitPredicateMemberModifiersSyntaxBuilder, TraitQualifiedMemberOperationSyntax,
    TraitQualifiedMemberOperationSyntaxBuilder, TraitScopeEnterRequirementDeclarationSyntax,
    TraitScopeEnterRequirementDeclarationSyntaxBuilder, TraitScopeExitRequirementDeclarationSyntax,
    TraitScopeExitRequirementDeclarationSyntaxBuilder, TraitTypeMemberDeclarationSyntax,
    TraitTypeMemberDeclarationSyntaxBuilder, TrustBoundaryExpressionSyntax,
    TrustBoundaryExpressionSyntaxBuilder, TupleExpressionSyntax, TupleExpressionSyntaxBuilder,
    TypeAnnotationSyntax, TypeAnnotationSyntaxBuilder, TypeCallableMemberDeclarationSyntax,
    TypeCallableMemberDeclarationSyntaxBuilder, TypeCallableMemberModifiersSyntax,
    TypeCallableMemberModifiersSyntaxBuilder, TypeConstructorMemberDeclarationSyntax,
    TypeConstructorMemberDeclarationSyntaxBuilder, TypeDirectivesSyntax,
    TypeDirectivesSyntaxBuilder, TypeExpressionSyntax, TypeExpressionSyntaxBuilder,
    TypeFormArgumentListSyntax, TypeFormArgumentListSyntaxBuilder, TypeFormArgumentSyntax,
    TypeFormArgumentSyntaxBuilder, TypeFormConstructionExpressionSyntax,
    TypeFormConstructionExpressionSyntaxBuilder, TypeModifiersSyntax, TypeModifiersSyntaxBuilder,
    TypedIdentifierSyntax, TypedIdentifierSyntaxBuilder, UnionBodySyntax, UnionBodySyntaxBuilder,
    UnionDeclarationSyntax, UnionDeclarationSyntaxBuilder, UnionPayloadFieldSyntax,
    UnionPayloadFieldSyntaxBuilder, UnionVariantDeclarationSyntax,
    UnionVariantDeclarationSyntaxBuilder, UnionVariantPayloadSyntax,
    UnionVariantPayloadSyntaxBuilder, UnitExpressionSyntax, UnitExpressionSyntaxBuilder,
    UnnamedTraitImplementationDeclarationSyntax,
    UnnamedTraitImplementationDeclarationSyntaxBuilder, UsesClauseSyntax, UsesClauseSyntaxBuilder,
    UsingDeclarationSyntax, UsingDeclarationSyntaxBuilder, VariantDirectivesSyntax,
    VariantDirectivesSyntaxBuilder, WhileExpressionSyntax, WhileExpressionSyntaxBuilder,
    WithClauseSyntax, WithClauseSyntaxBuilder, WithExpressionSyntax, WithExpressionSyntaxBuilder,
    YieldExpressionSyntax, YieldExpressionSyntaxBuilder,
};
pub use text::SyntaxText;
pub use token::{SyntaxToken, SyntaxTokenPresence};
pub use tree::SyntaxTree;
pub use trivia::SyntaxTrivia;
