[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bray-compilation = { path = "../crates/bray-compilation" }
bray-compiler-known = { path = "../crates/bray-compiler-known", features = ["generation"] }
bray-package-interface = { path = "../crates/bray-package-interface" }
rust-style = { path = "../tools/rust-style" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
bray-package-interface = { path = "../crates/bray-package-interface", features = ["test-support"] }

[[bin]]
name = "xtask"
path = "src/main.rs"
