use std::collections::BTreeSet;
use std::num::NonZeroU32;
use std::sync::Arc;

use bray_base::{NonEmptySharedStr, is_canonical_relative_path, sorted_unique_shared_slice};
use bray_runtime_interface::{BinarySymbolName, PlatformServiceRole, RuntimeAbiVersion};
use bray_target::{CodeModel, RelocationModel, TargetIdentity};

use super::{
    StandardLibraryArtifact, StandardLibraryArtifactDigest, StandardLibraryArtifactKind,
    StandardLibraryManifestError,
};

/// Source category accepted for cross-artifact native optimization.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum StandardLibraryOptimizationProducerKind {
    /// Bray code generated by the selected compiler backend.
    Bray,
    /// Pinned C or C++ source compiled by the selected LLVM toolchain.
    PinnedNative,
}

/// Compiler and native dependency identity that produced an optimization archive.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StandardLibraryOptimizationProducer {
    kind: StandardLibraryOptimizationProducerKind,
    implementation: NonEmptySharedStr,
    implementation_revision: NonEmptySharedStr,
    toolchain: NonEmptySharedStr,
    toolchain_revision: NonEmptySharedStr,
}

impl StandardLibraryOptimizationProducer {
    /// Creates a producer identity when every compatibility component is present.
    pub fn try_new(
        kind: StandardLibraryOptimizationProducerKind,
        implementation: impl Into<Arc<str>>,
        implementation_revision: impl Into<Arc<str>>,
        toolchain: impl Into<Arc<str>>,
        toolchain_revision: impl Into<Arc<str>>,
    ) -> Result<Self, StandardLibraryManifestError> {
        let implementation = NonEmptySharedStr::try_new(implementation)
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        let implementation_revision = NonEmptySharedStr::try_new(implementation_revision)
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        let toolchain = NonEmptySharedStr::try_new(toolchain)
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        let toolchain_revision = NonEmptySharedStr::try_new(toolchain_revision)
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        Ok(Self {
            kind,
            implementation,
            implementation_revision,
            toolchain,
            toolchain_revision,
        })
    }

    /// Returns the producer source category.
    pub const fn kind(&self) -> StandardLibraryOptimizationProducerKind {
        self.kind
    }

    /// Returns the implementation that formed the native modules.
    pub fn implementation(&self) -> &str {
        self.implementation.as_str()
    }

    /// Returns the implementation revision that affects generated content.
    pub fn implementation_revision(&self) -> &str {
        self.implementation_revision.as_str()
    }

    /// Returns the native toolchain family.
    pub fn toolchain(&self) -> &str {
        self.toolchain.as_str()
    }

    /// Returns the exact native toolchain revision.
    pub fn toolchain_revision(&self) -> &str {
        self.toolchain_revision.as_str()
    }
}

/// Target and ABI contract required to consume one optimization archive.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StandardLibraryOptimizationCompatibility {
    triple: NonEmptySharedStr,
    data_layout: NonEmptySharedStr,
    relocation_model: RelocationModel,
    code_model: CodeModel,
    runtime_abi: RuntimeAbiVersion,
}

impl StandardLibraryOptimizationCompatibility {
    /// Creates a complete compatibility contract for target-native LLVM modules.
    pub fn try_new(
        triple: impl Into<Arc<str>>,
        data_layout: impl Into<Arc<str>>,
        relocation_model: RelocationModel,
        code_model: CodeModel,
        runtime_abi: RuntimeAbiVersion,
    ) -> Result<Self, StandardLibraryManifestError> {
        let triple = NonEmptySharedStr::try_new(triple)
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        let data_layout = NonEmptySharedStr::try_new(data_layout)
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        Ok(Self {
            triple,
            data_layout,
            relocation_model,
            code_model,
            runtime_abi,
        })
    }

    /// Returns the canonical LLVM target triple.
    pub fn triple(&self) -> &str {
        self.triple.as_str()
    }

    /// Returns the exact LLVM data-layout contract.
    pub fn data_layout(&self) -> &str {
        self.data_layout.as_str()
    }

    /// Returns the selected relocation model.
    pub const fn relocation_model(&self) -> RelocationModel {
        self.relocation_model
    }

    /// Returns the selected code model.
    pub const fn code_model(&self) -> CodeModel {
        self.code_model
    }

    /// Returns the runtime ABI required by the generated modules.
    pub const fn runtime_abi(&self) -> RuntimeAbiVersion {
        self.runtime_abi
    }
}

/// Object-only artifact retained as the independently selectable fallback.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StandardLibraryOptimizationFallback {
    path: Arc<str>,
    digest: StandardLibraryArtifactDigest,
}

/// Packaged dependency metadata that contributes to optimization compatibility.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StandardLibraryOptimizationDependency {
    path: Arc<str>,
    digest: StandardLibraryArtifactDigest,
}

impl StandardLibraryOptimizationDependency {
    /// Creates a reference to one packaged dependency metadata artifact.
    pub fn try_new(
        path: impl Into<Arc<str>>,
        digest: StandardLibraryArtifactDigest,
    ) -> Result<Self, StandardLibraryManifestError> {
        let path = path.into();

        if !is_canonical_relative_path(&path) {
            return Err(StandardLibraryManifestError::InvalidOptimizationMetadata);
        }

        Ok(Self { path, digest })
    }

    /// Returns the dependency metadata path beneath the bundle root.
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Returns the exact dependency metadata digest.
    pub const fn digest(&self) -> StandardLibraryArtifactDigest {
        self.digest
    }
}

impl StandardLibraryOptimizationFallback {
    /// Creates a fallback reference to one canonical bundle artifact.
    pub fn try_new(
        path: impl Into<Arc<str>>,
        digest: StandardLibraryArtifactDigest,
    ) -> Result<Self, StandardLibraryManifestError> {
        let path = path.into();

        if !is_canonical_relative_path(&path) {
            return Err(StandardLibraryManifestError::InvalidOptimizationMetadata);
        }

        Ok(Self { path, digest })
    }

    /// Returns the fallback path beneath the bundle root.
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Returns the exact fallback content digest.
    pub const fn digest(&self) -> StandardLibraryArtifactDigest {
        self.digest
    }
}

/// Optimization semantics supplied by a standard library artifact.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum StandardLibraryOptimizationSemantics {
    /// LLVM modules with summaries suitable for ThinLTO import planning.
    ThinLto,
}

/// Native lifecycle obligation retained across whole-product optimization.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum StandardLibraryOptimizationLifecycleRoot {
    /// LLVM's appending global constructor table.
    GlobalConstructors,
    /// LLVM's appending global destructor table.
    GlobalDestructors,
    /// Process-exit callback registration performed by a native module.
    ExitRegistration,
}

/// Selection and preservation contract for one optimization archive.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StandardLibraryOptimizationMetadata {
    partition: NonEmptySharedStr,
    producer: StandardLibraryOptimizationProducer,
    compatibility: StandardLibraryOptimizationCompatibility,
    fallback: StandardLibraryOptimizationFallback,
    module_count: NonZeroU32,
    preservation_roots: Arc<[BinarySymbolName]>,
    lifecycle_roots: Arc<[StandardLibraryOptimizationLifecycleRoot]>,
    platform_services: Arc<[PlatformServiceRole]>,
    dependencies: Arc<[StandardLibraryOptimizationDependency]>,
}

impl StandardLibraryOptimizationMetadata {
    /// Creates the core contract for one summary-bearing optimization partition.
    pub fn try_new(
        partition: impl Into<Arc<str>>,
        producer: StandardLibraryOptimizationProducer,
        compatibility: StandardLibraryOptimizationCompatibility,
        fallback: StandardLibraryOptimizationFallback,
        module_count: NonZeroU32,
    ) -> Result<Self, StandardLibraryManifestError> {
        let partition = NonEmptySharedStr::try_new(partition)
            .filter(|partition| is_partition_identity(partition.as_str()))
            .ok_or(StandardLibraryManifestError::InvalidOptimizationMetadata)?;

        Ok(Self {
            partition,
            producer,
            compatibility,
            fallback,
            module_count,
            preservation_roots: Arc::from([]),
            lifecycle_roots: Arc::from([]),
            platform_services: Arc::from([]),
            dependencies: Arc::from([]),
        })
    }

    /// Returns this partition with its complete native preservation-root set.
    pub fn with_preservation_roots(
        mut self,
        preservation_roots: impl IntoIterator<Item = BinarySymbolName>,
    ) -> Self {
        self.preservation_roots = sorted_unique_shared_slice(preservation_roots);

        self
    }

    /// Returns this partition with its complete native lifecycle-root set.
    pub fn with_lifecycle_roots(
        mut self,
        lifecycle_roots: impl IntoIterator<Item = StandardLibraryOptimizationLifecycleRoot>,
    ) -> Self {
        self.lifecycle_roots = sorted_unique_shared_slice(lifecycle_roots);

        self
    }

    /// Returns this native provider partition with its applicable platform services.
    pub fn with_platform_services(
        mut self,
        platform_services: impl IntoIterator<Item = PlatformServiceRole>,
    ) -> Self {
        self.platform_services = sorted_unique_shared_slice(platform_services);

        self
    }

    /// Returns this partition with dependency metadata that affects compatibility.
    pub fn with_dependencies(
        mut self,
        dependencies: impl IntoIterator<Item = StandardLibraryOptimizationDependency>,
    ) -> Self {
        self.dependencies = sorted_unique_shared_slice(dependencies);

        self
    }

    /// Returns the stable semantic and co-retention partition identity.
    pub fn partition(&self) -> &str {
        self.partition.as_str()
    }

    /// Returns the compiler and native dependency identity.
    pub const fn producer(&self) -> &StandardLibraryOptimizationProducer {
        &self.producer
    }

    /// Returns the exact target and ABI compatibility contract.
    pub const fn compatibility(&self) -> &StandardLibraryOptimizationCompatibility {
        &self.compatibility
    }

    /// Returns the object-only fallback artifact.
    pub const fn fallback(&self) -> &StandardLibraryOptimizationFallback {
        &self.fallback
    }

    /// Returns the optimization policy represented by this archive.
    pub const fn semantics(&self) -> StandardLibraryOptimizationSemantics {
        StandardLibraryOptimizationSemantics::ThinLto
    }

    /// Returns the number of independently summarized modules in the archive.
    pub const fn module_count(&self) -> NonZeroU32 {
        self.module_count
    }

    /// Returns symbols that remain roots during whole-product optimization.
    pub fn preservation_roots(&self) -> &[BinarySymbolName] {
        &self.preservation_roots
    }

    /// Returns lifecycle obligations retained during whole-product optimization.
    pub fn lifecycle_roots(&self) -> &[StandardLibraryOptimizationLifecycleRoot] {
        &self.lifecycle_roots
    }

    /// Returns platform services associated with this native provider partition.
    pub fn platform_services(&self) -> &[PlatformServiceRole] {
        &self.platform_services
    }

    /// Returns packaged dependency metadata that affects this partition.
    pub fn dependencies(&self) -> &[StandardLibraryOptimizationDependency] {
        &self.dependencies
    }
}

fn is_partition_identity(value: &str) -> bool {
    value.bytes().enumerate().all(|(index, byte)| {
        byte.is_ascii_lowercase()
            || byte.is_ascii_digit()
            || (index > 0 && matches!(byte, b'_' | b'.' | b'-'))
    })
}

pub(super) fn validate_target(
    artifacts: &[StandardLibraryArtifact],
    target: &TargetIdentity,
    runtime_abi: RuntimeAbiVersion,
) -> Result<(), StandardLibraryManifestError> {
    let mut partitions = BTreeSet::new();
    let mut fallbacks = BTreeSet::new();
    let mut platform_services = BTreeSet::new();
    let mut compatibility = None;
    let mut toolchain = None;
    let mut has_bray_partition = false;

    for artifact in artifacts
        .iter()
        .filter(|artifact| artifact.kind() == StandardLibraryArtifactKind::OptimizationArchive)
    {
        let Some(optimization) = artifact.optimization() else {
            return Err(StandardLibraryManifestError::InvalidOptimizationMetadata);
        };

        let artifact_compatibility = optimization.compatibility();

        let artifact_toolchain = (
            optimization.producer().toolchain(),
            optimization.producer().toolchain_revision(),
        );

        if !partitions.insert(optimization.partition())
            || optimization.compatibility().runtime_abi() != runtime_abi
            || optimization.compatibility().triple() != target.as_str()
            || compatibility
                .as_ref()
                .is_some_and(|expected| *expected != artifact_compatibility)
            || toolchain
                .as_ref()
                .is_some_and(|expected| *expected != artifact_toolchain)
        {
            return Err(StandardLibraryManifestError::InvalidOptimizationMetadata);
        }

        compatibility.get_or_insert(artifact_compatibility);
        toolchain.get_or_insert(artifact_toolchain);

        let Some(fallback) = artifacts.iter().find(|candidate| {
            candidate.path() == optimization.fallback().path()
                && candidate.digest() == optimization.fallback().digest()
        }) else {
            return Err(StandardLibraryManifestError::InvalidOptimizationFallback);
        };

        if !fallbacks.insert(fallback.path()) {
            return Err(StandardLibraryManifestError::InvalidOptimizationFallback);
        }

        let valid_fallback = match optimization.producer().kind() {
            StandardLibraryOptimizationProducerKind::Bray => {
                optimization.partition() == "std"
                    && !std::mem::replace(&mut has_bray_partition, true)
                    && fallback.kind() == StandardLibraryArtifactKind::StaticLibrary
                    && optimization.platform_services().is_empty()
            }
            StandardLibraryOptimizationProducerKind::PinnedNative => {
                fallback.kind() == StandardLibraryArtifactKind::PlatformServiceLibrary
                    && !optimization.platform_services().is_empty()
                    && optimization
                        .platform_services()
                        .iter()
                        .all(|role| fallback.platform_services().contains(role))
                    && optimization
                        .platform_services()
                        .iter()
                        .all(|role| platform_services.insert(*role))
            }
        };

        if !valid_fallback {
            return Err(StandardLibraryManifestError::InvalidOptimizationFallback);
        }

        if optimization.dependencies().iter().any(|dependency| {
            !artifacts.iter().any(|candidate| {
                candidate.kind() == StandardLibraryArtifactKind::DependencyMetadata
                    && candidate.path() == dependency.path()
                    && candidate.digest() == dependency.digest()
            })
        }) {
            return Err(StandardLibraryManifestError::InvalidOptimizationMetadata);
        }
    }

    if !has_bray_partition {
        return Err(StandardLibraryManifestError::InvalidOptimizationMetadata);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroU32;

    use bray_runtime_interface::RuntimeAbiVersion;
    use bray_target::{CodeModel, RelocationModel};

    use super::{
        StandardLibraryOptimizationCompatibility, StandardLibraryOptimizationFallback,
        StandardLibraryOptimizationMetadata, StandardLibraryOptimizationProducer,
        StandardLibraryOptimizationProducerKind,
    };
    use crate::StandardLibraryArtifactDigest;

    #[test]
    fn optimization_metadata_requires_complete_compatibility_identities() {
        let producer = StandardLibraryOptimizationProducer::try_new(
            StandardLibraryOptimizationProducerKind::Bray,
            "llvm",
            "1",
            "llvm",
            "22.1.8",
        )
        .unwrap_or_else(|error| panic!("producer must be valid: {error:?}"));

        let compatibility = StandardLibraryOptimizationCompatibility::try_new(
            "x86_64-unknown-linux-gnu",
            "e-m:e-p:64:64",
            RelocationModel::PositionIndependent,
            CodeModel::Small,
            RuntimeAbiVersion::new(1, 0),
        )
        .unwrap_or_else(|error| panic!("compatibility must be valid: {error:?}"));

        let fallback = StandardLibraryOptimizationFallback::try_new(
            "targets/x86_64-unknown-linux-gnu/1.0/libstd.a",
            StandardLibraryArtifactDigest::new([7; 32]),
        )
        .unwrap_or_else(|error| panic!("fallback must be valid: {error:?}"));

        assert!(
            StandardLibraryOptimizationMetadata::try_new(
                "std.native",
                producer.clone(),
                compatibility.clone(),
                fallback.clone(),
                NonZeroU32::MIN,
            )
            .is_ok()
        );

        assert!(
            StandardLibraryOptimizationMetadata::try_new(
                "Invalid Partition",
                producer,
                compatibility,
                fallback,
                NonZeroU32::MIN,
            )
            .is_err()
        );
    }
}
