[package]
name = "bray-emitter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-codegen = { path = "../bray-codegen" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-linker = { path = "../bray-linker" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-package-interface = { path = "../bray-package-interface" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }
blake3 = "1"
renamore = "0.3"
sha2 = "0.10"
tempfile = "3"

[dev-dependencies]
bray-codegen = { path = "../bray-codegen", features = ["test-support"] }
bray-package-interface = { path = "../bray-package-interface", features = ["test-support"] }
bray-target = { path = "../bray-target", features = ["test-support"] }
bray-testing = { path = "../bray-testing", features = ["mir-unit"] }

[lints]
workspace = true
