[package]
name = "bray-binder"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-bound-tree = { path = "../bray-bound-tree" }
bray-checker = { path = "../bray-checker" }
bray-declarations = { path = "../bray-declarations" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }
bray-syntax = { path = "../bray-syntax" }

[dev-dependencies]
bray-parser = { path = "../bray-parser" }
bray-declarations = { path = "../bray-declarations" }
bray-symbols = { path = "../bray-symbols" }
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
