use std::path::{Path, PathBuf};

use crate::origin::{SourceOrigin, SourceOriginKind};
use crate::snapshot::SourceRevision;

/// Stable category for a source input boundary value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SourceInputKind {
    /// Source text read from a file path.
    File,
    /// Source supplied as virtual text.
    VirtualText,
    /// Source generated by the compiler or another tool.
    GeneratedText,
    /// Source supplied by an open LSP document.
    LspOpenDocument,
}

impl SourceInputKind {
    /// Returns the source origin category produced by this input kind.
    pub const fn origin_kind(self) -> SourceOriginKind {
        match self {
            Self::File => SourceOriginKind::File,
            Self::VirtualText => SourceOriginKind::Virtual,
            Self::GeneratedText => SourceOriginKind::Generated,
            Self::LspOpenDocument => SourceOriginKind::LspDocument,
        }
    }
}

/// Source text plus boundary metadata before insertion into a source store.
#[derive(Debug, Eq, Hash, PartialEq)]
pub enum SourceInput {
    /// Source text read from a file path.
    File {
        path: PathBuf,
        revision: SourceRevision,
        text: String,
    },
    /// Source supplied as virtual text.
    VirtualText {
        name: String,
        revision: SourceRevision,
        text: String,
    },
    /// Source generated by the compiler or another tool.
    GeneratedText {
        name: String,
        revision: SourceRevision,
        text: String,
    },
    /// Source supplied by an open LSP document.
    LspOpenDocument {
        uri: String,
        revision: SourceRevision,
        text: String,
    },
}

impl SourceInput {
    /// Creates a source input from text read at a file path.
    pub fn file(
        path: impl Into<PathBuf>,
        revision: impl Into<SourceRevision>,
        text: impl Into<String>,
    ) -> Self {
        Self::File {
            path: path.into(),
            revision: revision.into(),
            text: text.into(),
        }
    }

    /// Creates a source input from virtual text.
    pub fn virtual_text(
        name: impl Into<String>,
        revision: impl Into<SourceRevision>,
        text: impl Into<String>,
    ) -> Self {
        Self::VirtualText {
            name: name.into(),
            revision: revision.into(),
            text: text.into(),
        }
    }

    /// Creates a source input from generated text.
    pub fn generated_text(
        name: impl Into<String>,
        revision: impl Into<SourceRevision>,
        text: impl Into<String>,
    ) -> Self {
        Self::GeneratedText {
            name: name.into(),
            revision: revision.into(),
            text: text.into(),
        }
    }

    /// Creates a source input from an open LSP document.
    pub fn lsp_open_document(
        uri: impl Into<String>,
        revision: impl Into<SourceRevision>,
        text: impl Into<String>,
    ) -> Self {
        Self::LspOpenDocument {
            uri: uri.into(),
            revision: revision.into(),
            text: text.into(),
        }
    }

    /// Returns the stable source input category.
    pub const fn kind(&self) -> SourceInputKind {
        match self {
            Self::File { .. } => SourceInputKind::File,
            Self::VirtualText { .. } => SourceInputKind::VirtualText,
            Self::GeneratedText { .. } => SourceInputKind::GeneratedText,
            Self::LspOpenDocument { .. } => SourceInputKind::LspOpenDocument,
        }
    }

    /// Returns the source origin category produced by this input.
    pub const fn origin_kind(&self) -> SourceOriginKind {
        self.kind().origin_kind()
    }

    /// Returns the source input revision.
    pub const fn revision(&self) -> SourceRevision {
        match self {
            Self::File { revision, .. }
            | Self::VirtualText { revision, .. }
            | Self::GeneratedText { revision, .. }
            | Self::LspOpenDocument { revision, .. } => *revision,
        }
    }

    /// Returns the source text.
    pub fn text(&self) -> &str {
        match self {
            Self::File { text, .. }
            | Self::VirtualText { text, .. }
            | Self::GeneratedText { text, .. }
            | Self::LspOpenDocument { text, .. } => text,
        }
    }

    /// Returns the file path for file inputs.
    pub fn file_path(&self) -> Option<&Path> {
        match self {
            Self::File { path, .. } => Some(path.as_path()),
            _ => None,
        }
    }

    /// Returns the virtual source name for virtual text inputs.
    pub fn virtual_name(&self) -> Option<&str> {
        match self {
            Self::VirtualText { name, .. } => Some(name),
            _ => None,
        }
    }

    /// Returns the generated source name for generated text inputs.
    pub fn generated_name(&self) -> Option<&str> {
        match self {
            Self::GeneratedText { name, .. } => Some(name),
            _ => None,
        }
    }

    /// Returns the document URI for LSP-open document inputs.
    pub fn lsp_uri(&self) -> Option<&str> {
        match self {
            Self::LspOpenDocument { uri, .. } => Some(uri),
            _ => None,
        }
    }

    /// Converts this input into the pieces needed to create a source snapshot.
    pub fn into_snapshot_parts(self) -> (SourceOrigin, SourceRevision, String) {
        match self {
            Self::File {
                path,
                revision,
                text,
            } => (SourceOrigin::file(path), revision, text),
            Self::VirtualText {
                name,
                revision,
                text,
            } => (SourceOrigin::virtual_source(name), revision, text),
            Self::GeneratedText {
                name,
                revision,
                text,
            } => (SourceOrigin::generated(name), revision, text),
            Self::LspOpenDocument {
                uri,
                revision,
                text,
            } => (SourceOrigin::lsp_document(uri), revision, text),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{SourceInput, SourceInputKind};
    use crate::{SourceOriginKind, SourceRevision};

    #[test]
    fn input_kinds_map_to_origin_kinds() {
        assert_eq!(SourceInputKind::File.origin_kind(), SourceOriginKind::File);

        assert_eq!(
            SourceInputKind::VirtualText.origin_kind(),
            SourceOriginKind::Virtual
        );
        assert_eq!(
            SourceInputKind::GeneratedText.origin_kind(),
            SourceOriginKind::Generated
        );
        assert_eq!(
            SourceInputKind::LspOpenDocument.origin_kind(),
            SourceOriginKind::LspDocument
        );
    }

    #[test]
    fn source_inputs_expose_boundary_metadata() {
        let file = SourceInput::file("main.bray", SourceRevision::new(1), "module main\n");
        let virtual_text = SourceInput::virtual_text("buffer", SourceRevision::new(2), "let x = 1");

        let generated_text =
            SourceInput::generated_text("core", SourceRevision::new(3), "module core\n");

        let lsp_document = SourceInput::lsp_open_document(
            "file:///main.bray",
            SourceRevision::new(4),
            "module main\n",
        );

        assert_eq!(file.kind(), SourceInputKind::File);
        assert_eq!(file.revision(), SourceRevision::new(1));
        assert_eq!(file.text(), "module main\n");

        assert_eq!(
            file.file_path().and_then(|path| path.to_str()),
            Some("main.bray")
        );

        assert_eq!(virtual_text.virtual_name(), Some("buffer"));
        assert_eq!(generated_text.generated_name(), Some("core"));
        assert_eq!(lsp_document.lsp_uri(), Some("file:///main.bray"));
    }

    #[test]
    fn source_inputs_convert_to_snapshot_parts_without_changing_meaning() {
        let input = SourceInput::lsp_open_document(
            "file:///main.bray",
            SourceRevision::new(8),
            "module main\n",
        );

        let (origin, revision, text) = input.into_snapshot_parts();

        assert_eq!(origin.kind(), SourceOriginKind::LspDocument);
        assert_eq!(origin.lsp_uri(), Some("file:///main.bray"));
        assert_eq!(revision, SourceRevision::new(8));
        assert_eq!(text, "module main\n");
    }

    #[test]
    fn source_inputs_are_send_and_sync() {
        assert_send_sync::<SourceInput>();
    }

    fn assert_send_sync<T: Send + Sync>() {}
}
