use std::path::{Path, PathBuf};

use crate::identity::SourceIdentity;
use crate::origin::{SourceOrigin, SourceOriginKind};
use crate::version::SourceVersion;

/// Stable category for a source input boundary value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SourceInputKind {
    /// Source text read from a file path.
    File,
    /// Source supplied as virtual text.
    VirtualText,
    /// Source generated by the compiler or another tool.
    GeneratedText,
    /// Source supplied by an open LSP document.
    LspOpenDocument,
}

impl SourceInputKind {
    /// Returns the source origin category produced by this input kind.
    pub const fn origin_kind(self) -> SourceOriginKind {
        match self {
            Self::File => SourceOriginKind::File,
            Self::VirtualText => SourceOriginKind::Virtual,
            Self::GeneratedText => SourceOriginKind::Generated,
            Self::LspOpenDocument => SourceOriginKind::LspDocument,
        }
    }

    /// Returns the stable machine key for this source input category.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::File => "file",
            Self::VirtualText => "virtual_text",
            Self::GeneratedText => "generated_text",
            Self::LspOpenDocument => "lsp_open_document",
        }
    }
}

/// Source content plus boundary metadata before loading into a source snapshot.
#[derive(Debug, Eq, Hash, PartialEq)]
pub struct SourceInput {
    identity: SourceIdentity,
    origin: SourceInputOrigin,
    version: SourceVersion,
    content: SourceInputContent,
}

#[derive(Debug, Eq, Hash, PartialEq)]
enum SourceInputOrigin {
    File { path: PathBuf },
    VirtualText { name: String },
    GeneratedText { name: String },
    LspOpenDocument { uri: String },
}

#[derive(Debug, Eq, Hash, PartialEq)]
pub(crate) enum SourceInputContent {
    Text(String),
    Bytes(Vec<u8>),
}

impl SourceInput {
    /// Creates a file source input from already-decoded text.
    pub fn file(
        identity: SourceIdentity,
        path: impl Into<PathBuf>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::new(
            identity,
            SourceInputOrigin::File { path: path.into() },
            version,
            SourceInputContent::Text(text.into()),
        )
    }

    /// Creates a file source input from raw bytes.
    ///
    /// Raw bytes are validated as UTF-8 and normalized for a leading UTF-8 byte
    /// order mark by [`SourceLoader`](crate::SourceLoader).
    pub fn file_bytes(
        identity: SourceIdentity,
        path: impl Into<PathBuf>,
        version: impl Into<SourceVersion>,
        bytes: impl Into<Vec<u8>>,
    ) -> Self {
        Self::new(
            identity,
            SourceInputOrigin::File { path: path.into() },
            version,
            SourceInputContent::Bytes(bytes.into()),
        )
    }

    /// Creates a source input from virtual text.
    pub fn virtual_text(
        identity: SourceIdentity,
        name: impl Into<String>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::new(
            identity,
            SourceInputOrigin::VirtualText { name: name.into() },
            version,
            SourceInputContent::Text(text.into()),
        )
    }

    /// Creates a source input from generated text.
    pub fn generated_text(
        identity: SourceIdentity,
        name: impl Into<String>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::new(
            identity,
            SourceInputOrigin::GeneratedText { name: name.into() },
            version,
            SourceInputContent::Text(text.into()),
        )
    }

    /// Creates a source input from an open LSP document.
    pub fn lsp_open_document(
        identity: SourceIdentity,
        uri: impl Into<String>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::new(
            identity,
            SourceInputOrigin::LspOpenDocument { uri: uri.into() },
            version,
            SourceInputContent::Text(text.into()),
        )
    }

    /// Returns the stable source input category.
    pub const fn kind(&self) -> SourceInputKind {
        self.origin.kind()
    }

    /// Returns the source origin category produced by this input.
    pub const fn origin_kind(&self) -> SourceOriginKind {
        self.kind().origin_kind()
    }

    /// Returns the logical source identity.
    pub const fn identity(&self) -> SourceIdentity {
        self.identity
    }

    /// Returns the source input version.
    pub const fn version(&self) -> SourceVersion {
        self.version
    }

    /// Returns decoded source text when the input already stores text.
    ///
    /// Raw byte inputs return `None` until loaded through
    /// [`SourceLoader`](crate::SourceLoader).
    pub fn text(&self) -> Option<&str> {
        self.content.text()
    }

    /// Returns the source input bytes held at the boundary.
    ///
    /// Text inputs return their UTF-8 byte representation. Raw byte inputs
    /// return their undecoded bytes.
    pub fn bytes(&self) -> &[u8] {
        self.content.bytes()
    }

    /// Returns the file path for file inputs.
    pub fn file_path(&self) -> Option<&Path> {
        match &self.origin {
            SourceInputOrigin::File { path } => Some(path.as_path()),
            _ => None,
        }
    }

    /// Returns the virtual source name for virtual text inputs.
    pub fn virtual_name(&self) -> Option<&str> {
        match &self.origin {
            SourceInputOrigin::VirtualText { name } => Some(name),
            _ => None,
        }
    }

    /// Returns the generated source name for generated text inputs.
    pub fn generated_name(&self) -> Option<&str> {
        match &self.origin {
            SourceInputOrigin::GeneratedText { name } => Some(name),
            _ => None,
        }
    }

    /// Returns the document URI for LSP-open document inputs.
    pub fn lsp_uri(&self) -> Option<&str> {
        match &self.origin {
            SourceInputOrigin::LspOpenDocument { uri } => Some(uri),
            _ => None,
        }
    }

    pub(crate) fn into_snapshot_parts(
        self,
    ) -> (
        SourceIdentity,
        SourceOrigin,
        SourceVersion,
        SourceInputContent,
    ) {
        let origin = self.origin.into_origin();

        (self.identity, origin, self.version, self.content)
    }

    fn new(
        identity: SourceIdentity,
        origin: SourceInputOrigin,
        version: impl Into<SourceVersion>,
        content: SourceInputContent,
    ) -> Self {
        Self {
            identity,
            origin,
            version: version.into(),
            content,
        }
    }
}

impl SourceInputOrigin {
    const fn kind(&self) -> SourceInputKind {
        match self {
            Self::File { .. } => SourceInputKind::File,
            Self::VirtualText { .. } => SourceInputKind::VirtualText,
            Self::GeneratedText { .. } => SourceInputKind::GeneratedText,
            Self::LspOpenDocument { .. } => SourceInputKind::LspOpenDocument,
        }
    }

    fn into_origin(self) -> SourceOrigin {
        match self {
            Self::File { path } => SourceOrigin::file(path),
            Self::VirtualText { name } => SourceOrigin::virtual_source(name),
            Self::GeneratedText { name } => SourceOrigin::generated(name),
            Self::LspOpenDocument { uri } => SourceOrigin::lsp_document(uri),
        }
    }
}

impl SourceInputContent {
    fn text(&self) -> Option<&str> {
        match self {
            Self::Text(text) => Some(text),
            Self::Bytes(_) => None,
        }
    }

    fn bytes(&self) -> &[u8] {
        match self {
            Self::Text(text) => text.as_bytes(),
            Self::Bytes(bytes) => bytes.as_slice(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{SourceInput, SourceInputKind};
    use crate::{SourceIdentity, SourceOriginKind, SourceVersion};

    #[test]
    fn input_kinds_map_to_origin_kinds() {
        assert_eq!(SourceInputKind::File.origin_kind(), SourceOriginKind::File);
        assert_eq!(SourceInputKind::File.as_str(), "file");

        assert_eq!(
            SourceInputKind::VirtualText.origin_kind(),
            SourceOriginKind::Virtual
        );

        assert_eq!(
            SourceInputKind::GeneratedText.origin_kind(),
            SourceOriginKind::Generated
        );

        assert_eq!(
            SourceInputKind::LspOpenDocument.origin_kind(),
            SourceOriginKind::LspDocument
        );
    }

    #[test]
    fn source_inputs_expose_boundary_metadata() {
        let file = SourceInput::file(
            SourceIdentity::new(1),
            "main.bray",
            SourceVersion::new(1),
            "module main\n",
        );

        let virtual_text = SourceInput::virtual_text(
            SourceIdentity::new(2),
            "buffer",
            SourceVersion::new(2),
            "let x = 1",
        );

        let generated_text = SourceInput::generated_text(
            SourceIdentity::new(3),
            "core",
            SourceVersion::new(3),
            "module core\n",
        );

        let lsp_document = SourceInput::lsp_open_document(
            SourceIdentity::new(4),
            "file:///main.bray",
            SourceVersion::new(4),
            "module main\n",
        );

        assert_eq!(file.kind(), SourceInputKind::File);
        assert_eq!(file.identity(), SourceIdentity::new(1));
        assert_eq!(file.version(), SourceVersion::new(1));
        assert_eq!(file.text(), Some("module main\n"));
        assert_eq!(file.bytes(), b"module main\n");

        assert_eq!(
            file.file_path().and_then(|path| path.to_str()),
            Some("main.bray")
        );

        assert_eq!(virtual_text.virtual_name(), Some("buffer"));
        assert_eq!(generated_text.generated_name(), Some("core"));
        assert_eq!(lsp_document.lsp_uri(), Some("file:///main.bray"));
    }

    #[test]
    fn source_inputs_can_hold_raw_file_bytes() {
        let input = SourceInput::file_bytes(
            SourceIdentity::new(5),
            "main.bray",
            SourceVersion::new(1),
            vec![0xef, 0xbb, 0xbf, b'm'],
        );

        assert_eq!(input.kind(), SourceInputKind::File);
        assert_eq!(input.text(), None);
        assert_eq!(input.bytes(), &[0xef, 0xbb, 0xbf, b'm']);
    }

    #[test]
    fn source_inputs_convert_to_snapshot_parts_without_changing_meaning() {
        let input = SourceInput::lsp_open_document(
            SourceIdentity::new(6),
            "file:///main.bray",
            SourceVersion::new(8),
            "module main\n",
        );

        let (identity, origin, version, content) = input.into_snapshot_parts();

        assert_eq!(identity, SourceIdentity::new(6));
        assert_eq!(origin.kind(), SourceOriginKind::LspDocument);
        assert_eq!(origin.lsp_uri(), Some("file:///main.bray"));
        assert_eq!(version, SourceVersion::new(8));
        assert_eq!(content.text(), Some("module main\n"));
    }

    #[test]
    fn source_inputs_are_send_and_sync() {
        assert_send_sync::<SourceInput>();
    }

    fn assert_send_sync<T: Send + Sync>() {}
}
