use std::path::{Path, PathBuf};

use crate::identity::SourceIdentity;
use crate::origin::{SourceOrigin, SourceOriginKind};
use crate::version::SourceVersion;

/// Stable category for a source input boundary value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SourceInputKind {
    /// Source text read from a file path.
    File,
    /// Source supplied as virtual text.
    VirtualText,
    /// Source generated by the compiler or another tool.
    GeneratedText,
    /// Source supplied by an open LSP document.
    LspOpenDocument,
}

impl SourceInputKind {
    /// Returns the source origin category produced by this input kind.
    pub const fn origin_kind(self) -> SourceOriginKind {
        match self {
            Self::File => SourceOriginKind::File,
            Self::VirtualText => SourceOriginKind::Virtual,
            Self::GeneratedText => SourceOriginKind::Generated,
            Self::LspOpenDocument => SourceOriginKind::LspDocument,
        }
    }
}

/// Source text plus boundary metadata before insertion into a source store.
#[derive(Debug, Eq, Hash, PartialEq)]
pub enum SourceInput {
    /// Source text read from a file path.
    File {
        identity: SourceIdentity,
        path: PathBuf,
        version: SourceVersion,
        text: String,
    },
    /// Source supplied as virtual text.
    VirtualText {
        identity: SourceIdentity,
        name: String,
        version: SourceVersion,
        text: String,
    },
    /// Source generated by the compiler or another tool.
    GeneratedText {
        identity: SourceIdentity,
        name: String,
        version: SourceVersion,
        text: String,
    },
    /// Source supplied by an open LSP document.
    LspOpenDocument {
        identity: SourceIdentity,
        uri: String,
        version: SourceVersion,
        text: String,
    },
}

impl SourceInput {
    /// Creates a source input from text read at a file path.
    pub fn file(
        identity: SourceIdentity,
        path: impl Into<PathBuf>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::File {
            identity,
            path: path.into(),
            version: version.into(),
            text: text.into(),
        }
    }

    /// Creates a source input from virtual text.
    pub fn virtual_text(
        identity: SourceIdentity,
        name: impl Into<String>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::VirtualText {
            identity,
            name: name.into(),
            version: version.into(),
            text: text.into(),
        }
    }

    /// Creates a source input from generated text.
    pub fn generated_text(
        identity: SourceIdentity,
        name: impl Into<String>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::GeneratedText {
            identity,
            name: name.into(),
            version: version.into(),
            text: text.into(),
        }
    }

    /// Creates a source input from an open LSP document.
    pub fn lsp_open_document(
        identity: SourceIdentity,
        uri: impl Into<String>,
        version: impl Into<SourceVersion>,
        text: impl Into<String>,
    ) -> Self {
        Self::LspOpenDocument {
            identity,
            uri: uri.into(),
            version: version.into(),
            text: text.into(),
        }
    }

    /// Returns the stable source input category.
    pub const fn kind(&self) -> SourceInputKind {
        match self {
            Self::File { .. } => SourceInputKind::File,
            Self::VirtualText { .. } => SourceInputKind::VirtualText,
            Self::GeneratedText { .. } => SourceInputKind::GeneratedText,
            Self::LspOpenDocument { .. } => SourceInputKind::LspOpenDocument,
        }
    }

    /// Returns the source origin category produced by this input.
    pub const fn origin_kind(&self) -> SourceOriginKind {
        self.kind().origin_kind()
    }

    /// Returns the logical source identity.
    pub const fn identity(&self) -> SourceIdentity {
        match self {
            Self::File { identity, .. }
            | Self::VirtualText { identity, .. }
            | Self::GeneratedText { identity, .. }
            | Self::LspOpenDocument { identity, .. } => *identity,
        }
    }

    /// Returns the source input version.
    pub const fn version(&self) -> SourceVersion {
        match self {
            Self::File { version, .. }
            | Self::VirtualText { version, .. }
            | Self::GeneratedText { version, .. }
            | Self::LspOpenDocument { version, .. } => *version,
        }
    }

    /// Returns the source text.
    pub fn text(&self) -> &str {
        match self {
            Self::File { text, .. }
            | Self::VirtualText { text, .. }
            | Self::GeneratedText { text, .. }
            | Self::LspOpenDocument { text, .. } => text,
        }
    }

    /// Returns the file path for file inputs.
    pub fn file_path(&self) -> Option<&Path> {
        match self {
            Self::File { path, .. } => Some(path.as_path()),
            _ => None,
        }
    }

    /// Returns the virtual source name for virtual text inputs.
    pub fn virtual_name(&self) -> Option<&str> {
        match self {
            Self::VirtualText { name, .. } => Some(name),
            _ => None,
        }
    }

    /// Returns the generated source name for generated text inputs.
    pub fn generated_name(&self) -> Option<&str> {
        match self {
            Self::GeneratedText { name, .. } => Some(name),
            _ => None,
        }
    }

    /// Returns the document URI for LSP-open document inputs.
    pub fn lsp_uri(&self) -> Option<&str> {
        match self {
            Self::LspOpenDocument { uri, .. } => Some(uri),
            _ => None,
        }
    }

    pub(crate) fn into_snapshot_parts(
        self,
    ) -> (SourceIdentity, SourceOrigin, SourceVersion, String) {
        match self {
            Self::File {
                identity,
                path,
                version,
                text,
            } => (identity, SourceOrigin::file(path), version, text),
            Self::VirtualText {
                identity,
                name,
                version,
                text,
            } => (identity, SourceOrigin::virtual_source(name), version, text),
            Self::GeneratedText {
                identity,
                name,
                version,
                text,
            } => (identity, SourceOrigin::generated(name), version, text),
            Self::LspOpenDocument {
                identity,
                uri,
                version,
                text,
            } => (identity, SourceOrigin::lsp_document(uri), version, text),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{SourceInput, SourceInputKind};
    use crate::{SourceIdentity, SourceOriginKind, SourceVersion};

    #[test]
    fn input_kinds_map_to_origin_kinds() {
        assert_eq!(SourceInputKind::File.origin_kind(), SourceOriginKind::File);

        assert_eq!(
            SourceInputKind::VirtualText.origin_kind(),
            SourceOriginKind::Virtual
        );
        assert_eq!(
            SourceInputKind::GeneratedText.origin_kind(),
            SourceOriginKind::Generated
        );
        assert_eq!(
            SourceInputKind::LspOpenDocument.origin_kind(),
            SourceOriginKind::LspDocument
        );
    }

    #[test]
    fn source_inputs_expose_boundary_metadata() {
        let file = SourceInput::file(
            SourceIdentity::new(1),
            "main.bray",
            SourceVersion::new(1),
            "module main\n",
        );

        let virtual_text = SourceInput::virtual_text(
            SourceIdentity::new(2),
            "buffer",
            SourceVersion::new(2),
            "let x = 1",
        );

        let generated_text = SourceInput::generated_text(
            SourceIdentity::new(3),
            "core",
            SourceVersion::new(3),
            "module core\n",
        );

        let lsp_document = SourceInput::lsp_open_document(
            SourceIdentity::new(4),
            "file:///main.bray",
            SourceVersion::new(4),
            "module main\n",
        );

        assert_eq!(file.kind(), SourceInputKind::File);
        assert_eq!(file.identity(), SourceIdentity::new(1));
        assert_eq!(file.version(), SourceVersion::new(1));
        assert_eq!(file.text(), "module main\n");

        assert_eq!(
            file.file_path().and_then(|path| path.to_str()),
            Some("main.bray")
        );

        assert_eq!(virtual_text.virtual_name(), Some("buffer"));
        assert_eq!(generated_text.generated_name(), Some("core"));
        assert_eq!(lsp_document.lsp_uri(), Some("file:///main.bray"));
    }

    #[test]
    fn source_inputs_convert_to_snapshot_parts_without_changing_meaning() {
        let input = SourceInput::lsp_open_document(
            SourceIdentity::new(6),
            "file:///main.bray",
            SourceVersion::new(8),
            "module main\n",
        );

        let (identity, origin, version, text) = input.into_snapshot_parts();

        assert_eq!(identity, SourceIdentity::new(6));
        assert_eq!(origin.kind(), SourceOriginKind::LspDocument);
        assert_eq!(origin.lsp_uri(), Some("file:///main.bray"));
        assert_eq!(version, SourceVersion::new(8));
        assert_eq!(text, "module main\n");
    }

    #[test]
    fn source_inputs_are_send_and_sync() {
        assert_send_sync::<SourceInput>();
    }

    fn assert_send_sync<T: Send + Sync>() {}
}
