use std::path::{Path, PathBuf};

/// Stable category for where a source input came from.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SourceOriginKind {
    /// Source loaded from a file path.
    File,
    /// Source supplied as virtual or in-memory text.
    Virtual,
    /// Source generated by the compiler or another tool.
    Generated,
    /// Source supplied by an LSP document URI.
    LspDocument,
    /// Source loaded from a test fixture.
    TestFixture,
    /// Source read from standard input.
    Stdin,
}

/// Structured description of where a source input came from.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SourceOrigin {
    /// Source loaded from a file path.
    File { path: PathBuf },
    /// Source supplied as virtual or in-memory text.
    Virtual { name: String },
    /// Source generated by the compiler or another tool.
    Generated { name: String },
    /// Source supplied by an LSP document URI.
    LspDocument { uri: String },
    /// Source loaded from a test fixture.
    TestFixture { name: String },
    /// Source read from standard input.
    Stdin,
}

impl SourceOrigin {
    /// Creates a file source origin.
    pub fn file(path: impl Into<PathBuf>) -> Self {
        Self::File { path: path.into() }
    }

    /// Creates a virtual or in-memory source origin.
    pub fn virtual_source(name: impl Into<String>) -> Self {
        Self::Virtual { name: name.into() }
    }

    /// Creates a generated source origin.
    pub fn generated(name: impl Into<String>) -> Self {
        Self::Generated { name: name.into() }
    }

    /// Creates an LSP document source origin.
    pub fn lsp_document(uri: impl Into<String>) -> Self {
        Self::LspDocument { uri: uri.into() }
    }

    /// Creates a test fixture source origin.
    pub fn test_fixture(name: impl Into<String>) -> Self {
        Self::TestFixture { name: name.into() }
    }

    /// Creates a standard input source origin.
    pub const fn stdin() -> Self {
        Self::Stdin
    }

    /// Returns the stable source origin category.
    pub const fn kind(&self) -> SourceOriginKind {
        match self {
            Self::File { .. } => SourceOriginKind::File,
            Self::Virtual { .. } => SourceOriginKind::Virtual,
            Self::Generated { .. } => SourceOriginKind::Generated,
            Self::LspDocument { .. } => SourceOriginKind::LspDocument,
            Self::TestFixture { .. } => SourceOriginKind::TestFixture,
            Self::Stdin => SourceOriginKind::Stdin,
        }
    }

    /// Returns the file path for file origins.
    pub fn file_path(&self) -> Option<&Path> {
        match self {
            Self::File { path } => Some(path.as_path()),
            _ => None,
        }
    }

    /// Returns the virtual source name for virtual origins.
    pub fn virtual_name(&self) -> Option<&str> {
        match self {
            Self::Virtual { name } => Some(name),
            _ => None,
        }
    }

    /// Returns the generated source name for generated origins.
    pub fn generated_name(&self) -> Option<&str> {
        match self {
            Self::Generated { name } => Some(name),
            _ => None,
        }
    }

    /// Returns the document URI for LSP document origins.
    pub fn lsp_uri(&self) -> Option<&str> {
        match self {
            Self::LspDocument { uri } => Some(uri),
            _ => None,
        }
    }

    /// Returns the fixture name for test fixture origins.
    pub fn test_fixture_name(&self) -> Option<&str> {
        match self {
            Self::TestFixture { name } => Some(name),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{SourceOrigin, SourceOriginKind};

    #[test]
    fn source_origins_report_their_kind() {
        assert_eq!(
            SourceOrigin::file("main.bray").kind(),
            SourceOriginKind::File
        );
        assert_eq!(
            SourceOrigin::virtual_source("memory").kind(),
            SourceOriginKind::Virtual
        );
        assert_eq!(
            SourceOrigin::generated("lowered").kind(),
            SourceOriginKind::Generated
        );
        assert_eq!(
            SourceOrigin::lsp_document("file:///main.bray").kind(),
            SourceOriginKind::LspDocument
        );
        assert_eq!(
            SourceOrigin::test_fixture("fixture").kind(),
            SourceOriginKind::TestFixture
        );
        assert_eq!(SourceOrigin::stdin().kind(), SourceOriginKind::Stdin);
    }

    #[test]
    fn source_origins_expose_variant_payloads() {
        let file = SourceOrigin::file("main.bray");
        let virtual_source = SourceOrigin::virtual_source("buffer");
        let generated = SourceOrigin::generated("core");
        let lsp_document = SourceOrigin::lsp_document("file:///main.bray");
        let fixture = SourceOrigin::test_fixture("lexer/invalid-char");

        assert_eq!(
            file.file_path().and_then(|path| path.to_str()),
            Some("main.bray")
        );

        assert_eq!(virtual_source.virtual_name(), Some("buffer"));
        assert_eq!(generated.generated_name(), Some("core"));
        assert_eq!(lsp_document.lsp_uri(), Some("file:///main.bray"));
        assert_eq!(fixture.test_fixture_name(), Some("lexer/invalid-char"));
        assert_eq!(SourceOrigin::stdin().file_path(), None);
    }
}
