mod assembly;
mod build;
mod check;
mod control;
mod execution;
mod fixed_point;
mod id;
mod liveness;
mod model;
mod propagation;
mod reachability;
mod refinement;
mod storage_flow;

pub(crate) use build::{ControlFlowGraphBuildOutcome, build_control_flow_graph};
pub(crate) use check::check_control_flow;
pub(crate) use liveness::analyze_storage_liveness;
pub(crate) use model::{AnalysisOperationKind, AnalysisTaskOperationKind};
pub(crate) use refinement::check_refinements;
pub(crate) use storage_flow::check_storage_flow;
pub use storage_flow::{closed_type_is_copyable, type_is_copyable, type_is_copyable_in_context};
