use std::collections::BTreeSet;
use std::hash::{Hash, Hasher};
use std::sync::Arc;

use bray_base::{StableDigestHasher, shared_slice, sorted_unique_shared_slice};
use bray_ir::{MirTargetFacts, MirUnit, MirUnitId};

use super::{
    CodegenInstance, CodegenInstanceDependency, CodegenInstanceKey, CodegenOversizedUnit,
    CodegenPartitionCompatibility, CodegenPartitionPolicy, CodegenWork,
};

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct CodegenUnitKeyData {
    partition_policy: CodegenPartitionPolicy,
    estimated_work: CodegenWork,
    oversized: Option<CodegenOversizedUnit>,
    content_identity: [u8; 32],
    target: MirTargetFacts,
    recipe: Arc<CodegenUnitRecipe>,
}

/// Stable structural identity of one partitioned code generation unit.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CodegenUnitKey(Arc<CodegenUnitKeyData>);

#[derive(Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct CodegenUnitRecipe {
    instances: Arc<[CodegenInstanceKey]>,
    compatibilities: Arc<[CodegenPartitionCompatibility]>,
    mir_units: Arc<[MirUnitId]>,
    dependencies: Arc<[Arc<[CodegenInstanceDependency]>]>,
}

impl CodegenUnitKey {
    /// Returns the complete code generation partition policy.
    pub fn partition_policy(&self) -> CodegenPartitionPolicy {
        self.0.partition_policy
    }

    /// Returns the package, linkage, and visibility class of one contained definition.
    pub fn compatibility(
        &self,
        instance: &CodegenInstanceKey,
    ) -> Option<&CodegenPartitionCompatibility> {
        self.0
            .recipe
            .instances
            .binary_search(instance)
            .ok()
            .map(|index| &self.0.recipe.compatibilities[index])
    }

    /// Returns deterministic estimated generation work.
    pub fn estimated_work(&self) -> CodegenWork {
        self.0.estimated_work
    }

    /// Returns metadata when an indivisible unit exceeds the policy upper bound.
    pub fn oversized(&self) -> Option<CodegenOversizedUnit> {
        self.0.oversized
    }

    /// Returns the stable identity of complete MIR structure and dependency edges.
    pub fn content_identity(&self) -> [u8; 32] {
        self.0.content_identity
    }

    /// Returns the target affecting generated bytes.
    pub fn target(&self) -> &MirTargetFacts {
        &self.0.target
    }

    /// Returns canonical concrete definitions that structurally identify this unit.
    pub fn instances(&self) -> &[CodegenInstanceKey] {
        &self.0.recipe.instances
    }

    /// Returns exact generated-definition dependencies for one named instance.
    pub fn dependencies(
        &self,
        instance: &CodegenInstanceKey,
    ) -> Option<&[CodegenInstanceDependency]> {
        self.0
            .recipe
            .instances
            .binary_search(instance)
            .ok()
            .map(|index| self.0.recipe.dependencies[index].as_ref())
    }

    /// Returns the MIR unit identity used by one named concrete instance.
    pub fn mir_unit(&self, instance: &CodegenInstanceKey) -> Option<MirUnitId> {
        self.0
            .recipe
            .instances
            .binary_search(instance)
            .ok()
            .map(|index| self.0.recipe.mir_units[index])
    }
}

/// One immutable independently generated collection of concrete MIR definitions.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct CodegenUnit {
    key: CodegenUnitKey,
    target: MirTargetFacts,
    estimated_work: CodegenWork,
    oversized: Option<CodegenOversizedUnit>,
    instances: Arc<[CodegenInstance]>,
    external_instances: Arc<[CodegenInstanceKey]>,
}

impl CodegenUnit {
    /// Creates a unit from non-generic MIR definitions without external dependencies.
    pub fn try_new(
        partition_policy: CodegenPartitionPolicy,
        compatibility: CodegenPartitionCompatibility,
        mir_units: impl IntoIterator<Item = MirUnit>,
    ) -> Result<Self, CodegenUnitBuildError> {
        Self::try_from_instances(
            partition_policy,
            compatibility,
            mir_units.into_iter().map(CodegenInstance::non_generic),
        )
    }

    /// Creates a unit from one or more concrete instances.
    pub fn try_from_instances(
        partition_policy: CodegenPartitionPolicy,
        compatibility: CodegenPartitionCompatibility,
        instances: impl IntoIterator<Item = CodegenInstance>,
    ) -> Result<Self, CodegenUnitBuildError> {
        // Every recipe entry owns the Arc-backed package identity after this call returns.
        Self::try_from_partition(
            partition_policy,
            instances,
            |_| Some(compatibility.clone()),
            false,
        )
    }

    /// Creates a unit with an exact compatibility class for every concrete definition.
    pub fn try_from_partitioned_instances(
        partition_policy: CodegenPartitionPolicy,
        instances: impl IntoIterator<Item = CodegenInstance>,
        compatibility: impl Fn(&CodegenInstance) -> Option<CodegenPartitionCompatibility>,
    ) -> Result<Self, CodegenUnitBuildError> {
        Self::try_from_partition(partition_policy, instances, compatibility, false)
    }

    pub(super) fn try_from_indivisible_group(
        partition_policy: CodegenPartitionPolicy,
        instances: impl IntoIterator<Item = CodegenInstance>,
        compatibility: impl Fn(&CodegenInstance) -> Option<CodegenPartitionCompatibility>,
    ) -> Result<Self, CodegenUnitBuildError> {
        Self::try_from_partition(partition_policy, instances, compatibility, true)
    }

    fn try_from_partition(
        partition_policy: CodegenPartitionPolicy,
        instances: impl IntoIterator<Item = CodegenInstance>,
        compatibility: impl Fn(&CodegenInstance) -> Option<CodegenPartitionCompatibility>,
        indivisible: bool,
    ) -> Result<Self, CodegenUnitBuildError> {
        let mut instances: Vec<_> = instances.into_iter().collect();

        if instances.is_empty() {
            return Err(CodegenUnitBuildError::Empty);
        }

        instances.sort_unstable_by(|left, right| left.key().cmp(right.key()));

        if instances
            .windows(2)
            .any(|pair| pair[0].key() == pair[1].key())
        {
            return Err(CodegenUnitBuildError::DuplicateInstance);
        }

        let Some(compatibilities) = instances.iter().map(compatibility).collect::<Option<Vec<_>>>()
        else {
            return Err(CodegenUnitBuildError::MissingCompatibility);
        };

        // The unit owns target facts independently of its instance collection.
        let target = instances[0].key().target().clone();

        if instances
            .iter()
            .any(|instance| instance.key().target() != &target)
        {
            return Err(CodegenUnitBuildError::TargetMismatch);
        }

        let membership: BTreeSet<_> = instances.iter().map(|instance| instance.key()).collect();

        // The unit recipe owns dependency identities beyond each instance borrow.
        let external_instances = sorted_unique_shared_slice(
            instances
                .iter()
                .flat_map(|instance| instance.dependencies())
                .map(crate::CodegenInstanceDependency::instance)
                .filter(|dependency| !membership.contains(dependency))
                .cloned(),
        );

        // The structural recipe owns identities independently of retained instance payloads.
        let instance_keys = shared_slice(instances.iter().map(|instance| instance.key().clone()));
        let compatibilities = shared_slice(compatibilities);
        let mir_units = shared_slice(instances.iter().map(|instance| instance.mir().unit()));

        let dependencies = shared_slice(
            instances
                .iter()
                .map(|instance| Arc::from(instance.dependencies())),
        );

        let estimated_work = instances.iter().fold(CodegenWork::new(0), |work, instance| {
            work.saturating_add(partition_policy.estimate(instance))
        });

        let oversized = if estimated_work > partition_policy.upper_bound() {
            if !indivisible {
                return Err(CodegenUnitBuildError::WorkBoundExceeded);
            }

            Some(CodegenOversizedUnit::indivisible(
                estimated_work,
                partition_policy.upper_bound(),
            ))
        } else {
            None
        };

        let content_identity = content_identity(
            partition_policy,
            &compatibilities,
            estimated_work,
            oversized,
            &instances,
        );

        Ok(Self {
            key: CodegenUnitKey(Arc::new(CodegenUnitKeyData {
                partition_policy,
                estimated_work,
                oversized,
                content_identity,
                // The key retains target identity independently of the unit payload.
                target: target.clone(),
                recipe: Arc::new(CodegenUnitRecipe {
                    instances: instance_keys,
                    compatibilities,
                    mir_units,
                    dependencies,
                }),
            })),
            target,
            estimated_work,
            oversized,
            instances: instances.into(),
            external_instances,
        })
    }

    /// Returns target facts shared by every contained concrete definition.
    pub const fn target(&self) -> &MirTargetFacts {
        &self.target
    }

    /// Returns the stable structural unit key.
    pub const fn key(&self) -> &CodegenUnitKey {
        &self.key
    }

    /// Returns the package, linkage, and visibility class of one contained definition.
    pub fn compatibility(
        &self,
        instance: &CodegenInstanceKey,
    ) -> Option<&CodegenPartitionCompatibility> {
        self.key.compatibility(instance)
    }

    /// Returns deterministic estimated generation work.
    pub const fn estimated_work(&self) -> CodegenWork {
        self.estimated_work
    }

    /// Returns metadata when an indivisible unit exceeds the policy upper bound.
    pub const fn oversized(&self) -> Option<CodegenOversizedUnit> {
        self.oversized
    }

    /// Returns concrete definitions in canonical identity order.
    pub fn instances(&self) -> &[CodegenInstance] {
        &self.instances
    }

    /// Iterates validated MIR templates in concrete-instance order.
    pub fn mir_units(&self) -> impl ExactSizeIterator<Item = &MirUnit> {
        self.instances.iter().map(CodegenInstance::mir)
    }

    /// Returns generated definitions referenced outside this unit.
    pub fn external_instances(&self) -> &[CodegenInstanceKey] {
        &self.external_instances
    }
}

fn content_identity(
    partition_policy: CodegenPartitionPolicy,
    compatibilities: &[CodegenPartitionCompatibility],
    estimated_work: CodegenWork,
    oversized: Option<CodegenOversizedUnit>,
    instances: &[CodegenInstance],
) -> [u8; 32] {
    let mut hasher = StableDigestHasher::new();

    hasher.write(b"bray.codegen-unit-content");
    partition_policy.hash(&mut hasher);
    compatibilities.hash(&mut hasher);
    estimated_work.hash(&mut hasher);
    oversized.hash(&mut hasher);
    instances.hash(&mut hasher);

    hasher.finalize()
}

/// A contract violation that prevents creation of a code generation unit.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum CodegenUnitBuildError {
    /// The partition contains no definitions.
    Empty,
    /// Two entries describe the same concrete definition.
    DuplicateInstance,
    /// One concrete definition has no package, linkage, or visibility class.
    MissingCompatibility,
    /// Concrete definitions were lowered for different targets.
    TargetMismatch,
    /// Divisible membership exceeds the selected policy upper bound.
    WorkBoundExceeded,
}

#[cfg(test)]
mod tests {
    use bray_ir::{
        MirBlockKind, MirSourceAnchor, MirStorageKind, MirTerminatorKind, MirUnit, MirUnitBuilder,
        MirUnitKind,
    };
    use bray_testing::{
        test_bound_unit_with_declaration, test_mir_target, test_mir_type, test_mir_unit,
        test_mir_unit_with_declaration,
    };

    use super::{CodegenUnit, CodegenUnitBuildError};
    use crate::test_support::codegen_partition_compatibility;
    use crate::{
        CodegenInstance, CodegenInstanceDependency, CodegenInstanceKey, CodegenPartitionPolicy,
    };

    #[test]
    fn units_reject_empty_and_duplicate_instance_membership() {
        assert_eq!(
            CodegenUnit::try_new(
                CodegenPartitionPolicy::NATIVE_BALANCED,
                codegen_partition_compatibility(),
                [],
            ),
            Err(CodegenUnitBuildError::Empty)
        );

        let first = CodegenInstance::non_generic(test_mir_unit(4));
        let duplicate = first.clone();

        assert_eq!(
            CodegenUnit::try_from_instances(
                CodegenPartitionPolicy::NATIVE_BALANCED,
                codegen_partition_compatibility(),
                [first, duplicate],
            ),
            Err(CodegenUnitBuildError::DuplicateInstance)
        );
    }

    #[test]
    fn units_derive_equal_keys_independently_of_input_order() {
        let first = CodegenUnit::try_new(
            CodegenPartitionPolicy::NATIVE_BALANCED,
            codegen_partition_compatibility(),
            [test_mir_unit_with_declaration(8, 1), test_mir_unit(4)],
        );

        let second = CodegenUnit::try_new(
            CodegenPartitionPolicy::NATIVE_BALANCED,
            codegen_partition_compatibility(),
            [test_mir_unit(4), test_mir_unit_with_declaration(8, 1)],
        );

        assert_eq!(first, second);
    }

    #[test]
    fn unit_keys_distinguish_changed_mir_with_the_same_semantic_identity() {
        let without_storage = unit_with_optional_storage(false);
        let with_storage = unit_with_optional_storage(true);

        assert_eq!(without_storage.key(), with_storage.key());

        let without_storage = CodegenUnit::try_new(
            CodegenPartitionPolicy::NATIVE_BALANCED,
            codegen_partition_compatibility(),
            [without_storage],
        )
            .unwrap_or_else(|error| panic!("storage-free unit must validate: {error:?}"));

        let with_storage = CodegenUnit::try_new(
            CodegenPartitionPolicy::NATIVE_BALANCED,
            codegen_partition_compatibility(),
            [with_storage],
        )
            .unwrap_or_else(|error| panic!("storage-owning unit must validate: {error:?}"));

        assert_ne!(
            without_storage.key().content_identity(),
            with_storage.key().content_identity()
        );

        assert_ne!(without_storage.key(), with_storage.key());
    }

    #[test]
    fn units_publish_only_dependencies_outside_the_partition() {
        let first_mir = test_mir_unit(4);
        let second_mir = test_mir_unit_with_declaration(8, 1);
        let external = CodegenInstanceKey::non_generic(&test_mir_unit_with_declaration(12, 2));
        let first_key = CodegenInstanceKey::non_generic(&first_mir);
        let second_key = CodegenInstanceKey::non_generic(&second_mir);

        let Ok(first) = CodegenInstance::try_new(
            first_key.clone(),
            first_mir,
            [
                CodegenInstanceDependency::definition(second_key.clone()),
                CodegenInstanceDependency::definition(external.clone()),
            ],
        ) else {
            panic!("first test instance must validate");
        };

        let Ok(second) = CodegenInstance::try_new(
            second_key.clone(),
            second_mir,
            [CodegenInstanceDependency::definition(external.clone())],
        ) else {
            panic!("second test instance must validate");
        };

        let Ok(unit) = CodegenUnit::try_from_instances(
            CodegenPartitionPolicy::NATIVE_BALANCED,
            codegen_partition_compatibility(),
            [first, second],
        ) else {
            panic!("test unit must validate");
        };

        assert_eq!(unit.external_instances(), std::slice::from_ref(&external),);

        assert_eq!(
            unit.key().dependencies(&first_key),
            Some(
                [
                    CodegenInstanceDependency::definition(second_key),
                    CodegenInstanceDependency::definition(external.clone()),
                ]
                .as_slice(),
            ),
        );
    }

    fn unit_with_optional_storage(has_storage: bool) -> MirUnit {
        let bound = test_bound_unit_with_declaration(4, 0);
        let source = MirSourceAnchor::from(bound.key().source());

        let mut builder = MirUnitBuilder::for_bound(
            bound.identity(),
            MirUnitKind::Synchronous,
            test_mir_target(),
        );

        let entry = builder
            .push_block(source.clone(), MirBlockKind::Ordinary)
            .unwrap_or_else(|error| panic!("test block must validate: {error:?}"));

        if has_storage {
            builder
                .push_storage(source.clone(), MirStorageKind::Local, test_mir_type())
                .unwrap_or_else(|error| panic!("test storage must validate: {error:?}"));
        }

        builder
            .set_terminator(entry, source, MirTerminatorKind::Return(None))
            .unwrap_or_else(|error| panic!("test terminator must validate: {error:?}"));

        builder
            .finish(entry)
            .unwrap_or_else(|error| panic!("test MIR unit must validate: {error:?}"))
    }
}
