[package]
name = "bray-compilation"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-binder = { path = "../bray-binder" }
bray-bound-tree = { path = "../bray-bound-tree" }
bray-checker = { path = "../bray-checker" }
bray-codegen = { path = "../bray-codegen" }
bray-compiler-known = { path = "../bray-compiler-known" }
bray-declarations = { path = "../bray-declarations" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-emitter = { path = "../bray-emitter" }
bray-ir = { path = "../bray-ir" }
bray-lowering = { path = "../bray-lowering" }
bray-parser = { path = "../bray-parser" }
bray-package-interface = { path = "../bray-package-interface" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }
bray-syntax = { path = "../bray-syntax" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-target = { path = "../bray-target" }
rayon = "1.11.0"

[dev-dependencies]
bray-bound-tree = { path = "../bray-bound-tree", features = ["test-support"] }
bray-codegen = { path = "../bray-codegen", features = ["test-support"] }
bray-package-interface = { path = "../bray-package-interface", features = ["test-support"] }

[lints]
workspace = true
