use super::{
    CatalogDeclarationSurface, CatalogScopeLocation, CatalogSourceAnchor, CatalogSurfaceElement,
    CatalogTypeSurface, CompilerKnownCatalog, CompilerKnownDeclarationOwner,
    RecognizedStandardLibraryDeclarationIdentity, RecognizedStandardLibraryDeclarationOwner,
};

pub(super) fn render_catalog(catalog: &CompilerKnownCatalog, digest: &str) -> String {
    let mut output = String::from(
        "// @generated by `cargo xtask compiler-known generate`. Do not edit.\n\n\
         use std::borrow::Cow;\n\n\
         use bray_source::{TextRange, TextSize};\n\
         use bray_syntax::SyntaxKind;\n\n\
         use crate::{AvailabilityRule, CompilerKnownOperationRole, ImplementationHook, RepresentationRole};\n\n\
         use super::super::*;\n\n",
    );

    output.push_str(&format!(
        "pub const CATALOG_SOURCE_DIGEST: &str = {digest:?};\n\n"
    ));

    render_scopes(&mut output, catalog);
    render_declarations(&mut output, catalog);
    render_values(&mut output, catalog);
    render_roles(&mut output, catalog);
    render_recognized_scopes(&mut output, catalog);
    render_recognized_declarations(&mut output, catalog);
    render_surfaces(&mut output, catalog);

    output.push_str(
        "pub static COMPILER_KNOWN_CATALOG: CompilerKnownCatalog = CompilerKnownCatalog {\n\
             compiler_known_scopes: Cow::Borrowed(COMPILER_KNOWN_SCOPES),\n\
             compiler_known_declarations: Cow::Borrowed(COMPILER_KNOWN_DECLARATIONS),\n\
             compiler_known_values: Cow::Borrowed(COMPILER_KNOWN_VALUES),\n\
             role_registry: CompilerKnownCatalogRoleRegistry {\n\
                 representations: Cow::Borrowed(COMPILER_KNOWN_REPRESENTATION_ROLES),\n\
                 implementations: Cow::Borrowed(COMPILER_KNOWN_IMPLEMENTATION_ROLES),\n\
                 operations: Cow::Borrowed(COMPILER_KNOWN_OPERATION_ROLES),\n\
             },\n\
             recognized_scopes: Cow::Borrowed(RECOGNIZED_SCOPES),\n\
             recognized_declarations: Cow::Borrowed(RECOGNIZED_DECLARATIONS),\n\
             declaration_surfaces: Cow::Borrowed(DECLARATION_SURFACES),\n\
             type_surfaces: Cow::Borrowed(TYPE_SURFACES),\n\
         };\n",
    );

    output
}

fn render_roles(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str(
        "static COMPILER_KNOWN_REPRESENTATION_ROLES: &[CompilerKnownRepresentationBinding] = &[\n",
    );

    for binding in catalog.role_registry().representations() {
        let target = match binding.target() {
            super::CompilerKnownRepresentationTarget::Declaration(id) => format!(
                "CompilerKnownRepresentationTarget::Declaration(CompilerKnownDeclarationId::new({}))",
                id.raw()
            ),
            super::CompilerKnownRepresentationTarget::Value(id) => format!(
                "CompilerKnownRepresentationTarget::Value(CompilerKnownValueId::new({}))",
                id.raw()
            ),
        };

        output.push_str(&format!(
            "    CompilerKnownRepresentationBinding {{ role: RepresentationRole::{:?}, target: {} }},\n",
            binding.role(),
            target,
        ));
    }

    output.push_str("];\n\n");
    output.push_str(
        "static COMPILER_KNOWN_IMPLEMENTATION_ROLES: &[CompilerKnownImplementationBinding] = &[\n",
    );

    for binding in catalog.role_registry().implementations() {
        output.push_str(&format!(
            "    CompilerKnownImplementationBinding {{ hook: ImplementationHook::{:?}, declaration: CompilerKnownDeclarationId::new({}) }},\n",
            binding.hook(),
            binding.declaration().raw(),
        ));
    }

    output.push_str("];\n\n");

    output
        .push_str("static COMPILER_KNOWN_OPERATION_ROLES: &[CompilerKnownOperationBinding] = &[\n");

    for binding in catalog.role_registry().operations() {
        output.push_str(&format!(
            "    CompilerKnownOperationBinding {{ role: CompilerKnownOperationRole::{:?}, trait_definition: CompilerKnownDeclarationId::new({}), result_type_member: {}, fixed_result_type: {}, callable: {} }},\n",
            binding.role(),
            binding.trait_definition().raw(),
            render_optional_id(binding.result_type_member(), "CompilerKnownDeclarationId"),
            render_optional_id(binding.fixed_result_type(), "CompilerKnownDeclarationId"),
            render_optional_id(binding.callable(), "CompilerKnownDeclarationId"),
        ));
    }

    output.push_str("];\n\n");
}

fn render_scopes(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str("static COMPILER_KNOWN_SCOPES: &[CompilerKnownScopeDescriptor] = &[\n");

    for scope in catalog.compiler_known_scopes() {
        let location = match scope.location() {
            CatalogScopeLocation::Ambient => "CatalogScopeLocation::Ambient".to_owned(),
            CatalogScopeLocation::Module(path) => format!(
                "CatalogScopeLocation::Module(CatalogPath::from_static(&[{}]))",
                path.segments()
                    .map(|segment| format!("Cow::Borrowed({segment:?})"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        };

        output.push_str(&format!(
            "    CompilerKnownScopeDescriptor {{\n        id: CompilerKnownScopeId::new({}),\n        key: CompilerKnownScopeKey::from_static({:?}),\n        location: {},\n        declaration_ids: Cow::Borrowed(&[{}]),\n        value_ids: Cow::Borrowed(&[{}]),\n    }},\n",
            scope.id().raw(),
            scope.key().as_str(),
            location,
            render_ids(scope.declaration_ids(), "CompilerKnownDeclarationId"),
            render_ids(scope.value_ids(), "CompilerKnownValueId"),
        ));
    }

    output.push_str("];\n\n");
}

fn render_declarations(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str(
        "static COMPILER_KNOWN_DECLARATIONS: &[CompilerKnownDeclarationDescriptor] = &[\n",
    );

    for declaration in catalog.compiler_known_declarations() {
        let owner = match declaration.owner() {
            CompilerKnownDeclarationOwner::Scope(id) => format!(
                "CompilerKnownDeclarationOwner::Scope(CompilerKnownScopeId::new({}))",
                id.raw()
            ),
            CompilerKnownDeclarationOwner::Declaration(id) => format!(
                "CompilerKnownDeclarationOwner::Declaration(CompilerKnownDeclarationId::new({}))",
                id.raw()
            ),
        };

        output.push_str(&format!(
            "    CompilerKnownDeclarationDescriptor {{\n        id: CompilerKnownDeclarationId::new({}),\n        key: CompilerKnownDeclarationKey::from_static({:?}),\n        owner: {},\n        kind: CatalogDeclarationKind::{:?},\n        surface: {},\n        representation_role: {},\n        implementation_hook: {},\n        availability_rule: AvailabilityRule::{:?},\n    }},\n",
            declaration.id().raw(),
            declaration.key().as_str(),
            owner,
            declaration.kind(),
            render_declaration_surface(declaration.surface()),
            render_option("RepresentationRole", declaration.representation_role()),
            render_option("ImplementationHook", declaration.implementation_hook()),
            declaration.availability_rule(),
        ));
    }

    output.push_str("];\n\n");
}

fn render_values(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str("static COMPILER_KNOWN_VALUES: &[CompilerKnownValueDescriptor] = &[\n");

    for value in catalog.compiler_known_values() {
        output.push_str(&format!(
            "    CompilerKnownValueDescriptor {{\n        id: CompilerKnownValueId::new({}),\n        key: CompilerKnownValueKey::from_static({:?}),\n        owner_scope: CompilerKnownScopeId::new({}),\n        spelling: CatalogTokenSpelling::from_static({:?}),\n        type_surface: {},\n        representation_role: RepresentationRole::{:?},\n        availability_rule: AvailabilityRule::{:?},\n    }},\n",
            value.id().raw(),
            value.key().as_str(),
            value.owner_scope().raw(),
            value.spelling().as_str(),
            render_type_surface(value.type_surface()),
            value.representation_role(),
            value.availability_rule(),
        ));
    }

    output.push_str("];\n\n");
}

fn render_recognized_scopes(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str("static RECOGNIZED_SCOPES: &[RecognizedStandardLibraryScopeDescriptor] = &[\n");

    for scope in catalog.recognized_standard_library_scopes() {
        let segments = scope
            .path()
            .segments()
            .map(|segment| format!("Cow::Borrowed({segment:?})"))
            .collect::<Vec<_>>()
            .join(", ");

        output.push_str(&format!(
            "    RecognizedStandardLibraryScopeDescriptor {{\n        id: RecognizedStandardLibraryScopeId::new({}),\n        key: RecognizedStandardLibraryScopeKey::from_static({:?}),\n        path: CatalogPath::from_static(&[{}]),\n        declaration_ids: Cow::Borrowed(&[{}]),\n    }},\n",
            scope.id().raw(),
            scope.key().as_str(),
            segments,
            render_ids(
                scope.declaration_ids(),
                "RecognizedStandardLibraryDeclarationId"
            ),
        ));
    }

    output.push_str("];\n\n");
}

fn render_recognized_declarations(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str(
        "static RECOGNIZED_DECLARATIONS: &[RecognizedStandardLibraryDeclarationDescriptor] = &[\n",
    );

    for declaration in catalog.recognized_standard_library_declarations() {
        let owner = match declaration.owner() {
            RecognizedStandardLibraryDeclarationOwner::Scope(id) => format!(
                "RecognizedStandardLibraryDeclarationOwner::Scope(RecognizedStandardLibraryScopeId::new({}))",
                id.raw()
            ),
            RecognizedStandardLibraryDeclarationOwner::Declaration(id) => format!(
                "RecognizedStandardLibraryDeclarationOwner::Declaration(RecognizedStandardLibraryDeclarationId::new({}))",
                id.raw()
            ),
        };
        let identity = match declaration.identity() {
            RecognizedStandardLibraryDeclarationIdentity::Name(name) => {
                format!("RecognizedStandardLibraryDeclarationIdentity::name_from_static({name:?})")
            }
            RecognizedStandardLibraryDeclarationIdentity::Ordinal(ordinal) => {
                format!("RecognizedStandardLibraryDeclarationIdentity::Ordinal({ordinal})")
            }
        };

        output.push_str(&format!(
            "    RecognizedStandardLibraryDeclarationDescriptor {{\n        id: RecognizedStandardLibraryDeclarationId::new({}),\n        key: RecognizedStandardLibraryDeclarationKey::from_static({:?}),\n        owner: {},\n        identity: {},\n        kind: CatalogDeclarationKind::{:?},\n        surface: {},\n        implementation_hook: {},\n        availability_rule: AvailabilityRule::{:?},\n    }},\n",
            declaration.id().raw(),
            declaration.key().as_str(),
            owner,
            identity,
            declaration.kind(),
            render_declaration_surface(declaration.surface()),
            render_option("ImplementationHook", declaration.implementation_hook()),
            declaration.availability_rule(),
        ));
    }

    output.push_str("];\n\n");
}

fn render_surfaces(output: &mut String, catalog: &CompilerKnownCatalog) {
    output.push_str("static DECLARATION_SURFACES: &[CatalogDeclarationSurfaceSyntax] = &[\n");

    for surface in catalog.declaration_surfaces() {
        output.push_str(&format!(
            "    CatalogDeclarationSurfaceSyntax {{\n        surface: {},\n        kind: CatalogDeclarationKind::{:?},\n        elements: Cow::Borrowed(&[{}]),\n    }},\n",
            render_declaration_surface(surface.surface()),
            surface.kind(),
            render_surface_elements(surface.elements()),
        ));
    }

    output.push_str("];\n\nstatic TYPE_SURFACES: &[CatalogTypeSurfaceSyntax] = &[\n");

    for surface in catalog.type_surfaces() {
        output.push_str(&format!(
            "    CatalogTypeSurfaceSyntax {{\n        surface: {},\n        elements: Cow::Borrowed(&[{}]),\n    }},\n",
            render_type_surface(surface.surface()),
            render_surface_elements(surface.elements()),
        ));
    }

    output.push_str("];\n\n");
}

fn render_surface_elements(elements: &[CatalogSurfaceElement]) -> String {
    elements
        .iter()
        .map(|element| match element {
            CatalogSurfaceElement::EnterNode(kind) => {
                format!("CatalogSurfaceElement::EnterNode(SyntaxKind::{kind:?})")
            }
            CatalogSurfaceElement::Token(token) => format!(
                "CatalogSurfaceElement::Token(CatalogSurfaceToken::from_static(SyntaxKind::{:?}, {:?}))",
                token.kind(), token.spelling()
            ),
            CatalogSurfaceElement::ExitNode(kind) => {
                format!("CatalogSurfaceElement::ExitNode(SyntaxKind::{kind:?})")
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_ids<T>(ids: &[T], type_name: &str) -> String
where
    T: Copy + Into<u32>,
{
    ids.iter()
        .map(|id| format!("{type_name}::new({})", Into::<u32>::into(*id)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_optional_id<T>(id: Option<T>, type_name: &str) -> String
where
    T: Copy + Into<u32>,
{
    id.map_or_else(
        || "None".to_owned(),
        |id| format!("Some({type_name}::new({}))", Into::<u32>::into(id)),
    )
}

fn render_declaration_surface(surface: CatalogDeclarationSurface) -> String {
    format!(
        "CatalogDeclarationSurface({})",
        render_anchor(surface.anchor())
    )
}

fn render_type_surface(surface: CatalogTypeSurface) -> String {
    format!("CatalogTypeSurface({})", render_anchor(surface.anchor()))
}

fn render_anchor(anchor: CatalogSourceAnchor) -> String {
    format!(
        "CatalogSourceAnchor {{ source: CatalogSourceId::new({}), range: TextRange::new(TextSize::new({}), TextSize::new({})) }}",
        anchor.source().raw(),
        anchor.range().start().bytes(),
        anchor.range().end().bytes(),
    )
}

fn render_option<T>(type_name: &str, value: Option<T>) -> String
where
    T: std::fmt::Debug,
{
    match value {
        Some(value) => format!("Some({type_name}::{value:?})"),
        None => "None".to_owned(),
    }
}
