[package]
name = "bray-lowering"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-bound-tree = { path = "../bray-bound-tree" }

[dev-dependencies]
bray-declarations = { path = "../bray-declarations" }
bray-parser = { path = "../bray-parser" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }

[lints]
workspace = true
