[package]
name = "bray-lowering"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-bound-tree = { path = "../bray-bound-tree" }
bray-execution = { path = "../bray-execution" }
bray-ir = { path = "../bray-ir" }
bray-symbols = { path = "../bray-symbols" }

[dev-dependencies]
bray-symbols = { path = "../bray-symbols", features = ["test-support"] }
bray-testing = { path = "../bray-testing", features = ["bound-unit"] }

[lints]
workspace = true
