[package]
name = "bray-lowering"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-bound-tree = { path = "../bray-bound-tree" }
bray-compiler-known = { path = "../bray-compiler-known" }
bray-declarations = { path = "../bray-declarations" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-ir = { path = "../bray-ir" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }

[dev-dependencies]
bray-symbols = { path = "../bray-symbols", features = ["test-support"] }
bray-testing = { path = "../bray-testing", features = ["mir-unit"] }

[lints]
workspace = true
