[package]
name = "bray-fuzz"
version = "0.0.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]
resolver = "3"

[dependencies]
bray-parser = { path = "../crates/bray-parser" }
bray-source = { path = "../crates/bray-source" }
bray-syntax = { path = "../crates/bray-syntax" }
bray-testing = { path = "../crates/bray-testing" }
libfuzzer-sys = "0.4"

[[bin]]
name = "lexer_parser"
path = "fuzz_targets/lexer_parser.rs"
test = false
doc = false
bench = false
