[package]
name = "bray-runtime-observation"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[features]
performance-observation = []

[dependencies]
bray-runtime-abi = { path = "../bray-runtime-abi" }

[lints]
workspace = true
