[package]
name = "bray-runtime"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bray-platform = { path = "../bray-platform" }
bray-platform-abi = { path = "../bray-platform-abi" }
bray-runtime-abi = { path = "../bray-runtime-abi" }
bray-runtime-model = { path = "../bray-runtime-model" }

[dev-dependencies]
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
