[package]
name = "bray-runtime"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bray-platform = { path = "../bray-platform" }
bray-runtime-interface = { path = "../bray-runtime-interface" }

[lints]
workspace = true
