[package]
name = "bray-runtime"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[features]
test-output = ["bray-platform/test-output"]

[dependencies]
bray-platform = {
    path = "../bray-platform",
    default-features = false,
    features = ["clock", "event", "memory", "thread"],
}
bray-runtime-abi = { path = "../bray-runtime-abi" }
bray-runtime-model = { path = "../bray-runtime-model" }
triomphe = { version = "0.1.16", default-features = false, features = ["std"] }
scoped-tls = "1.0.1"
trybox = { version = "0.1.2", default-features = false }

[dev-dependencies]
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
