[package]
name = "bray-messages"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-diagnostics = { path = "../bray-diagnostics" }
bray-profile = { path = "../bray-profile" }
bray-source = { path = "../bray-source" }
bray-syntax = { path = "../bray-syntax" }

[lints]
workspace = true
