[package]
name = "bray-package-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
test-support = []

[dependencies]
blake3 = "1"
bray-base = { path = "../bray-base" }
bray-bound-tree = { path = "../bray-bound-tree" }
bray-compiler-known = { path = "../bray-compiler-known" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-ir = { path = "../bray-ir" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }

[dev-dependencies]
bray-messages = { path = "../bray-messages" }

[lints]
workspace = true
