[package]
name = "bray-declarations"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-diagnostics = { path = "../bray-diagnostics" }
bray-source = { path = "../bray-source" }
bray-syntax = { path = "../bray-syntax" }

[dev-dependencies]
bray-parser = { path = "../bray-parser" }
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
