[package]
name = "bray-runtime-adapter"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[features]
callback = []
cancellation = []
event = []
host = []
scheduler = []
test-host = [
    "callback",
    "cancellation",
    "dep:bray-platform",
    "bray-platform/test-output",
    "dep:bray-platform-abi-support",
    "dep:bray-source",
    "dep:bray-test-protocol",
    "event",
    "host",
    "bray-runtime/test-output",
    "scheduler",
]

[dependencies]
bray-platform = {
    path = "../bray-platform",
    optional = true,
    default-features = false,
}
bray-platform-abi-support = { path = "../bray-platform-abi-support", optional = true }
bray-runtime = { path = "../bray-runtime" }
bray-runtime-abi = { path = "../bray-runtime-abi" }
bray-source = { path = "../bray-source", optional = true }
bray-test-protocol = { path = "../bray-test-protocol", optional = true }

[lints]
workspace = true
