use std::fmt::Write;
use std::path::{Path, PathBuf};

use bray_base::lowercase_hex;
use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::text::normalize_line_endings;
use crate::workspace;

const VERSION: &str = "17.0.0";
const GENERATOR_REVISION: u32 = 2;
const INPUT_ROOT: &str = "standard-library/targets/unicode/17.0.0";
const TABLE_OUTPUT: &str = "standard-library/std/src/runtime/character/unicode_tables.bray";
const METADATA_OUTPUT: &str = "standard-library/targets/unicode/metadata.json";
const RANGES_PER_SEGMENT: usize = 10;

pub(super) fn run(mut arguments: impl Iterator<Item = String>) -> Result<(), String> {
    if arguments.next().as_deref() != Some("generate") {
        return Err("expected `unicode generate [--check]`".to_owned());
    }

    let check = match arguments.next().as_deref() {
        None => false,
        Some("--check") => true,
        Some(argument) => return Err(format!("unexpected argument: {argument}")),
    };

    crate::command::reject_trailing_argument(arguments)?;

    generate(check)
}

pub(super) fn verify() -> Result<(), String> {
    generate(true)
}

fn generate(check: bool) -> Result<(), String> {
    let root = workspace::root()?;
    let inputs = load_inputs(&root)?;
    let alphabetic = property_ranges(&inputs[0].contents, &["Alphabetic"])?;
    let whitespace = property_ranges(&inputs[1].contents, &["White_Space"])?;
    let numeric = property_ranges(&inputs[2].contents, &["Decimal", "Digit", "Numeric"])?;

    let table = render_tables(&inputs, &alphabetic, &numeric, &whitespace)?;
    let metadata = render_metadata(&inputs)?;

    let outputs = [
        (root.join(TABLE_OUTPUT), table.into_bytes()),
        (root.join(METADATA_OUTPUT), metadata),
    ];

    if check {
        check_outputs(&outputs)
    } else {
        synchronize_outputs(&outputs)
    }
}

struct Input {
    name: &'static str,
    contents: String,
    digest: String,
}

fn load_inputs(root: &Path) -> Result<[Input; 3], String> {
    [
        "DerivedCoreProperties.txt",
        "PropList.txt",
        "DerivedNumericType.txt",
    ]
    .map(|name| load_input(root, name))
    .into_iter()
    .collect::<Result<Vec<_>, _>>()?
    .try_into()
    .map_err(|_| "Unicode input inventory is incomplete".to_owned())
}

fn load_input(root: &Path, name: &'static str) -> Result<Input, String> {
    let path = root.join(INPUT_ROOT).join(name);
    let bytes = std::fs::read(&path).map_err(|error| workspace::io_error("read", &path, error))?;

    let contents = String::from_utf8(normalize_line_endings(&bytes).into_owned())
        .map_err(|error| format!("{} is not UTF-8: {error}", path.display()))?;

    let digest = lowercase_hex(&Sha256::digest(contents.as_bytes()));

    Ok(Input {
        name,
        contents,
        digest,
    })
}

fn property_ranges(contents: &str, properties: &[&str]) -> Result<Vec<(u32, u32)>, String> {
    let mut ranges = Vec::new();

    for line in contents.lines() {
        let definition = line.split('#').next().unwrap_or_default().trim();

        if definition.is_empty() {
            continue;
        }

        let Some((range, property)) = definition.split_once(';') else {
            return Err(format!("invalid Unicode data line: {line}"));
        };

        if !properties.contains(&property.trim()) {
            continue;
        }

        ranges.push(parse_range(range.trim())?);
    }

    ranges.sort_unstable();

    let mut merged: Vec<(u32, u32)> = Vec::with_capacity(ranges.len());

    for (start, end) in ranges {
        if let Some((_, previous_end)) = merged.last_mut()
            && start <= previous_end.saturating_add(1)
        {
            *previous_end = (*previous_end).max(end);
        } else {
            merged.push((start, end));
        }
    }

    Ok(merged)
}

fn parse_range(value: &str) -> Result<(u32, u32), String> {
    let (start, end) = value.split_once("..").unwrap_or((value, value));

    let start = u32::from_str_radix(start, 16)
        .map_err(|error| format!("invalid Unicode range start {start}: {error}"))?;

    let end = u32::from_str_radix(end, 16)
        .map_err(|error| format!("invalid Unicode range end {end}: {error}"))?;

    if start > end || end > 0x10_ffff {
        return Err(format!("invalid Unicode range {value}"));
    }

    Ok((start, end))
}

fn render_tables(
    inputs: &[Input],
    alphabetic: &[(u32, u32)],
    numeric: &[(u32, u32)],
    whitespace: &[(u32, u32)],
) -> Result<String, String> {
    let mut output = String::new();

    writeln!(
        output,
        "// Generated by `cargo xtask standard-library unicode generate`."
    )
    .map_err(|error| error.to_string())?;

    writeln!(
        output,
        "// Unicode {VERSION}, generator revision {GENERATOR_REVISION}."
    )
    .map_err(|error| error.to_string())?;

    for input in inputs {
        writeln!(output, "// {} SHA-256 {}.", input.name, input.digest)
            .map_err(|error| error.to_string())?;
    }

    output.push_str("\ntrusted internal module std.runtime.character;\n\n");
    render_property(&mut output, "alphabetic", alphabetic)?;
    render_property(&mut output, "numeric", numeric)?;
    render_property(&mut output, "whitespace", whitespace)?;
    render_range_search(&mut output);
    render_range_decoder(&mut output);
    output.pop();

    Ok(output)
}

fn render_property(output: &mut String, name: &str, ranges: &[(u32, u32)]) -> Result<(), String> {
    let segments = ranges.chunks(RANGES_PER_SEGMENT).collect::<Vec<_>>();

    writeln!(
        output,
        "trusted internal func {name}(pos value: u32) -> bool\n{{"
    )
    .map_err(|error| error.to_string())?;

    render_segment_selection(output, &segments, 1)?;
    output.push_str("}\n\n");

    Ok(())
}

fn render_segment_selection(
    output: &mut String,
    segments: &[&[(u32, u32)]],
    depth: usize,
) -> Result<(), String> {
    let indentation = "    ".repeat(depth);

    if segments.is_empty() {
        writeln!(output, "{indentation}return false;").map_err(|error| error.to_string())?;

        return Ok(());
    }

    let middle = segments.len() / 2;
    let segment = segments[middle];
    let start = segment.first().map_or(0, |range| range.0);
    let end = segment.last().map_or(0, |range| range.1);

    writeln!(
        output,
        "{indentation}if value < 0x{start:x}\n{indentation}{{"
    )
    .map_err(|error| error.to_string())?;

    render_segment_selection(output, &segments[..middle], depth + 1)?;
    writeln!(output, "{indentation}}}").map_err(|error| error.to_string())?;

    writeln!(
        output,
        "\n{indentation}if value > 0x{end:x}\n{indentation}{{"
    )
    .map_err(|error| error.to_string())?;

    render_segment_selection(output, &segments[middle + 1..], depth + 1)?;
    writeln!(output, "{indentation}}}").map_err(|error| error.to_string())?;

    let encoded = encode_ranges(segment);

    let inline = format!(
        "{indentation}return trusted contains_encoded_ranges(value, \"{encoded}\", count = {});",
        segment.len(),
    );

    if inline.len() <= 120 {
        writeln!(output, "\n{inline}").map_err(|error| error.to_string())
    } else {
        writeln!(
            output,
            "\n{indentation}return trusted contains_encoded_ranges(\n{indentation}    value,\n{indentation}    \"{encoded}\",\n{indentation}    count = {},\n{indentation});",
            segment.len(),
        )
        .map_err(|error| error.to_string())
    }
}

fn render_range_search(output: &mut String) {
    output.push_str(
        r#"trusted internal func contains_encoded_ranges(pos value: u32, pos encoded: string, pos count: usize) -> bool
{
    let data: &[u8] = encoded.as_bytes();

    let mut first: usize = 0;
    let mut remaining: usize = count;

    while first < remaining
    {
        let middle: usize = first + (remaining - first) / 2;
        let range: usize = middle * 8;
        let start: u32 = decode_range_value(data, offset = range);
        let end: u32 = decode_range_value(data, offset = range + 4);

        if value < start
        {
            remaining = middle;
        }
        else if value > end
        {
            first = middle + 1;
        }
        else
        {
            return true;
        }
    }

    return false;
}

"#,
    );
}

fn encode_ranges(ranges: &[(u32, u32)]) -> String {
    ranges
        .iter()
        .flat_map(|(start, end)| [*start, *end])
        .flat_map(|value| [18, 12, 6, 0].map(|shift| encode_range_digit((value >> shift) & 0x3f)))
        .collect()
}

fn encode_range_digit(value: u32) -> char {
    match value {
        0..=25 => char::from_u32(u32::from(b'A') + value),
        26..=51 => char::from_u32(u32::from(b'a') + value - 26),
        52..=61 => char::from_u32(u32::from(b'0') + value - 52),
        62 => Some('-'),
        63 => Some('_'),
        _ => None,
    }
    .unwrap_or_else(|| panic!("six-bit range digit must have an encoding"))
}

fn render_range_decoder(output: &mut String) {
    output.push_str(
        r#"internal func decode_range_value(pos data: &[u8], pos offset: usize) -> u32
{
    return decode_range_digit(data[offset]) << 18 | decode_range_digit(data[offset + 1]) << 12 | decode_range_digit(
        data[offset + 2]
    ) << 6 | decode_range_digit(data[offset + 3]);
}

internal func decode_range_digit(pos value: u8) -> u32
{
    if value >= 65 && value <= 90
    {
        return (value - 65) as u32;
    }

    if value >= 97 && value <= 122
    {
        return (value - 97 + 26) as u32;
    }

    if value >= 48 && value <= 57
    {
        return (value - 48 + 52) as u32;
    }

    assert(value == 45 || value == 95, "generated Unicode range data must use the range alphabet");

    if value == 45
    {
        return 62;
    }

    return 63;
}

"#,
    );
}

#[derive(Serialize)]
struct Metadata<'a> {
    format: u32,
    unicode_version: &'a str,
    generator_revision: u32,
    inputs: Vec<MetadataInput<'a>>,
}

#[derive(Serialize)]
struct MetadataInput<'a> {
    name: &'a str,
    sha256: &'a str,
}

fn render_metadata(inputs: &[Input]) -> Result<Vec<u8>, String> {
    let metadata = Metadata {
        format: 1,
        unicode_version: VERSION,
        generator_revision: GENERATOR_REVISION,
        inputs: inputs
            .iter()
            .map(|input| MetadataInput {
                name: input.name,
                sha256: &input.digest,
            })
            .collect(),
    };

    let mut output = serde_json::to_vec_pretty(&metadata).map_err(|error| error.to_string())?;
    output.push(b'\n');

    Ok(output)
}

fn check_outputs(outputs: &[(PathBuf, Vec<u8>)]) -> Result<(), String> {
    let stale = outputs
        .iter()
        .filter_map(|(path, expected)| match std::fs::read(path) {
            Ok(actual) if normalize_line_endings(&actual) == normalize_line_endings(expected) => {
                None
            }
            _ => Some(path.display().to_string()),
        })
        .collect::<Vec<_>>();

    if stale.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "generated Unicode output is stale: {}",
            stale.join(", ")
        ))
    }
}

fn synchronize_outputs(outputs: &[(PathBuf, Vec<u8>)]) -> Result<(), String> {
    for (path, contents) in outputs {
        let parent = path
            .parent()
            .ok_or_else(|| format!("{} has no parent", path.display()))?;

        std::fs::create_dir_all(parent)
            .map_err(|error| workspace::io_error("create", parent, error))?;

        if std::fs::read(path).ok().as_deref() != Some(contents) {
            std::fs::write(path, contents)
                .map_err(|error| workspace::io_error("write", path, error))?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{encode_ranges, parse_range, property_ranges};

    #[test]
    fn range_encoding_is_fixed_width_and_uses_the_source_safe_alphabet() {
        assert_eq!(encode_ranges(&[(0, 0x10_ffff)]), "AAAAEP__");
    }

    #[test]
    fn selected_properties_are_parsed_and_adjacent_ranges_are_merged() {
        let ranges = property_ranges(
            "0041..005A ; Alphabetic # letters\n005B ; Other\n0061..007A ; Alphabetic\n005F..0060 ; Alphabetic\n",
            &["Alphabetic"],
        )
        .unwrap_or_else(|error| panic!("properties must parse: {error}"));

        assert_eq!(ranges, [(0x41, 0x5a), (0x5f, 0x7a)]);
    }

    #[test]
    fn scalar_and_interval_ranges_are_supported() {
        assert_eq!(parse_range("0020"), Ok((0x20, 0x20)));
        assert_eq!(parse_range("0030..0039"), Ok((0x30, 0x39)));
    }
}
