[package]
name = "bray-bound-tree"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-declarations = { path = "../bray-declarations" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }

[dev-dependencies]
bray-syntax = { path = "../bray-syntax" }

[lints]
workspace = true
