[package]
name = "bray-checker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-bound-tree = { path = "../bray-bound-tree" }
bray-compiler-known = { path = "../bray-compiler-known" }
bray-declarations = { path = "../bray-declarations" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }
rustc_apfloat = "0.2.3"

[dev-dependencies]
bray-bound-tree = { path = "../bray-bound-tree", features = ["test-support"] }
bray-parser = { path = "../bray-parser" }
bray-symbols = { path = "../bray-symbols", features = ["test-support"] }
bray-syntax = { path = "../bray-syntax" }
bray-testing = { path = "../bray-testing" }
bray-target = { path = "../bray-target", features = ["test-support"] }

[lints]
workspace = true
