[package]
name = "bray-checker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-bound-tree = { path = "../bray-bound-tree" }
bray-compiler-known = { path = "../bray-compiler-known" }
bray-declarations = { path = "../bray-declarations" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }

[dev-dependencies]
bray-parser = { path = "../bray-parser" }
bray-symbols = { path = "../bray-symbols", features = ["test-support"] }

[lints]
workspace = true
