/* Generated by cargo xtask standard-library os-bindings generate. */
/* SDK authority: Debian 13 stable sysroot Debian 13, Linux 6.12, glibc 2.41 */
/* Complete input SHA-256: 458c4fb1a6f53375106d5617948237df32fa19b3595c024c625179c18fdb0a91 */

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <dlfcn.h>
#include <fcntl.h>
#include <linux/version.h>
#include <netdb.h>
#include <netinet/ip.h>
#include <pthread.h>
#include <signal.h>
#include <sys/inotify.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>

_Static_assert(LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0) && LINUX_VERSION_CODE < KERNEL_VERSION(6, 13, 0), "Linux SDK revision");
_Static_assert(__GLIBC__ == 2 && __GLIBC_MINOR__ == 41, "glibc SDK revision");
_Static_assert(sizeof(clockid_t) == 4, "clockid_t size");
_Static_assert(_Alignof(clockid_t) == 4, "clockid_t alignment");
_Static_assert(((clockid_t)-1 < (clockid_t)0) == 1, "clockid_t signedness");
_Static_assert(sizeof(off_t) == 8, "off_t size");
_Static_assert(_Alignof(off_t) == 8, "off_t alignment");
_Static_assert(((off_t)-1 < (off_t)0) == 1, "off_t signedness");
_Static_assert(sizeof(pthread_t) == 8, "pthread_t size");
_Static_assert(_Alignof(pthread_t) == 8, "pthread_t alignment");
_Static_assert(((pthread_t)-1 < (pthread_t)0) == 0, "pthread_t signedness");
_Static_assert(sizeof(time_t) == 8, "time_t size");
_Static_assert(_Alignof(time_t) == 8, "time_t alignment");
_Static_assert(((time_t)-1 < (time_t)0) == 1, "time_t signedness");
_Static_assert((AT_FDCWD) == -100, "AT_FDCWD value");
_Static_assert((CLOCK_MONOTONIC) == 1, "CLOCK_MONOTONIC value");
_Static_assert((MAP_ANONYMOUS) == 32, "MAP_ANONYMOUS value");
_Static_assert((MAP_PRIVATE) == 2, "MAP_PRIVATE value");
_Static_assert((MAP_SHARED) == 1, "MAP_SHARED value");
_Static_assert((O_CLOEXEC) == 524288, "O_CLOEXEC value");
_Static_assert((O_RDONLY) == 0, "O_RDONLY value");
_Static_assert((O_RDWR) == 2, "O_RDWR value");
_Static_assert((O_WRONLY) == 1, "O_WRONLY value");
_Static_assert((PROT_EXEC) == 4, "PROT_EXEC value");
_Static_assert((PROT_NONE) == 0, "PROT_NONE value");
_Static_assert((PROT_READ) == 1, "PROT_READ value");
_Static_assert((PROT_WRITE) == 2, "PROT_WRITE value");
_Static_assert(sizeof(struct addrinfo *) == sizeof(void *), "struct addrinfo pointer representation");
_Static_assert(_Alignof(struct inotify_event) == 4, "struct inotify_event alignment");
_Static_assert(offsetof(struct inotify_event, wd) == 0, "struct inotify_event.wd offset");
_Static_assert(sizeof(((struct inotify_event *)0)->wd) == sizeof(int), "struct inotify_event.wd type");
_Static_assert(offsetof(struct inotify_event, mask) == 4, "struct inotify_event.mask offset");
_Static_assert(sizeof(((struct inotify_event *)0)->mask) == sizeof(uint32_t), "struct inotify_event.mask type");
_Static_assert(offsetof(struct inotify_event, cookie) == 8, "struct inotify_event.cookie offset");
_Static_assert(sizeof(((struct inotify_event *)0)->cookie) == sizeof(uint32_t), "struct inotify_event.cookie type");
_Static_assert(offsetof(struct inotify_event, len) == 12, "struct inotify_event.len offset");
_Static_assert(sizeof(((struct inotify_event *)0)->len) == sizeof(uint32_t), "struct inotify_event.len type");
_Static_assert(offsetof(struct inotify_event, name) == 16, "struct inotify_event.name offset");
_Static_assert(sizeof(((struct inotify_event *)0)->name[0]) == sizeof(char), "struct inotify_event.name element");
_Static_assert(sizeof(struct iphdr) == 20, "struct iphdr size");
_Static_assert(_Alignof(struct iphdr) == 4, "struct iphdr alignment");
_Static_assert(offsetof(struct iphdr, tos) == 1, "struct iphdr.tos offset");
_Static_assert(sizeof(((struct iphdr *)0)->tos) == sizeof(uint8_t), "struct iphdr.tos type");
_Static_assert(offsetof(struct iphdr, tot_len) == 2, "struct iphdr.tot_len offset");
_Static_assert(sizeof(((struct iphdr *)0)->tot_len) == sizeof(uint16_t), "struct iphdr.tot_len type");
_Static_assert(offsetof(struct iphdr, id) == 4, "struct iphdr.id offset");
_Static_assert(sizeof(((struct iphdr *)0)->id) == sizeof(uint16_t), "struct iphdr.id type");
_Static_assert(offsetof(struct iphdr, frag_off) == 6, "struct iphdr.frag_off offset");
_Static_assert(sizeof(((struct iphdr *)0)->frag_off) == sizeof(uint16_t), "struct iphdr.frag_off type");
_Static_assert(offsetof(struct iphdr, ttl) == 8, "struct iphdr.ttl offset");
_Static_assert(sizeof(((struct iphdr *)0)->ttl) == sizeof(uint8_t), "struct iphdr.ttl type");
_Static_assert(offsetof(struct iphdr, protocol) == 9, "struct iphdr.protocol offset");
_Static_assert(sizeof(((struct iphdr *)0)->protocol) == sizeof(uint8_t), "struct iphdr.protocol type");
_Static_assert(offsetof(struct iphdr, check) == 10, "struct iphdr.check offset");
_Static_assert(sizeof(((struct iphdr *)0)->check) == sizeof(uint16_t), "struct iphdr.check type");
_Static_assert(offsetof(struct iphdr, saddr) == 12, "struct iphdr.saddr offset");
_Static_assert(sizeof(((struct iphdr *)0)->saddr) == sizeof(uint32_t), "struct iphdr.saddr type");
_Static_assert(offsetof(struct iphdr, daddr) == 16, "struct iphdr.daddr offset");
_Static_assert(sizeof(((struct iphdr *)0)->daddr) == sizeof(uint32_t), "struct iphdr.daddr type");
_Static_assert(sizeof(pthread_attr_t *) == sizeof(void *), "pthread_attr_t pointer representation");
_Static_assert(sizeof(pthread_mutex_t) == 48, "pthread_mutex_t size");
_Static_assert(_Alignof(pthread_mutex_t) == 8, "pthread_mutex_t alignment");
_Static_assert(sizeof(union sigval) == 8, "union sigval size");
_Static_assert(_Alignof(union sigval) == 8, "union sigval alignment");
_Static_assert(offsetof(union sigval, sival_int) == 0, "union sigval.sival_int offset");
_Static_assert(sizeof(((union sigval *)0)->sival_int) == sizeof(int), "union sigval.sival_int type");
_Static_assert(offsetof(union sigval, sival_ptr) == 0, "union sigval.sival_ptr offset");
_Static_assert(sizeof(((union sigval *)0)->sival_ptr) == sizeof(void *), "union sigval.sival_ptr type");
_Static_assert(sizeof(struct timespec) == 16, "struct timespec size");
_Static_assert(_Alignof(struct timespec) == 8, "struct timespec alignment");
_Static_assert(offsetof(struct timespec, tv_sec) == 0, "struct timespec.tv_sec offset");
_Static_assert(sizeof(((struct timespec *)0)->tv_sec) == sizeof(time_t), "struct timespec.tv_sec type");
_Static_assert(offsetof(struct timespec, tv_nsec) == 8, "struct timespec.tv_nsec offset");
_Static_assert(sizeof(((struct timespec *)0)->tv_nsec) == sizeof(long), "struct timespec.tv_nsec type");
typedef int (*bray_probe_ClockGetTime)(clockid_t, struct timespec *);
_Static_assert(__builtin_types_compatible_p(int (*)(clockid_t, struct timespec *), bray_probe_ClockGetTime), "int (*)(clockid_t, struct timespec *) callback");
typedef void * (*bray_probe_ThreadStartRoutine)(void *);
_Static_assert(__builtin_types_compatible_p(void *(*)(void *), bray_probe_ThreadStartRoutine), "void *(*)(void *) callback");
_Static_assert(sizeof(int) == 4, "InotifyEvent.watch_descriptor Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "InotifyEvent.watch_descriptor Bray integer signedness");
_Static_assert(sizeof(uint32_t) == 4, "InotifyEvent.mask Bray integer size");
_Static_assert(((uint32_t)-1 < (uint32_t)0) == 0, "InotifyEvent.mask Bray integer signedness");
_Static_assert(sizeof(uint32_t) == 4, "InotifyEvent.cookie Bray integer size");
_Static_assert(((uint32_t)-1 < (uint32_t)0) == 0, "InotifyEvent.cookie Bray integer signedness");
_Static_assert(sizeof(uint32_t) == 4, "InotifyEvent.length Bray integer size");
_Static_assert(((uint32_t)-1 < (uint32_t)0) == 0, "InotifyEvent.length Bray integer signedness");
_Static_assert(sizeof(char) == 1, "InotifyEvent.name Bray integer size");
_Static_assert(sizeof(uint8_t) == 1, "IpHeader backing storage Bray integer size");
_Static_assert(((uint8_t)-1 < (uint8_t)0) == 0, "IpHeader backing storage Bray integer signedness");
_Static_assert(sizeof(uint8_t) == 1, "IpHeader.type_of_service Bray integer size");
_Static_assert(((uint8_t)-1 < (uint8_t)0) == 0, "IpHeader.type_of_service Bray integer signedness");
_Static_assert(sizeof(uint16_t) == 2, "IpHeader.total_length Bray integer size");
_Static_assert(((uint16_t)-1 < (uint16_t)0) == 0, "IpHeader.total_length Bray integer signedness");
_Static_assert(sizeof(uint16_t) == 2, "IpHeader.identification Bray integer size");
_Static_assert(((uint16_t)-1 < (uint16_t)0) == 0, "IpHeader.identification Bray integer signedness");
_Static_assert(sizeof(uint16_t) == 2, "IpHeader.fragment_offset Bray integer size");
_Static_assert(((uint16_t)-1 < (uint16_t)0) == 0, "IpHeader.fragment_offset Bray integer signedness");
_Static_assert(sizeof(uint8_t) == 1, "IpHeader.time_to_live Bray integer size");
_Static_assert(((uint8_t)-1 < (uint8_t)0) == 0, "IpHeader.time_to_live Bray integer signedness");
_Static_assert(sizeof(uint8_t) == 1, "IpHeader.protocol Bray integer size");
_Static_assert(((uint8_t)-1 < (uint8_t)0) == 0, "IpHeader.protocol Bray integer signedness");
_Static_assert(sizeof(uint16_t) == 2, "IpHeader.checksum Bray integer size");
_Static_assert(((uint16_t)-1 < (uint16_t)0) == 0, "IpHeader.checksum Bray integer signedness");
_Static_assert(sizeof(uint32_t) == 4, "IpHeader.source Bray integer size");
_Static_assert(((uint32_t)-1 < (uint32_t)0) == 0, "IpHeader.source Bray integer signedness");
_Static_assert(sizeof(uint32_t) == 4, "IpHeader.destination Bray integer size");
_Static_assert(((uint32_t)-1 < (uint32_t)0) == 0, "IpHeader.destination Bray integer signedness");
_Static_assert(sizeof(int) == 4, "SignalValue.integer Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "SignalValue.integer Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "SignalValue.pointer Bray pointer representation");
_Static_assert(sizeof(time_t) == 8, "Timespec.seconds Bray integer size");
_Static_assert(((time_t)-1 < (time_t)0) == 1, "Timespec.seconds Bray integer signedness");
_Static_assert(sizeof(long) == 8, "Timespec.nanoseconds Bray integer size");
_Static_assert(((long)-1 < (long)0) == 1, "Timespec.nanoseconds Bray integer signedness");
_Static_assert(sizeof(clockid_t) == 4, "ClockGetTime parameter clock Bray integer size");
_Static_assert(((clockid_t)-1 < (clockid_t)0) == 1, "ClockGetTime parameter clock Bray integer signedness");
_Static_assert(sizeof(struct timespec *) == sizeof(void *), "ClockGetTime parameter time Bray pointer representation");
_Static_assert(sizeof(int) == 4, "ClockGetTime result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "ClockGetTime result Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "ThreadStartRoutine parameter context Bray pointer representation");
_Static_assert(sizeof(void *) == sizeof(void *), "ThreadStartRoutine result Bray pointer representation");
_Static_assert(sizeof(clockid_t) == 4, "clock_gettime parameter clock Bray integer size");
_Static_assert(((clockid_t)-1 < (clockid_t)0) == 1, "clock_gettime parameter clock Bray integer signedness");
_Static_assert(sizeof(struct timespec *) == sizeof(void *), "clock_gettime parameter time Bray pointer representation");
_Static_assert(sizeof(int) == 4, "clock_gettime result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "clock_gettime result Bray integer signedness");
_Static_assert(sizeof(int) == 4, "close parameter descriptor Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "close parameter descriptor Bray integer signedness");
_Static_assert(sizeof(int) == 4, "close result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "close result Bray integer signedness");
_Static_assert(sizeof(int *) == sizeof(void *), "errno_location result Bray pointer representation");
_Static_assert(sizeof(void *) == sizeof(void *), "mmap parameter address Bray pointer representation");
_Static_assert(sizeof(size_t) == 8, "mmap parameter length Bray integer size");
_Static_assert(((size_t)-1 < (size_t)0) == 0, "mmap parameter length Bray integer signedness");
_Static_assert(sizeof(int) == 4, "mmap parameter protection Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "mmap parameter protection Bray integer signedness");
_Static_assert(sizeof(int) == 4, "mmap parameter flags Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "mmap parameter flags Bray integer signedness");
_Static_assert(sizeof(int) == 4, "mmap parameter descriptor Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "mmap parameter descriptor Bray integer signedness");
_Static_assert(sizeof(off_t) == 8, "mmap parameter offset Bray integer size");
_Static_assert(((off_t)-1 < (off_t)0) == 1, "mmap parameter offset Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "mmap result Bray pointer representation");
_Static_assert(sizeof(void *) == sizeof(void *), "munmap parameter address Bray pointer representation");
_Static_assert(sizeof(size_t) == 8, "munmap parameter length Bray integer size");
_Static_assert(((size_t)-1 < (size_t)0) == 0, "munmap parameter length Bray integer signedness");
_Static_assert(sizeof(int) == 4, "munmap result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "munmap result Bray integer signedness");
_Static_assert(sizeof(const char *) == sizeof(void *), "open parameter path Bray pointer representation");
_Static_assert(sizeof(int) == 4, "open parameter flags Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "open parameter flags Bray integer signedness");
_Static_assert(sizeof(int) == 4, "open result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "open result Bray integer signedness");
_Static_assert(sizeof(pthread_t *) == sizeof(void *), "pthread_create parameter thread Bray pointer representation");
_Static_assert(sizeof(const pthread_attr_t *) == sizeof(void *), "pthread_create parameter attributes Bray pointer representation");
_Static_assert(__builtin_types_compatible_p(void *(*)(void *), void *(*)(void *)), "pthread_create parameter entry Bray named type");
_Static_assert(sizeof(void *) == sizeof(void *), "pthread_create parameter context Bray pointer representation");
_Static_assert(sizeof(int) == 4, "pthread_create result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "pthread_create result Bray integer signedness");
_Static_assert(sizeof(char **) == sizeof(void *), "ENVIRON Bray pointer representation");
typedef int (*bray_probe_clock_gettime_type)(clockid_t, struct timespec *);
_Static_assert(__builtin_types_compatible_p(__typeof__(&clock_gettime), bray_probe_clock_gettime_type), "clock_gettime signature");
typedef int (*bray_probe_close_type)(int);
_Static_assert(__builtin_types_compatible_p(__typeof__(&close), bray_probe_close_type), "close signature");
typedef int * (*bray_probe_errno_location_type)(void);
_Static_assert(__builtin_types_compatible_p(__typeof__(&__errno_location), bray_probe_errno_location_type), "__errno_location signature");
extern __typeof__(__errno_location) bray_probe_errno_location_symbol;
__asm__(".symver bray_probe_errno_location_symbol,__errno_location@GLIBC_2.17");
typedef void * (*bray_probe_mmap_type)(void *, size_t, int, int, int, off_t);
_Static_assert(__builtin_types_compatible_p(__typeof__(&mmap), bray_probe_mmap_type), "mmap signature");
typedef int (*bray_probe_munmap_type)(void *, size_t);
_Static_assert(__builtin_types_compatible_p(__typeof__(&munmap), bray_probe_munmap_type), "munmap signature");
static __typeof__(&open) bray_probe_open = &open;
typedef int (*bray_probe_pthread_create_type)(pthread_t *, const pthread_attr_t *, void *(*)(void *), void *);
_Static_assert(__builtin_types_compatible_p(__typeof__(&pthread_create), bray_probe_pthread_create_type), "pthread_create signature");
_Static_assert(__builtin_types_compatible_p(__typeof__(environ), char **), "environ storage type");

int main(void)
{
    struct iphdr bray_probe_IpHeader = {0};
    bray_probe_IpHeader.ihl = 15;
    uint8_t bray_probe_header_length_backing = 0;
    memcpy(&bray_probe_header_length_backing, (unsigned char *)&bray_probe_IpHeader + 0, sizeof(bray_probe_header_length_backing));
    if ((bray_probe_header_length_backing & 15) >> 0 != 15)
        return 1;
    bray_probe_IpHeader.version = 15;
    uint8_t bray_probe_version_backing = 0;
    memcpy(&bray_probe_version_backing, (unsigned char *)&bray_probe_IpHeader + 0, sizeof(bray_probe_version_backing));
    if ((bray_probe_version_backing & 240) >> 4 != 15)
        return 2;
    (void)&clock_gettime;
    (void)&close;
    (void)&bray_probe_errno_location_symbol;
    (void)&mmap;
    (void)&munmap;
    (void)&open;
    (void)&pthread_create;
    (void)&environ;
    void *bray_probe_dynamic_clock_gettime_library = dlopen("libc.so.6", RTLD_NOW | RTLD_LOCAL);
    if (bray_probe_dynamic_clock_gettime_library == NULL)
        return 3;
    if (dlsym(bray_probe_dynamic_clock_gettime_library, "clock_gettime") == NULL)
        return 4;
    if (dlclose(bray_probe_dynamic_clock_gettime_library) != 0)
        return 5;
    void *bray_probe_dynamic_environ_library = dlopen("libc.so.6", RTLD_NOW | RTLD_LOCAL);
    if (bray_probe_dynamic_environ_library == NULL)
        return 6;
    if (dlsym(bray_probe_dynamic_environ_library, "environ") == NULL)
        return 7;
    if (dlclose(bray_probe_dynamic_environ_library) != 0)
        return 8;
    return 0;
}
