/* Generated by cargo xtask standard-library os-bindings generate. */
/* SDK authority: Microsoft Windows SDK 10.0.26100.0 */
/* Compiler runtime authority: Microsoft Visual C++ build tools 14.44.35207 */
/* Complete input SHA-256: 458c4fb1a6f53375106d5617948237df32fa19b3595c024c625179c18fdb0a91 */

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#define WIN32_LEAN_AND_MEAN 1
#define NOMINMAX 1
#include <windows.h>

_Static_assert(sizeof(DWORD) == 4, "DWORD size");
_Static_assert(_Alignof(DWORD) == 4, "DWORD alignment");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "DWORD signedness");
_Static_assert(sizeof(SIZE_T) == 8, "SIZE_T size");
_Static_assert(_Alignof(SIZE_T) == 8, "SIZE_T alignment");
_Static_assert(((SIZE_T)-1 < (SIZE_T)0) == 0, "SIZE_T signedness");
_Static_assert(sizeof(WCHAR) == 2, "WCHAR size");
_Static_assert(_Alignof(WCHAR) == 2, "WCHAR alignment");
_Static_assert(((WCHAR)-1 < (WCHAR)0) == 0, "WCHAR signedness");
_Static_assert((CREATE_ALWAYS) == 2, "CREATE_ALWAYS value");
_Static_assert((CREATE_NEW) == 1, "CREATE_NEW value");
_Static_assert((FILE_SHARE_DELETE) == 4, "FILE_SHARE_DELETE value");
_Static_assert((FILE_SHARE_READ) == 1, "FILE_SHARE_READ value");
_Static_assert((FILE_SHARE_WRITE) == 2, "FILE_SHARE_WRITE value");
_Static_assert((GENERIC_READ) == 2147483648, "GENERIC_READ value");
_Static_assert((GENERIC_WRITE) == 1073741824, "GENERIC_WRITE value");
_Static_assert((INFINITE) == 4294967295, "INFINITE value");
_Static_assert((MEM_COMMIT) == 4096, "MEM_COMMIT value");
_Static_assert((MEM_RELEASE) == 32768, "MEM_RELEASE value");
_Static_assert((MEM_RESERVE) == 8192, "MEM_RESERVE value");
_Static_assert((OPEN_ALWAYS) == 4, "OPEN_ALWAYS value");
_Static_assert((OPEN_EXISTING) == 3, "OPEN_EXISTING value");
_Static_assert((PAGE_READWRITE) == 4, "PAGE_READWRITE value");
_Static_assert((TRUNCATE_EXISTING) == 5, "TRUNCATE_EXISTING value");
_Static_assert(sizeof(CRITICAL_SECTION) == 40, "CRITICAL_SECTION size");
_Static_assert(_Alignof(CRITICAL_SECTION) == 8, "CRITICAL_SECTION alignment");
_Static_assert(_Alignof(FILE_NOTIFY_INFORMATION) == 4, "FILE_NOTIFY_INFORMATION alignment");
_Static_assert(offsetof(FILE_NOTIFY_INFORMATION, NextEntryOffset) == 0, "FILE_NOTIFY_INFORMATION.NextEntryOffset offset");
_Static_assert(sizeof(((FILE_NOTIFY_INFORMATION *)0)->NextEntryOffset) == sizeof(DWORD), "FILE_NOTIFY_INFORMATION.NextEntryOffset type");
_Static_assert(offsetof(FILE_NOTIFY_INFORMATION, Action) == 4, "FILE_NOTIFY_INFORMATION.Action offset");
_Static_assert(sizeof(((FILE_NOTIFY_INFORMATION *)0)->Action) == sizeof(DWORD), "FILE_NOTIFY_INFORMATION.Action type");
_Static_assert(offsetof(FILE_NOTIFY_INFORMATION, FileNameLength) == 8, "FILE_NOTIFY_INFORMATION.FileNameLength offset");
_Static_assert(sizeof(((FILE_NOTIFY_INFORMATION *)0)->FileNameLength) == sizeof(DWORD), "FILE_NOTIFY_INFORMATION.FileNameLength type");
_Static_assert(offsetof(FILE_NOTIFY_INFORMATION, FileName) == 12, "FILE_NOTIFY_INFORMATION.FileName offset");
_Static_assert(sizeof(((FILE_NOTIFY_INFORMATION *)0)->FileName[0]) == sizeof(WCHAR), "FILE_NOTIFY_INFORMATION.FileName element");
_Static_assert(sizeof(FILETIME) == 8, "FILETIME size");
_Static_assert(_Alignof(FILETIME) == 4, "FILETIME alignment");
_Static_assert(offsetof(FILETIME, dwLowDateTime) == 0, "FILETIME.dwLowDateTime offset");
_Static_assert(sizeof(((FILETIME *)0)->dwLowDateTime) == sizeof(DWORD), "FILETIME.dwLowDateTime type");
_Static_assert(offsetof(FILETIME, dwHighDateTime) == 4, "FILETIME.dwHighDateTime offset");
_Static_assert(sizeof(((FILETIME *)0)->dwHighDateTime) == sizeof(DWORD), "FILETIME.dwHighDateTime type");
_Static_assert(sizeof(LARGE_INTEGER) == 8, "LARGE_INTEGER size");
_Static_assert(_Alignof(LARGE_INTEGER) == 8, "LARGE_INTEGER alignment");
_Static_assert(offsetof(LARGE_INTEGER, QuadPart) == 0, "LARGE_INTEGER.QuadPart offset");
_Static_assert(sizeof(((LARGE_INTEGER *)0)->QuadPart) == sizeof(LONGLONG), "LARGE_INTEGER.QuadPart type");
_Static_assert(offsetof(LARGE_INTEGER, u) == 0, "LARGE_INTEGER.u offset");
_Static_assert(sizeof(((LARGE_INTEGER *)0)->u) == sizeof(__typeof__(((LARGE_INTEGER *)0)->u)), "LARGE_INTEGER.u type");
_Static_assert(sizeof(__typeof__(((LARGE_INTEGER *)0)->u)) == 8, "__typeof__(((LARGE_INTEGER *)0)->u) size");
_Static_assert(_Alignof(__typeof__(((LARGE_INTEGER *)0)->u)) == 4, "__typeof__(((LARGE_INTEGER *)0)->u) alignment");
_Static_assert(offsetof(__typeof__(((LARGE_INTEGER *)0)->u), LowPart) == 0, "__typeof__(((LARGE_INTEGER *)0)->u).LowPart offset");
_Static_assert(sizeof(((__typeof__(((LARGE_INTEGER *)0)->u) *)0)->LowPart) == sizeof(DWORD), "__typeof__(((LARGE_INTEGER *)0)->u).LowPart type");
_Static_assert(offsetof(__typeof__(((LARGE_INTEGER *)0)->u), HighPart) == 4, "__typeof__(((LARGE_INTEGER *)0)->u).HighPart offset");
_Static_assert(sizeof(((__typeof__(((LARGE_INTEGER *)0)->u) *)0)->HighPart) == sizeof(LONG), "__typeof__(((LARGE_INTEGER *)0)->u).HighPart type");
_Static_assert(sizeof(SECURITY_ATTRIBUTES *) == sizeof(void *), "SECURITY_ATTRIBUTES pointer representation");
typedef DWORD (*bray_probe_ThreadStartRoutine)(LPVOID);
_Static_assert(__builtin_types_compatible_p(LPTHREAD_START_ROUTINE, bray_probe_ThreadStartRoutine), "LPTHREAD_START_ROUTINE callback");
typedef ULONGLONG (*bray_probe_TickCountRoutine)(void);
_Static_assert(__builtin_types_compatible_p(ULONGLONG (*)(void), bray_probe_TickCountRoutine), "ULONGLONG (*)(void) callback");
_Static_assert(sizeof(DWORD) == 4, "FileNotifyInformation.next_entry_offset Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "FileNotifyInformation.next_entry_offset Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "FileNotifyInformation.action Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "FileNotifyInformation.action Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "FileNotifyInformation.file_name_length Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "FileNotifyInformation.file_name_length Bray integer signedness");
_Static_assert(sizeof(WCHAR) == 2, "FileNotifyInformation.file_name Bray integer size");
_Static_assert(((WCHAR)-1 < (WCHAR)0) == 0, "FileNotifyInformation.file_name Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "FileTime.low Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "FileTime.low Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "FileTime.high Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "FileTime.high Bray integer signedness");
_Static_assert(sizeof(LONGLONG) == 8, "LargeInteger.quad_part Bray integer size");
_Static_assert(((LONGLONG)-1 < (LONGLONG)0) == 1, "LargeInteger.quad_part Bray integer signedness");
_Static_assert(__builtin_types_compatible_p(__typeof__(((LARGE_INTEGER *)0)->u), __typeof__(((LARGE_INTEGER *)0)->u)), "LargeInteger.parts Bray named type");
_Static_assert(sizeof(DWORD) == 4, "LargeIntegerParts.low_part Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "LargeIntegerParts.low_part Bray integer signedness");
_Static_assert(sizeof(LONG) == 4, "LargeIntegerParts.high_part Bray integer size");
_Static_assert(((LONG)-1 < (LONG)0) == 1, "LargeIntegerParts.high_part Bray integer signedness");
_Static_assert(sizeof(LPVOID) == sizeof(void *), "ThreadStartRoutine parameter context Bray pointer representation");
_Static_assert(sizeof(DWORD) == 4, "ThreadStartRoutine result Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "ThreadStartRoutine result Bray integer signedness");
_Static_assert(sizeof(ULONGLONG) == 8, "TickCountRoutine result Bray integer size");
_Static_assert(((ULONGLONG)-1 < (ULONGLONG)0) == 0, "TickCountRoutine result Bray integer signedness");
_Static_assert(sizeof(HANDLE) == sizeof(void *), "close_handle parameter handle Bray pointer representation");
_Static_assert(sizeof(BOOL) == 4, "close_handle result Bray integer size");
_Static_assert(((BOOL)-1 < (BOOL)0) == 1, "close_handle result Bray integer signedness");
_Static_assert(sizeof(LPSECURITY_ATTRIBUTES) == sizeof(void *), "create_thread parameter attributes Bray pointer representation");
_Static_assert(sizeof(SIZE_T) == 8, "create_thread parameter stack_size Bray integer size");
_Static_assert(((SIZE_T)-1 < (SIZE_T)0) == 0, "create_thread parameter stack_size Bray integer signedness");
_Static_assert(__builtin_types_compatible_p(LPTHREAD_START_ROUTINE, LPTHREAD_START_ROUTINE), "create_thread parameter entry Bray named type");
_Static_assert(sizeof(LPVOID) == sizeof(void *), "create_thread parameter context Bray pointer representation");
_Static_assert(sizeof(DWORD) == 4, "create_thread parameter creation_flags Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "create_thread parameter creation_flags Bray integer signedness");
_Static_assert(sizeof(LPDWORD) == sizeof(void *), "create_thread parameter thread_identifier Bray pointer representation");
_Static_assert(sizeof(HANDLE) == sizeof(void *), "create_thread result Bray pointer representation");
_Static_assert(sizeof(DWORD) == 4, "get_last_error result Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "get_last_error result Bray integer signedness");
_Static_assert(sizeof(LPVOID) == sizeof(void *), "virtual_alloc parameter address Bray pointer representation");
_Static_assert(sizeof(SIZE_T) == 8, "virtual_alloc parameter size Bray integer size");
_Static_assert(((SIZE_T)-1 < (SIZE_T)0) == 0, "virtual_alloc parameter size Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "virtual_alloc parameter allocation_type Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "virtual_alloc parameter allocation_type Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "virtual_alloc parameter protection Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "virtual_alloc parameter protection Bray integer signedness");
_Static_assert(sizeof(LPVOID) == sizeof(void *), "virtual_alloc result Bray pointer representation");
_Static_assert(sizeof(LPVOID) == sizeof(void *), "virtual_free parameter address Bray pointer representation");
_Static_assert(sizeof(SIZE_T) == 8, "virtual_free parameter size Bray integer size");
_Static_assert(((SIZE_T)-1 < (SIZE_T)0) == 0, "virtual_free parameter size Bray integer signedness");
_Static_assert(sizeof(DWORD) == 4, "virtual_free parameter free_type Bray integer size");
_Static_assert(((DWORD)-1 < (DWORD)0) == 0, "virtual_free parameter free_type Bray integer signedness");
_Static_assert(sizeof(BOOL) == 4, "virtual_free result Bray integer size");
_Static_assert(((BOOL)-1 < (BOOL)0) == 1, "virtual_free result Bray integer signedness");
typedef BOOL (*bray_probe_close_handle_type)(HANDLE);
_Static_assert(__builtin_types_compatible_p(__typeof__(&CloseHandle), bray_probe_close_handle_type), "CloseHandle signature");
typedef HANDLE (*bray_probe_create_thread_type)(LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
_Static_assert(__builtin_types_compatible_p(__typeof__(&CreateThread), bray_probe_create_thread_type), "CreateThread signature");
typedef DWORD (*bray_probe_get_last_error_type)(void);
_Static_assert(__builtin_types_compatible_p(__typeof__(&GetLastError), bray_probe_get_last_error_type), "GetLastError signature");
typedef LPVOID (*bray_probe_virtual_alloc_type)(LPVOID, SIZE_T, DWORD, DWORD);
_Static_assert(__builtin_types_compatible_p(__typeof__(&VirtualAlloc), bray_probe_virtual_alloc_type), "VirtualAlloc signature");
typedef BOOL (*bray_probe_virtual_free_type)(LPVOID, SIZE_T, DWORD);
_Static_assert(__builtin_types_compatible_p(__typeof__(&VirtualFree), bray_probe_virtual_free_type), "VirtualFree signature");

int main(void)
{
    (void)&CloseHandle;
    (void)&CreateThread;
    (void)&GetLastError;
    (void)&VirtualAlloc;
    (void)&VirtualFree;
    HMODULE bray_probe_dynamic_get_tick_count_library = LoadLibraryA("kernel32.dll");
    if (bray_probe_dynamic_get_tick_count_library == NULL)
        return 1;
    if (GetProcAddress(bray_probe_dynamic_get_tick_count_library, "GetTickCount64") == NULL)
        return 2;
    if (!FreeLibrary(bray_probe_dynamic_get_tick_count_library))
        return 3;
    return 0;
}
