/* Generated by cargo xtask standard-library os-bindings generate. */
/* SDK authority: Apple macOS SDK 15.5 */
/* Complete input SHA-256: 458c4fb1a6f53375106d5617948237df32fa19b3595c024c625179c18fdb0a91 */

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <Availability.h>
#include <CoreFoundation/CoreFoundation.h>
#include <dlfcn.h>
#include <fcntl.h>
#include <pthread.h>
#include <signal.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>

_Static_assert(__MAC_OS_X_VERSION_MAX_ALLOWED == 150500, "macOS SDK revision");
_Static_assert(sizeof(clockid_t) == 4, "clockid_t size");
_Static_assert(_Alignof(clockid_t) == 4, "clockid_t alignment");
_Static_assert(((clockid_t)-1 < (clockid_t)0) == 0, "clockid_t signedness");
_Static_assert(sizeof(off_t) == 8, "off_t size");
_Static_assert(_Alignof(off_t) == 8, "off_t alignment");
_Static_assert(((off_t)-1 < (off_t)0) == 1, "off_t signedness");
_Static_assert(sizeof(pthread_t) == 8, "pthread_t size");
_Static_assert(_Alignof(pthread_t) == 8, "pthread_t alignment");
_Static_assert(((pthread_t)-1 < (pthread_t)0) == 0, "pthread_t signedness");
_Static_assert(sizeof(time_t) == 8, "time_t size");
_Static_assert(_Alignof(time_t) == 8, "time_t alignment");
_Static_assert(((time_t)-1 < (time_t)0) == 1, "time_t signedness");
_Static_assert((AT_FDCWD) == -2, "AT_FDCWD value");
_Static_assert((CLOCK_MONOTONIC) == 6, "CLOCK_MONOTONIC value");
_Static_assert((MAP_ANON) == 4096, "MAP_ANON value");
_Static_assert((MAP_PRIVATE) == 2, "MAP_PRIVATE value");
_Static_assert((MAP_SHARED) == 1, "MAP_SHARED value");
_Static_assert((O_CLOEXEC) == 16777216, "O_CLOEXEC value");
_Static_assert((O_RDONLY) == 0, "O_RDONLY value");
_Static_assert((O_RDWR) == 2, "O_RDWR value");
_Static_assert((O_WRONLY) == 1, "O_WRONLY value");
_Static_assert((PROT_EXEC) == 4, "PROT_EXEC value");
_Static_assert((PROT_NONE) == 0, "PROT_NONE value");
_Static_assert((PROT_READ) == 1, "PROT_READ value");
_Static_assert((PROT_WRITE) == 2, "PROT_WRITE value");
_Static_assert(sizeof(pthread_attr_t *) == sizeof(void *), "pthread_attr_t pointer representation");
_Static_assert(sizeof(pthread_mutex_t) == 64, "pthread_mutex_t size");
_Static_assert(_Alignof(pthread_mutex_t) == 8, "pthread_mutex_t alignment");
_Static_assert(sizeof(union sigval) == 8, "union sigval size");
_Static_assert(_Alignof(union sigval) == 8, "union sigval alignment");
_Static_assert(offsetof(union sigval, sival_int) == 0, "union sigval.sival_int offset");
_Static_assert(sizeof(((union sigval *)0)->sival_int) == sizeof(int), "union sigval.sival_int type");
_Static_assert(offsetof(union sigval, sival_ptr) == 0, "union sigval.sival_ptr offset");
_Static_assert(sizeof(((union sigval *)0)->sival_ptr) == sizeof(void *), "union sigval.sival_ptr type");
_Static_assert(sizeof(struct timespec) == 16, "struct timespec size");
_Static_assert(_Alignof(struct timespec) == 8, "struct timespec alignment");
_Static_assert(offsetof(struct timespec, tv_sec) == 0, "struct timespec.tv_sec offset");
_Static_assert(sizeof(((struct timespec *)0)->tv_sec) == sizeof(time_t), "struct timespec.tv_sec type");
_Static_assert(offsetof(struct timespec, tv_nsec) == 8, "struct timespec.tv_nsec offset");
_Static_assert(sizeof(((struct timespec *)0)->tv_nsec) == sizeof(long), "struct timespec.tv_nsec type");
typedef int (*bray_probe_ClockGetTime)(clockid_t, struct timespec *);
_Static_assert(__builtin_types_compatible_p(int (*)(clockid_t, struct timespec *), bray_probe_ClockGetTime), "int (*)(clockid_t, struct timespec *) callback");
typedef void * (*bray_probe_ThreadStartRoutine)(void *);
_Static_assert(__builtin_types_compatible_p(void *(*)(void *), bray_probe_ThreadStartRoutine), "void *(*)(void *) callback");
_Static_assert(sizeof(int) == 4, "SignalValue.integer Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "SignalValue.integer Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "SignalValue.pointer Bray pointer representation");
_Static_assert(sizeof(time_t) == 8, "Timespec.seconds Bray integer size");
_Static_assert(((time_t)-1 < (time_t)0) == 1, "Timespec.seconds Bray integer signedness");
_Static_assert(sizeof(long) == 8, "Timespec.nanoseconds Bray integer size");
_Static_assert(((long)-1 < (long)0) == 1, "Timespec.nanoseconds Bray integer signedness");
_Static_assert(sizeof(clockid_t) == 4, "ClockGetTime parameter clock Bray integer size");
_Static_assert(((clockid_t)-1 < (clockid_t)0) == 0, "ClockGetTime parameter clock Bray integer signedness");
_Static_assert(sizeof(struct timespec *) == sizeof(void *), "ClockGetTime parameter time Bray pointer representation");
_Static_assert(sizeof(int) == 4, "ClockGetTime result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "ClockGetTime result Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "ThreadStartRoutine parameter context Bray pointer representation");
_Static_assert(sizeof(void *) == sizeof(void *), "ThreadStartRoutine result Bray pointer representation");
_Static_assert(__builtin_types_compatible_p(CFAbsoluteTime, double), "cf_absolute_time_get_current result Bray floating-point type");
_Static_assert(sizeof(clockid_t) == 4, "clock_gettime parameter clock Bray integer size");
_Static_assert(((clockid_t)-1 < (clockid_t)0) == 0, "clock_gettime parameter clock Bray integer signedness");
_Static_assert(sizeof(struct timespec *) == sizeof(void *), "clock_gettime parameter time Bray pointer representation");
_Static_assert(sizeof(int) == 4, "clock_gettime result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "clock_gettime result Bray integer signedness");
_Static_assert(sizeof(int) == 4, "close parameter descriptor Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "close parameter descriptor Bray integer signedness");
_Static_assert(sizeof(int) == 4, "close result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "close result Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "mmap parameter address Bray pointer representation");
_Static_assert(sizeof(size_t) == 8, "mmap parameter length Bray integer size");
_Static_assert(((size_t)-1 < (size_t)0) == 0, "mmap parameter length Bray integer signedness");
_Static_assert(sizeof(int) == 4, "mmap parameter protection Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "mmap parameter protection Bray integer signedness");
_Static_assert(sizeof(int) == 4, "mmap parameter flags Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "mmap parameter flags Bray integer signedness");
_Static_assert(sizeof(int) == 4, "mmap parameter descriptor Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "mmap parameter descriptor Bray integer signedness");
_Static_assert(sizeof(off_t) == 8, "mmap parameter offset Bray integer size");
_Static_assert(((off_t)-1 < (off_t)0) == 1, "mmap parameter offset Bray integer signedness");
_Static_assert(sizeof(void *) == sizeof(void *), "mmap result Bray pointer representation");
_Static_assert(sizeof(void *) == sizeof(void *), "munmap parameter address Bray pointer representation");
_Static_assert(sizeof(size_t) == 8, "munmap parameter length Bray integer size");
_Static_assert(((size_t)-1 < (size_t)0) == 0, "munmap parameter length Bray integer signedness");
_Static_assert(sizeof(int) == 4, "munmap result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "munmap result Bray integer signedness");
_Static_assert(sizeof(const char *) == sizeof(void *), "open parameter path Bray pointer representation");
_Static_assert(sizeof(int) == 4, "open parameter flags Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "open parameter flags Bray integer signedness");
_Static_assert(sizeof(int) == 4, "open result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "open result Bray integer signedness");
_Static_assert(sizeof(pthread_t *) == sizeof(void *), "pthread_create parameter thread Bray pointer representation");
_Static_assert(sizeof(const pthread_attr_t *) == sizeof(void *), "pthread_create parameter attributes Bray pointer representation");
_Static_assert(__builtin_types_compatible_p(void *(*)(void *), void *(*)(void *)), "pthread_create parameter entry Bray named type");
_Static_assert(sizeof(void *) == sizeof(void *), "pthread_create parameter context Bray pointer representation");
_Static_assert(sizeof(int) == 4, "pthread_create result Bray integer size");
_Static_assert(((int)-1 < (int)0) == 1, "pthread_create result Bray integer signedness");
_Static_assert(sizeof(char **) == sizeof(void *), "ENVIRON Bray pointer representation");
typedef CFAbsoluteTime (*bray_probe_cf_absolute_time_get_current_type)(void);
_Static_assert(__builtin_types_compatible_p(__typeof__(&CFAbsoluteTimeGetCurrent), bray_probe_cf_absolute_time_get_current_type), "CFAbsoluteTimeGetCurrent signature");
typedef int (*bray_probe_clock_gettime_type)(clockid_t, struct timespec *);
_Static_assert(__builtin_types_compatible_p(__typeof__(&clock_gettime), bray_probe_clock_gettime_type), "clock_gettime signature");
typedef int (*bray_probe_close_type)(int);
_Static_assert(__builtin_types_compatible_p(__typeof__(&close), bray_probe_close_type), "close signature");
typedef void * (*bray_probe_mmap_type)(void *, size_t, int, int, int, off_t);
_Static_assert(__builtin_types_compatible_p(__typeof__(&mmap), bray_probe_mmap_type), "mmap signature");
typedef int (*bray_probe_munmap_type)(void *, size_t);
_Static_assert(__builtin_types_compatible_p(__typeof__(&munmap), bray_probe_munmap_type), "munmap signature");
static __typeof__(&open) bray_probe_open = &open;
typedef int (*bray_probe_pthread_create_type)(pthread_t *, const pthread_attr_t *, void *(*)(void *), void *);
_Static_assert(__builtin_types_compatible_p(__typeof__(&pthread_create), bray_probe_pthread_create_type), "pthread_create signature");
_Static_assert(__builtin_types_compatible_p(__typeof__(environ), char **), "environ storage type");

int main(void)
{
    (void)&CFAbsoluteTimeGetCurrent;
    (void)&clock_gettime;
    (void)&close;
    (void)&mmap;
    (void)&munmap;
    (void)&open;
    (void)&pthread_create;
    (void)&environ;
    void *bray_probe_dynamic_clock_gettime_library = dlopen("/usr/lib/libSystem.B.dylib", RTLD_NOW | RTLD_LOCAL);
    if (bray_probe_dynamic_clock_gettime_library == NULL)
        return 1;
    if (dlsym(bray_probe_dynamic_clock_gettime_library, "clock_gettime") == NULL)
        return 2;
    if (dlclose(bray_probe_dynamic_clock_gettime_library) != 0)
        return 3;
    void *bray_probe_dynamic_environ_library = dlopen("/usr/lib/libSystem.B.dylib", RTLD_NOW | RTLD_LOCAL);
    if (bray_probe_dynamic_environ_library == NULL)
        return 4;
    if (dlsym(bray_probe_dynamic_environ_library, "environ") == NULL)
        return 5;
    if (dlclose(bray_probe_dynamic_environ_library) != 0)
        return 6;
    return 0;
}
