[package]
name = "bray-linker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-platform = { path = "../bray-platform" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }

[dev-dependencies]
bray-testing = { path = "../bray-testing", features = ["mir-unit"] }

[lints]
workspace = true
