[package]
name = "bray-linker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }

[lints]
workspace = true
