[package]
name = "bray-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-base = { path = "../bray-base" }
bray-bound-tree = { path = "../bray-bound-tree" }
bray-runtime-interface = { path = "../bray-runtime-interface" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }
bray-target = { path = "../bray-target" }

[dev-dependencies]
bray-target = { path = "../bray-target", features = ["test-support"] }
bray-testing = { path = "../bray-testing", features = ["bound-unit"] }

[lints]
workspace = true
