[package]
name = "bray-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bray-bound-tree = { path = "../bray-bound-tree" }
bray-compilation = { path = "../bray-compilation" }
bray-declarations = { path = "../bray-declarations" }
bray-diagnostics = { path = "../bray-diagnostics" }
bray-messages = { path = "../bray-messages" }
bray-package-interface = { path = "../bray-package-interface" }
bray-project = { path = "../bray-project" }
bray-source = { path = "../bray-source" }
bray-symbols = { path = "../bray-symbols" }
bray-syntax = { path = "../bray-syntax" }
bray-target = { path = "../bray-target" }
bray-tooling = { path = "../bray-tooling" }

crossbeam-channel = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
bray-testing = { path = "../bray-testing" }

[lints]
workspace = true
