/// Compiler-provided memory operation named by a structured diagnostic.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum DiagnosticMemoryOperation {
    UninitializedStorage,
    UninitializedStoragePointer,
    MutableUninitializedStoragePointer,
    ProtectedStorageWrite,
    AssumeInitialized,
    MoveInitialized,
    AnchoredSharedBorrow,
    AnchoredMutableBorrow,
    AddressOf,
    MutableAddressOf,
    NullPointer,
    PointerNullCheck,
    PointerElementOffset,
    PointerByteOffset,
    PointerReinterpretation,
    CallableFromPointer,
    PointerFromCallable,
    CallbackState,
    PointerRead,
    PointerWrite,
    MemoryCopy,
    OverlappingMemoryCopy,
    SizeDetermination,
    AlignmentDetermination,
    StrideDetermination,
    LayoutDetermination,
    TrailingLayoutDetermination,
    RawAllocation,
    RawDeallocation,
    Allocation,
    Deallocation,
    RawBufferCapacity,
    RawBufferInitializedCount,
    RawBufferPointer,
    RawBufferInitializedSlice,
    MutableRawBufferInitializedSlice,
    RawBufferSparePointer,
    RawBufferSetInitializedCount,
    RawBufferRelease,
    RawBufferReplace,
    RawBufferRelocate,
    ByteBufferFill,
    ByteSliceCopy,
    ByteBufferRead,
    SliceLength,
    VolatileRead,
    VolatileWrite,
    PointerExposeAddress,
    PointerFromExposedAddress,
    PointerAddressComparison,
    CompilerFence,
    HardwareFence,
    CatastrophicAbort,
    DebuggerTrap,
    UnreachableTermination,
    SpinLoopHint,
    TargetFeatureCheck,
    InlineAssembly,
    AtomicInitialization,
    AtomicLoad,
    AtomicStore,
    AtomicExchange,
    AtomicCompareExchange,
    AtomicCompareExchangeWeak,
    AtomicFetchAdd,
    AtomicFetchSubtract,
    AtomicFetchAnd,
    AtomicFetchOr,
    AtomicFetchXor,
    AtomicFence,
    AtomicCompilerFence,
    AtomicWait,
    AtomicNotifyOne,
    AtomicNotifyAll,
}

impl DiagnosticMemoryOperation {
    /// Returns the stable machine key for this memory operation.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::UninitializedStorage => "uninitialized_storage",
            Self::UninitializedStoragePointer => "uninitialized_storage_pointer",
            Self::MutableUninitializedStoragePointer => "mutable_uninitialized_storage_pointer",
            Self::ProtectedStorageWrite => "protected_storage_write",
            Self::AssumeInitialized => "assume_initialized",
            Self::MoveInitialized => "move_initialized",
            Self::AnchoredSharedBorrow => "anchored_shared_borrow",
            Self::AnchoredMutableBorrow => "anchored_mutable_borrow",
            Self::AddressOf => "address_of",
            Self::MutableAddressOf => "mutable_address_of",
            Self::NullPointer => "null_pointer",
            Self::PointerNullCheck => "pointer_null_check",
            Self::PointerElementOffset => "pointer_element_offset",
            Self::PointerByteOffset => "pointer_byte_offset",
            Self::PointerReinterpretation => "pointer_reinterpretation",
            Self::CallableFromPointer => "callable_from_pointer",
            Self::PointerFromCallable => "pointer_from_callable",
            Self::CallbackState => "callback_state",
            Self::PointerRead => "pointer_read",
            Self::PointerWrite => "pointer_write",
            Self::MemoryCopy => "memory_copy",
            Self::OverlappingMemoryCopy => "overlapping_memory_copy",
            Self::SizeDetermination => "size_determination",
            Self::AlignmentDetermination => "alignment_determination",
            Self::StrideDetermination => "stride_determination",
            Self::LayoutDetermination => "layout_determination",
            Self::TrailingLayoutDetermination => "trailing_layout_determination",
            Self::RawAllocation => "raw_allocation",
            Self::RawDeallocation => "raw_deallocation",
            Self::Allocation => "allocation",
            Self::Deallocation => "deallocation",
            Self::RawBufferCapacity => "raw_buffer_capacity",
            Self::RawBufferInitializedCount => "raw_buffer_initialized_count",
            Self::RawBufferPointer => "raw_buffer_pointer",
            Self::RawBufferInitializedSlice => "raw_buffer_initialized_slice",
            Self::MutableRawBufferInitializedSlice => "mutable_raw_buffer_initialized_slice",
            Self::RawBufferSparePointer => "raw_buffer_spare_pointer",
            Self::RawBufferSetInitializedCount => "raw_buffer_set_initialized_count",
            Self::RawBufferRelease => "raw_buffer_release",
            Self::RawBufferReplace => "raw_buffer_replace",
            Self::RawBufferRelocate => "raw_buffer_relocate",
            Self::ByteBufferFill => "byte_buffer_fill",
            Self::ByteSliceCopy => "byte_slice_copy",
            Self::ByteBufferRead => "byte_buffer_read",
            Self::SliceLength => "slice_length",
            Self::VolatileRead => "volatile_read",
            Self::VolatileWrite => "volatile_write",
            Self::PointerExposeAddress => "pointer_expose_address",
            Self::PointerFromExposedAddress => "pointer_from_exposed_address",
            Self::PointerAddressComparison => "pointer_address_comparison",
            Self::CompilerFence => "compiler_fence",
            Self::HardwareFence => "hardware_fence",
            Self::CatastrophicAbort => "catastrophic_abort",
            Self::DebuggerTrap => "debugger_trap",
            Self::UnreachableTermination => "unreachable_termination",
            Self::SpinLoopHint => "spin_loop_hint",
            Self::TargetFeatureCheck => "target_feature_check",
            Self::InlineAssembly => "inline_assembly",
            Self::AtomicInitialization => "atomic_initialization",
            Self::AtomicLoad => "atomic_load",
            Self::AtomicStore => "atomic_store",
            Self::AtomicExchange => "atomic_exchange",
            Self::AtomicCompareExchange => "atomic_compare_exchange",
            Self::AtomicCompareExchangeWeak => "atomic_compare_exchange_weak",
            Self::AtomicFetchAdd => "atomic_fetch_add",
            Self::AtomicFetchSubtract => "atomic_fetch_subtract",
            Self::AtomicFetchAnd => "atomic_fetch_and",
            Self::AtomicFetchOr => "atomic_fetch_or",
            Self::AtomicFetchXor => "atomic_fetch_xor",
            Self::AtomicFence => "atomic_fence",
            Self::AtomicCompilerFence => "atomic_compiler_fence",
            Self::AtomicWait => "atomic_wait",
            Self::AtomicNotifyOne => "atomic_notify_one",
            Self::AtomicNotifyAll => "atomic_notify_all",
        }
    }
}

/// Exact source contract violated by a callback-state request.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum DiagnosticCallbackStateProblem {
    OutsideCallable,
    LanguageAbi,
    CallableNotTrusted,
    ReceiverPresent,
    MissingSymbolDirective,
    MissingContextParameter,
    ContextArgumentNotName,
    ContextArgumentNotParameter,
    ContextParameterNotFirst { actual_ordinal: u64 },
}

impl DiagnosticCallbackStateProblem {
    /// Returns the stable machine key for this callback-state problem.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::OutsideCallable => "outside_callable",
            Self::LanguageAbi => "language_abi",
            Self::CallableNotTrusted => "callable_not_trusted",
            Self::ReceiverPresent => "receiver_present",
            Self::MissingSymbolDirective => "missing_symbol_directive",
            Self::MissingContextParameter => "missing_context_parameter",
            Self::ContextArgumentNotName => "context_argument_not_name",
            Self::ContextArgumentNotParameter => "context_argument_not_parameter",
            Self::ContextParameterNotFirst { .. } => "context_parameter_not_first",
        }
    }
}
